"use client";
import "@/components/broker.css";
import { ArrowLeft, Check, MessageSquare } from "lucide-react";
import Link from "@/components/native-link";
import { use, useEffect, useState } from "react";
import { useDemo } from "@/components/demo-provider";
import { formatPremium, formatPrice, formatCoverageCell } from "@/lib/display";
import { insuranceTerms } from "@/lib/insurance-terms";
import { categoryFields } from "@/lib/catalog";
import type { Lead, ChatCard } from "@/lib/types";

export default function BrokerLeadPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params);
  const { state, updateLead } = useDemo();
  const lead = state.leads.find((item) => item.id === id);
  const [elapsed, setElapsed] = useState<number | null>(0);
  const [note, setNote] = useState("");
  const [outcome, setOutcome] = useState<"interested" | "follow_up" | "not_interested">("interested");
  useEffect(() => { const call = lead?.calls.find((item) => !item.endedAt); if (!call) return; const tick = () => { const started = Date.parse(call.startedAt); setElapsed(Number.isFinite(started) && started <= Date.now() ? Math.floor((Date.now() - started) / 1000) : null); }; tick(); const timer = window.setInterval(tick, 1000); return () => window.clearInterval(timer); }, [lead?.calls]);
  if (!lead) return <main className="broker-workspace broker-lead-page"><div className="broker-container broker-empty"><MessageSquare size={32} aria-hidden="true"/><h1>ไม่พบคำขอ</h1><p>ลิงก์นี้ไม่มีคำขอในข้อมูลเดโมของเบราว์เซอร์นี้</p><Link href="/broker" className="broker-secondary">กลับ Dashboard</Link></div></main>;
  const currentLead: Lead = lead;
  const activeCall = currentLead.calls.find((call) => !call.endedAt);
  function patch(next: Partial<Lead>) { updateLead({ ...currentLead, ...next, updatedAt: new Date().toISOString() }); }
  function accept() { if (currentLead.status === "new") patch({ status: "contacting" }); }
  function startCall() { if (activeCall || !["contacting", "follow_up"].includes(currentLead.status)) return; patch({ status: "contacting", calls: [...currentLead.calls, { id: crypto.randomUUID(), startedAt: new Date().toISOString(), endedAt: null, outcome: null, note: "" }] }); }
  function endCall() { if (!activeCall || !note.trim()) return; patch({ status: outcome === "follow_up" ? "follow_up" : "closed", calls: currentLead.calls.map((call) => call.id === activeCall.id ? { ...call, endedAt: new Date().toISOString(), outcome, note: note.trim() } : call), notes: note.trim() }); setNote(""); document.getElementById("call-title")?.focus({preventScroll:true}); }
  const statusLabel={new:"ใหม่",contacting:"กำลังติดต่อ",follow_up:"ติดตามผล",closed:"ปิดเรื่อง"}[lead.status];
  return <main className="broker-workspace broker-lead-page"><div className="broker-demo-strip">โหมดผู้เชี่ยวชาญ · การสนทนาจำลอง ไม่มีการโทรจริง</div><div className="broker-container">
   <Link href="/broker" className="broker-back"><ArrowLeft size={16} aria-hidden="true"/>กลับ Dashboard</Link>
   <header className="broker-detail-heading"><div><p className="broker-eyebrow">คำขอผู้เชี่ยวชาญ</p><h1>{lead.displayName}</h1><p>ส่งเมื่อ <time dateTime={lead.createdAt}>{new Date(lead.createdAt).toLocaleString("th-TH",{timeZone:"Asia/Bangkok"})}</time></p></div><span className={`broker-status broker-status-${lead.status}`} role="status">{statusLabel}</span></header>
   <div className="broker-detail-grid"><div className="broker-detail-main">
    <section className="broker-panel" aria-labelledby="lead-summary-title"><div className="broker-panel-heading"><h2 id="lead-summary-title">สรุปความต้องการ</h2><span className="broker-muted">ข้อมูล ณ ตอนส่ง</span></div><dl className="broker-summary-grid"><div><dt>ประเภทประกัน</dt><dd>{{health:"สุขภาพ",motor:"รถยนต์",life:"ชีวิต",accident:"อุบัติเหตุ",travel:"เดินทาง",property:"ทรัพย์สิน",liability:"ความรับผิด"}[lead.summary.category]}</dd></div><div><dt>งบประมาณ</dt><dd>{lead.summary.budgetTHB===null?"ยังไม่ได้ระบุ":`${lead.summary.budgetTHB.toLocaleString("th-TH")} บาท`}</dd></div><div><dt>สะดวกติดต่อ</dt><dd>ช่วง{{morning:"เช้า",afternoon:"บ่าย",evening:"เย็น"}[lead.contactWindow]}</dd></div><div><dt>คะแนนกิจกรรมเดโม</dt><dd>{lead.interestScore}<small> / 100</small></dd></div><div className="broker-summary-wide"><dt>แผนที่สนใจ</dt><dd>{lead.summary.interestedPlanIds.map(planId=>lead.planFacts?.find(plan=>plan.id===planId)?.name??`${planId} (ไม่มีชื่อที่บันทึกไว้)`).join(" · ")||"ยังไม่ได้เลือก"}</dd></div><div className="broker-summary-wide"><dt>สิ่งที่อยากให้ช่วย</dt><dd>{lead.summary.needs.join(" · ")||"ยังไม่ระบุ"}</dd></div><div className="broker-summary-wide"><dt>คำถามถึงผู้เชี่ยวชาญ</dt><dd>{lead.summary.questions.join(" · ")||"ยังไม่ระบุ"}</dd></div></dl><p className="broker-consent"><Check size={16} aria-hidden="true"/>ยินยอมส่งข้อมูลเมื่อ <time dateTime={lead.consentAt}>{new Date(lead.consentAt).toLocaleString("th-TH",{timeZone:"Asia/Bangkok"})}</time></p></section>
    <section className="broker-panel" aria-labelledby="saved-plans-title"><div className="broker-panel-heading"><h2 id="saved-plans-title">ข้อมูลแผน ณ ตอนส่ง</h2><span className="broker-muted">{lead.planFacts?.length??0} แผน</span></div>{lead.planFacts?.length?lead.planFacts.map(plan=><div key={plan.id} className="broker-saved-plan"><h3>{plan.name}</h3><p>{plan.price?formatPrice(plan.price):formatPremium(plan.premiumTHB,plan.premiumPeriod,plan.premiumNote)}</p><a href={plan.source.url} target="_blank" rel="noreferrer" className="broker-source">{plan.source.label} ↗</a></div>):<p className="broker-muted">คำขอเก่าไม่มีข้อมูลแผนที่บันทึกไว้</p>}</section>
    <section className="broker-panel broker-transcript" aria-labelledby="transcript-title"><div className="broker-panel-heading"><h2 id="transcript-title">บทสนทนาตอนส่งคำขอ</h2><span className="broker-muted">อ่านอย่างเดียว</span></div>{lead.transcript.length?lead.transcript.map((message,index)=><div key={index} className={`broker-message broker-message-${message.role}`}><p className="broker-message-label">{message.role==="user"?"ลูกค้าเดโม":message.mode==="live"?"Live AI":message.mode==="mock"?"บทสนทนาตัวอย่าง":"ประวัติ AI (ไม่ระบุโหมด)"}</p><p className="broker-message-content">{message.content}</p>{message.role==="assistant"&&message.cards?.map((card,j)=><HistoricalCard key={j} card={card} lead={lead}/>)}</div>):<p className="broker-muted">ส่งความสนใจจากหน้าแผนโดยตรง</p>}</section>
   </div><aside className="broker-detail-side">
    <section className="broker-panel broker-call-panel" aria-labelledby="call-title"><p className="broker-eyebrow">ขั้นตอนถัดไป</p><h2 id="call-title" tabIndex={-1}>{lead.status==="closed"?"ปิดเรื่องแล้ว":activeCall?"บันทึกการสนทนา":lead.status==="new"?"รับเรื่องเพื่อเริ่มดูแล":lead.status==="follow_up"?"พร้อมติดตามผล":"เริ่มสนทนากับลูกค้า"}</h2><p className="broker-muted">{lead.status==="closed"?"อ่านสรุปและประวัติการดูแลได้ด้านล่าง":"การสนทนาจำลองสำหรับเดโม ไม่มีการติดต่อหรือโทรจริง"}</p><div className="broker-call-actions"><button type="button" onClick={accept} disabled={lead.status!=="new"} className="broker-primary">รับเรื่อง</button><button type="button" onClick={startCall} disabled={Boolean(activeCall)||!["contacting","follow_up"].includes(lead.status)} className="broker-secondary">เริ่มสนทนา</button></div>
     {activeCall&&<div className="broker-call-form"><p className="broker-timer">กำลังสนทนา <strong>{elapsed===null?"ไม่ทราบเวลาเริ่ม":`${Math.floor(elapsed/60)}:${String(elapsed%60).padStart(2,"0")}`}</strong></p><label htmlFor="lead-note">บันทึกผล</label><textarea id="lead-note" value={note} onChange={event=>setNote(event.target.value)} maxLength={2000} aria-describedby="lead-note-hint" placeholder="สิ่งที่คุย และสิ่งที่จะทำต่อ"/><p id="lead-note-hint" className="broker-muted">เขียนบันทึกก่อนบันทึกผล · {note.length.toLocaleString("th-TH")}/2,000</p><label htmlFor="lead-outcome">ผลการสนทนา</label><select id="lead-outcome" value={outcome} onChange={event=>setOutcome(event.target.value as typeof outcome)}><option value="interested">สนใจต่อ</option><option value="follow_up">นัดติดตาม</option><option value="not_interested">ไม่สนใจ</option></select><button type="button" onClick={endCall} disabled={!note.trim()} className="broker-primary">บันทึกผล</button></div>}
    </section>
    <section className="broker-panel" aria-labelledby="call-history-title"><div className="broker-panel-heading"><h2 id="call-history-title">ประวัติการสนทนา</h2><span className="broker-muted">{currentLead.calls.length} ครั้ง</span></div>{currentLead.calls.length?<ol className="broker-call-history">{[...currentLead.calls].reverse().map(call=>{const started=Date.parse(call.startedAt),ended=call.endedAt?Date.parse(call.endedAt):null;const seconds=ended!==null&&Number.isFinite(started)&&Number.isFinite(ended)&&ended>=started?Math.floor((ended-started)/1000):null;return <li key={call.id}><h3>{call.outcome==="follow_up"?"นัดติดตาม":call.outcome==="interested"?"สนใจต่อ":call.outcome==="not_interested"?"ไม่สนใจ":"กำลังคุย"}</h3><p className="broker-muted">เริ่ม {Number.isFinite(started)?<time dateTime={call.startedAt}>{new Date(started).toLocaleString("th-TH",{timeZone:"Asia/Bangkok"})}</time>:"ไม่ทราบเวลา"}</p>{call.endedAt&&<p className="broker-muted">จบ {ended!==null&&Number.isFinite(ended)?<time dateTime={call.endedAt}>{new Date(ended).toLocaleString("th-TH",{timeZone:"Asia/Bangkok"})}</time>:"ไม่ทราบเวลา"} · {seconds===null?"ไม่ทราบระยะเวลา":`${Math.floor(seconds/60)} นาที ${seconds%60} วินาที`}</p>}{call.note&&<p className="broker-message-content">{call.note}</p>}</li>;})}</ol>:<p className="broker-muted">ยังไม่ได้เริ่มการสนทนา</p>}</section>
   </aside></div>
  </div></main>;
}

function HistoricalCard({card,lead}:{card:ChatCard;lead:Lead}){
 if(card.type==="question")return <p className="mt-2 rounded-xl bg-[#f5f5f7] p-3">คำถามในการ์ด: {card.prompt}</p>;
 if(card.type==="term")return <p className="mt-2 rounded-xl bg-[#f5f5f7] p-3">คำศัพท์ที่เปิด: {Object.hasOwn(insuranceTerms,card.term)?insuranceTerms[card.term as keyof typeof insuranceTerms].title:card.term} <span className="text-[#6e6e73]">· ชื่อจากพจนานุกรมปัจจุบัน</span></p>;
 return <details className="mt-2 rounded-xl border border-[#e0e0e0] p-3"><summary className="min-h-11 cursor-pointer content-center font-medium">{card.type==="comparison"?"การ์ดเปรียบเทียบ":card.type==="handoff"?"การ์ดส่งต่อผู้เชี่ยวชาญ":"การ์ดข้อมูลแผน"} · ข้อมูล ณ ตอนส่ง</summary>{card.type==="handoff"&&<p className="mt-2">{card.reason}</p>}{card.planIds.map(id=>{
 const plan=lead.planFacts?.find(p=>p.id===id);
 if(!plan)return <p key={id} className="mt-3 text-[#6e6e73]">{id} · คำขอเก่าไม่มีข้อมูลแผนนี้ที่บันทึกไว้</p>;
 const fields="fieldKeys"in card?(card.fieldKeys.length?card.fieldKeys:Object.keys(plan.coverageCells??{})):[];
 return <article key={id} className="mt-3 border-t border-[#e0e0e0] pt-3"><h3 className="font-semibold">{plan.name}</h3><p>{plan.price?formatPrice(plan.price):formatPremium(plan.premiumTHB,plan.premiumPeriod,plan.premiumNote)}</p><dl>{fields.map(key=>{
 const cell=plan.coverageCells&&Object.hasOwn(plan.coverageCells,key)?plan.coverageCells[key]:undefined;
 return <div key={key} className="mt-3"><dt className="font-medium">{categoryFields[plan.category].find(f=>f.key===key)?.label??key}</dt><dd>{cell?formatCoverageCell(cell):"ไม่มีข้อมูลช่องนี้ ณ ตอนส่ง"}{cell?.sourceIds.map(sourceId=>{const source=plan.sources?.find(s=>s.id===sourceId);return source?<a key={sourceId} className="text-link block min-h-11 content-center" href={source.url} target="_blank" rel="noreferrer">{source.publisher} · {source.locator}</a>:null;})}</dd></div>;
 })}</dl></article>;
 })}</details>;
}
