"use client";
import { useEffect, useRef, useState } from "react";
import Link from "@/components/native-link";
import "@/components/home-content.css";

const guide="https://www.oic.or.th/web-upload/migrated/content/85388/insur2_0.pdf";
const learning=[
 ["เลือกเรื่องที่ห่วง","ความกังวล · สิทธิเดิม · งบที่ไหว",guide],
 ["เทียบความคุ้มครอง","วงเงิน · เบี้ย · ข้อยกเว้น",guide],
 ["เช็กผู้ขาย","ตรวจใบอนุญาต กรอกข้อมูลตามจริง","https://www.muangthai.co.th/th/health-insurance-journey"],
 ["อ่านก่อนจ่าย","ชื่อ · แผน · วันคุ้มครอง · ช่องทางชำระ",guide],
 ["เก็บกรมธรรม์","เก็บช่องทางเคลมและวันต่ออายุ","https://www.muangthai.co.th/th/service"],
];
const promotions=[
 {category:"เดินทาง",insurer:"MSIG ประกันภัย",title:"ประกันเดินทาง",offer:"สมัครกับเพื่อน",value:"20%",valueLabel:"ลดสูงสุด",image:"/images/products/travel-05.jpg",source:"https://www.msig-thai.com/th",demo:true,start:"",end:"",dates:"ตัวอย่างโปรโมชัน",copy:"ตัวอย่างข้อเสนอสำหรับสมัครประกันเดินทางกับเพื่อน",conditions:"ส่วนลด 20% เป็นตัวเลขจำลองเพื่อสาธิต ยังไม่ใช่ข้อเสนอที่ยืนยันจาก MSIG โปรดตรวจจำนวนผู้สมัคร แผนที่เข้าร่วม และเงื่อนไขกับบริษัทก่อนซื้อ"},
 {category:"สุขภาพ",insurer:"AXA ประกันภัย",title:"ประกันสุขภาพ",offer:"สมัครยกครอบครัว",value:"25%",valueLabel:"ลดสูงสุด",image:"/images/insurance-life-hero.png",source:"https://www.axa.co.th/th/personal/health-insurance",demo:true,start:"",end:"",dates:"ตัวอย่างโปรโมชัน",copy:"ตัวอย่างข้อเสนอสำหรับครอบครัวที่สมัครประกันสุขภาพพร้อมกัน",conditions:"ส่วนลด 25% เป็นตัวเลขจำลองเพื่อสาธิต ยังไม่ใช่ข้อเสนอที่ยืนยันจาก AXA การรับประกันและส่วนลดขึ้นกับแผน อายุ และเงื่อนไขบริษัท ต้องตรวจรายละเอียดก่อนซื้อ"},
 {category:"รถยนต์",insurer:"AXA ประกันภัย",title:"ประกันรถยนต์",value:"18%",valueLabel:"ลดสูงสุด",image:"https://images.prismic.io/thailandgi-ktaxa/addik51ZCF7ETAaY_approve_AXANOW_tc_1200x640_th3.png?auto=format,compress",source:"https://www.axa.co.th/th/promotion/axanow",start:"2026-03-26",end:"2026-12-31",dates:"26 มี.ค. – 31 ธ.ค. 2569",copy:"สำหรับรถส่วนบุคคล ซื้อออนไลน์ตามช่องทางและเงื่อนไขที่กำหนด",conditions:"โค้ด AXANOW: ชั้น 1 ซ่อมอู่ลด 15%; ชั้น 2+/3+ ซ่อมอู่ลด 18%; พ.ร.บ. ลด 10% ไม่รวมอากรและ VAT เฉพาะลูกค้าออนไลน์ครั้งแรก ผู้เคยซื้อช่องทางอื่นต้องผ่านเงื่อนไขไม่มีเคลม 12 เดือน ผ่อน 0% ขึ้นกับยอดเบี้ยและบัตรที่ร่วมรายการ ไม่ใช่ราคาเสนอเฉพาะรถของคุณ"},

 {category:"บ้าน",insurer:"MSIG ประกันภัย",title:"ประกันบ้าน",value:"15%",valueLabel:"ส่วนลด",image:"https://www.msig-thai.com/sites/msig_th_revamp/files/2026-08/15.png",source:"https://www.msig-thai.com/th/promotion/"+encodeURIComponent("กรอกโค้ด-home15- รับส่วนลด-15-สำหรับประกันภัยบ้านแทนรัก-รับ-starbucks-e-coupon-สูงสุด-600"),start:"2026-09-01",end:"2027-01-31",dates:"1 ก.ย. 2569 – 31 ม.ค. 2570",copy:"ประกันบ้านแทนรัก โค้ด Home15 พร้อม Starbucks e-Coupon ตามยอดเบี้ย",conditions:"คูปองขึ้นกับเบี้ยหลังส่วนลดต่อกรมธรรม์ ต้องตอบแบบสอบถามภายใน 90 วันหลังรับ SMS และใช้ได้เมื่อเริ่มคุ้มครอง ตารางเกณฑ์รางวัลสูงสุด 600 บาทในต้นทางพิมพ์ยอดไม่ชัดเจน จึงยังยืนยันยอดที่เข้าเกณฑ์นี้ไม่ได้ โปรดตรวจสิทธิ์กับบริษัท ไม่ใช่ผู้ซื้อทุกคนได้รับรางวัลสูงสุด"},
];
export default function Home(){
 const promotionRail=useRef<HTMLDivElement>(null);
 const scrollPromotions=(direction:number)=>{const rail=promotionRail.current;if(rail)rail.scrollBy({left:direction*((rail.firstElementChild?.getBoundingClientRect().width??300)+24),behavior:"auto"});};
 const [today,setToday]=useState<string|null>(null);
 useEffect(()=>{const update=()=>setToday(new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Bangkok",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date()));const initial=setTimeout(update,0),clock=setInterval(update,60_000);return()=>{clearTimeout(initial);clearInterval(clock);};},[]);
 const active=promotions.filter(p=>p.demo||(today&&p.start<=today&&today<=p.end));
 return <main className="home-page">
  <section className="draft-hero" aria-labelledby="hero-title"><img src="/images/insurance-life-hero.png" alt="ครอบครัวเดินเคียงกันในบ้านที่เปิดรับแสงธรรมชาติ" fetchPriority="high"/><h1 id="hero-title">เลือกประกันที่ใช่<br/><span>สำหรับคุณ</span></h1><Link href="/chat?start=1" className="hero-action">เริ่มค้นหาประกัน</Link></section>
  <section className="home-promotions" aria-labelledby="promotions-title"><div className="section-heading"><h2 id="promotions-title">โปรโมชัน</h2><p>สมัครด้วยกันก่อน แล้วเลือกโปรโมชันอื่นที่ใช่</p><div className="promotion-controls"><button type="button" aria-label="เลื่อนโปรโมชันไปทางซ้าย" aria-controls="promotion-rail" onClick={()=>scrollPromotions(-1)}>←</button><button type="button" aria-label="เลื่อนโปรโมชันไปทางขวา" aria-controls="promotion-rail" onClick={()=>scrollPromotions(1)}>→</button></div></div><div className="promotion-grid" id="promotion-rail" ref={promotionRail} role="region" aria-label="รายการโปรโมชัน เลื่อนซ้ายหรือขวาเพื่อดูเพิ่มเติม" tabIndex={0}>{active.map(p=><article className="promotion-card" key={p.source}><img className="promotion-image" src={p.image} alt={p.demo?`ภาพประกอบ ${p.title}`:`ภาพโปรโมชันทางการ ${p.insurer}: ${p.title}`} loading="lazy"/><div className="promotion-body"><p className="promotion-kind">{p.demo?"ประกันกลุ่ม · สมัครด้วยกัน":`ประกัน${p.category}`}</p><p>{p.insurer}</p><h3>{p.title}</h3>{p.offer&&<p className="promotion-offer">{p.offer}</p>}{p.demo&&<span className="promotion-demo">ตัวอย่างโปรโมชัน</span>}<p className="promotion-value-label">{p.valueLabel}</p><p className="promotion-value">{p.value}</p>{!p.demo&&<p className="promotion-dates">{p.dates}</p>}<details className="promotion-conditions"><summary>ดูเงื่อนไข<span className="sr-only">: {p.title}</span></summary><p>{p.copy}</p><p>{p.conditions}</p><a className="text-link" href={p.source} target="_blank" rel="noopener noreferrer">{p.demo?"ข้อมูลประกันจากบริษัท":"รายละเอียดจากบริษัท"} ↗</a></details></div></article>)}</div>{today&&active.length===0&&<p>ยังไม่มีโปรโมชัน</p>}<p className="home-promotion-note">เลื่อนซ้าย–ขวาเพื่อดูเพิ่มเติม · การ์ดที่ระบุ “ตัวอย่างโปรโมชัน” ใช้ตัวเลขจำลอง ไม่ใช่ส่วนลดที่ยืนยันจากบริษัท · สิทธิ์จริงเป็นไปตามเงื่อนไขบริษัท</p></section>
  <section className="home-learning purchase-guide" aria-labelledby="learning-title"><div className="section-heading"><h2 id="learning-title">ก่อนซื้อประกัน</h2><p className="learning-intro">5 เรื่องที่ควรรู้</p></div><ol className="purchase-steps">{learning.map(([title,copy],i)=><li key={title}><span className="purchase-number" aria-hidden="true">0{i+1}</span><div><h3>{title}</h3><p>{copy}</p></div></li>)}</ol><details className="home-guide-reference"><summary>อ่านเพิ่มเติม</summary><ul>{[...new Set(learning.map(item=>item[2]))].map((source,index)=><li key={source}><a href={source} target="_blank" rel="noopener noreferrer">{["คู่มือเลือกประกัน","เตรียมตัวก่อนซื้อ","การดูแลกรมธรรม์"][index]} ↗</a></li>)}</ul></details><Link href="/browse" className="text-link">ดูประกันทั้งหมด ›</Link></section>
  <footer className="site-footer"><span>Insurance · เว็บไซต์สาธิต</span><Link href="/broker">สำหรับผู้เชี่ยวชาญ ›</Link></footer>
 </main>;
}
