"use client";
import { useEffect, useState } from "react";
import Link from "@/components/native-link";
import "@/components/home-content.css";

const guide="https://www.oic.or.th/web-upload/migrated/content/85388/insur2_0.pdf";
const learning=[
 ["เริ่มจากสิ่งที่อยากดูแล","ดูความคุ้มครองที่มีอยู่ แล้วเลือกเรื่องที่ยังกังวล พร้อมงบที่จ่ายต่อไหว",guide],
 ["เทียบให้ครบ ก่อนดูแค่ราคา","ดูเบี้ยที่ต้องจ่าย วงเงิน เงื่อนไข และสิ่งที่ไม่คุ้มครอง เทียบแผนประเภทเดียวกัน",guide],
 ["เช็กคนขาย กรอกข้อมูลตามจริง","ตรวจใบอนุญาตตัวแทนหรือนายหน้า และตอบข้อมูลในใบสมัครให้ครบตามจริง","https://www.muangthai.co.th/th/health-insurance-journey"],
 ["อ่านสัญญา ก่อนยืนยันจ่าย","เช็กชื่อ แผน วันเริ่มคุ้มครอง และเงื่อนไข จ่ายผ่านช่องทางที่บริษัทรับรอง พร้อมเก็บใบเสร็จ",guide],
 ["เก็บไว้ให้หาเจอ เมื่อถึงเวลาใช้","เก็บกรมธรรม์ ช่องทางแจ้งเคลม และวันครบกำหนด ทบทวนความคุ้มครองก่อนต่ออายุ","https://www.muangthai.co.th/th/service"],
];
const promotions=[
 {category:"รถยนต์",insurer:"AXA ประกันภัย",title:"AXANOW ลดเบี้ยสูงสุด 18%",image:"https://images.prismic.io/thailandgi-ktaxa/addik51ZCF7ETAaY_approve_AXANOW_tc_1200x640_th3.png?auto=format,compress",source:"https://www.axa.co.th/th/promotion/axanow",start:"2026-03-26",end:"2026-12-31",dates:"26 มี.ค. – 31 ธ.ค. 2569",copy:"สำหรับรถส่วนบุคคล ซื้อออนไลน์ตามช่องทางและเงื่อนไขที่กำหนด",conditions:"โค้ด AXANOW: ชั้น 1 ซ่อมอู่ลด 15%; ชั้น 2+/3+ ซ่อมอู่ลด 18%; พ.ร.บ. ลด 10% ไม่รวมอากรและ VAT เฉพาะลูกค้าออนไลน์ครั้งแรก ผู้เคยซื้อช่องทางอื่นต้องผ่านเงื่อนไขไม่มีเคลม 12 เดือน ผ่อน 0% ขึ้นกับยอดเบี้ยและบัตรที่ร่วมรายการ ไม่ใช่ราคาเสนอเฉพาะรถของคุณ"},
 {category:"เดินทาง",insurer:"MSIG ประกันภัย",title:"เที่ยวต่างประเทศ รับสิทธิ์ตามยอดเบี้ย",image:"https://www.msig-thai.com/sites/msig_th_revamp/files/2026-07/15STB_0.png",source:"https://www.msig-thai.com/th/promotion/enter-promocode-15stb-or-15ptt-get-e-coupone-voucher-worth-1000-thb-msig-travel-easy-plus",start:"2026-08-01",end:"2026-09-30",dates:"1 ส.ค. – 30 ก.ย. 2569",copy:"Travel Easy Plus รายเที่ยวหรือรายปี โค้ด 15STB หรือ 15PTT ลด 15% พร้อมของรางวัลตามเงื่อนไข",conditions:"คูปองขึ้นกับเบี้ยหลังส่วนลดต่อคน ต้องสมัคร MSIG Privilege และตอบแบบสอบถามภายใน 90 วันหลังรับ SMS ใช้ได้เมื่อกรมธรรม์เริ่มคุ้มครอง ตารางต้นทางระบุรางวัลสูงสุดที่ยอดมากกว่า 6,000 บาท แต่ยอดเท่ากับ 6,000 บาทยังไม่ชัดเจน ให้ยืนยันกับบริษัท ยกเลิกกรมธรรม์อาจถูกเรียกคืนรางวัล"},
 {category:"บ้าน",insurer:"MSIG ประกันภัย",title:"ดูแลบ้าน พร้อมส่วนลด 15%",image:"https://www.msig-thai.com/sites/msig_th_revamp/files/2026-08/15.png",source:"https://www.msig-thai.com/th/promotion/"+encodeURIComponent("กรอกโค้ด-home15- รับส่วนลด-15-สำหรับประกันภัยบ้านแทนรัก-รับ-starbucks-e-coupon-สูงสุด-600"),start:"2026-09-01",end:"2027-01-31",dates:"1 ก.ย. 2569 – 31 ม.ค. 2570",copy:"ประกันบ้านแทนรัก โค้ด Home15 พร้อม Starbucks e-Coupon ตามยอดเบี้ย",conditions:"คูปองขึ้นกับเบี้ยหลังส่วนลดต่อกรมธรรม์ ต้องตอบแบบสอบถามภายใน 90 วันหลังรับ SMS และใช้ได้เมื่อเริ่มคุ้มครอง ตารางเกณฑ์รางวัลสูงสุด 600 บาทในต้นทางพิมพ์ยอดไม่ชัดเจน จึงยังยืนยันยอดที่เข้าเกณฑ์นี้ไม่ได้ โปรดตรวจสิทธิ์กับบริษัท ไม่ใช่ผู้ซื้อทุกคนได้รับรางวัลสูงสุด"},
];
export default function Home(){
 const [today,setToday]=useState<string|null>(null);
 useEffect(()=>{const update=()=>setToday(new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Bangkok",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date()));const initial=setTimeout(update,0),clock=setInterval(update,60_000);return()=>{clearTimeout(initial);clearInterval(clock);};},[]);
 const active=today?promotions.filter(p=>p.start<=today&&today<=p.end):[];
 return <main className="home-page">
  <section className="draft-hero" aria-labelledby="hero-title"><img src="/images/insurance-hero.png" alt="เอกสารประกันและแล็ปท็อปบนโต๊ะทำงาน" fetchPriority="high"/><h1 id="hero-title">เลือกประกันที่ใช่<br/><span>สำหรับคุณ</span></h1><Link href="/chat?start=1" className="hero-action">เริ่มค้นหาประกันเลย!</Link></section>
  <section className="home-promotions" aria-labelledby="promotions-title"><div className="section-heading"><h2 id="promotions-title">โปรโมชันจากบริษัทประกัน</h2><p>ดูสิทธิ์ที่ตรงกับคุณ พร้อมเงื่อนไขจากเจ้าของโปรโมชัน</p></div><div className="promotion-grid">{active.map(p=><article className="promotion-card" key={p.source}><img className="promotion-image" src={p.image} alt={`ภาพโปรโมชันทางการ ${p.insurer}: ${p.title}`} loading="lazy"/><div className="promotion-body"><p>{p.insurer}</p><h3>{p.title}</h3><p className="promotion-dates">{p.dates}</p><p>{p.copy}</p><details className="promotion-conditions"><summary>เงื่อนไขสำคัญ<span className="sr-only">: {p.title}</span></summary><p>{p.conditions}</p></details><a className="text-link" href={p.source} target="_blank" rel="noopener noreferrer">ดูโปรโมชันที่บริษัทประกัน ↗</a></div></article>)}</div>{today&&active.length===0&&<p>ยังไม่มีโปรโมชันที่ยืนยันช่วงเวลาได้ในขณะนี้</p>}<p className="home-promotion-note">ตรวจข้อมูลจากเว็บไซต์บริษัทเมื่อ 12 กันยายน 2569 · สิทธิ์ขึ้นกับช่องทางซื้อและเงื่อนไขบริษัท เว็บไซต์นี้เป็นเดโม ไม่รับชำระเงินหรือรับสิทธิ์โปรโมชัน</p></section>
  <section className="home-learning purchase-guide" aria-labelledby="learning-title"><div className="section-heading"><h2 id="learning-title">ซื้อประกัน เริ่มยังไงดี?</h2><p className="learning-intro">ค่อย ๆ เลือกให้เข้าใจ ตั้งแต่ก่อนซื้อจนถึงวันที่ต้องใช้</p></div><ol className="purchase-steps">{learning.map(([title,copy,source],i)=><li key={title}><span className="purchase-number" aria-hidden="true">0{i+1}</span><div><h3>{title}</h3><p>{copy}</p><a href={source} target="_blank" rel="noopener noreferrer" className="text-link" aria-label={`อ่านแหล่งข้อมูล: ${title} (เปิดแท็บใหม่)`}>อ่านเพิ่ม ↗</a></div></li>)}</ol><Link href="/browse" className="text-link">ลองเลือกประกันที่สนใจ ›</Link></section>
  <footer className="site-footer"><span>Insurance · เว็บไซต์สาธิต ไม่มีการซื้อหรือออกกรมธรรม์จริง</span><Link href="/broker">สำหรับผู้เชี่ยวชาญ ›</Link></footer>
 </main>;
}
