"use client";
import { useState } from "react";
import { categoryFields, getPlan } from "@/lib/catalog";
import { buildComparison } from "@/lib/compare";
import { formatCoverageCell } from "@/lib/display";
import { insuranceTerms, type InsuranceTermKey } from "@/lib/insurance-terms";
import { categories, type Category, type ChatCard, type CoverageCell, type Plan } from "@/lib/types";
import { PlanPrice } from "./plan-price";
import { TermHelp } from "./term-help";

export const categoryLabels:Record<Category,string>={health:"สุขภาพ",motor:"รถยนต์",life:"ชีวิต",accident:"อุบัติเหตุ",travel:"เดินทาง",property:"ทรัพย์สิน",liability:"ความรับผิด"};
export type CardAction=(intent:"select"|"interest"|"handoff"|"compare",ids:string[])=>string|void;
type Props={card:ChatCard;selection:string[];disabled:boolean;current:boolean;onAction:CardAction;onCategory:(category:Category)=>void;onBudget:(budget:number,category:Category|null)=>void};
const featured:Partial<Record<Category,string[]>>={motor:["class","ownDamageLimit","thirdPartyProperty","thirdPartyBodilyPerPerson","deductible","repairType"],health:["annualLimit","perDiseaseLimit","roomPerDay","opdPerYear","deductible","copay"]};
function fieldsFor(plan:Plan,keys:string[]){const fields=categoryFields[plan.category];return (keys.length?keys:featured[plan.category]??fields.slice(0,6).map(f=>f.key)).map(key=>fields.find(f=>f.key===key)).filter(f=>f!==undefined).slice(0,8);}
function Fact({cell,plan}:{cell:CoverageCell;plan:Plan}){const sources=plan.sources.filter(source=>cell.sourceIds.includes(source.id));return <><span>{formatCoverageCell({...cell,conditions:[]})}</span>{(cell.conditions.length>0||sources.length>0)&&<details className="chat-fact-details"><summary>เงื่อนไขและที่มา</summary>{cell.conditions.map((condition,i)=><p key={i}>{condition}</p>)}{sources.map(source=><a key={source.id} href={source.url} target="_blank" rel="noreferrer">{source.publisher} · {source.locator} ↗</a>)}</details>}</>;}
export function ChatCardView({card,selection,disabled,current,onAction,onCategory,onBudget}:Props){
 const [error,setError]=useState(""),[budget,setBudget]=useState("");
 const act:CardAction=(intent,ids)=>setError(onAction(intent,ids)||"");
 const feedback=error?<p className="chat-card-error" role="alert">{error}</p>:null;
 if(card.type==="term"){
  const term=insuranceTerms[card.term as InsuranceTermKey];if(!term)return null;
  return <section className="chat-result-card chat-term-card"><p className="chat-card-eyebrow">เข้าใจในหนึ่งนาที</p><h3>{term.title}</h3><p>{term.description}</p><p className="chat-card-caution">{term.caution}</p><a className="text-link" href={term.source} target="_blank" rel="noreferrer">อ่านแหล่งอ้างอิง ↗</a></section>;
 }
 if(card.type==="question")return <section className="chat-result-card chat-question-card"><h3>{card.prompt}</h3>{card.kind==="category"?<div className="chat-choice-grid" role="group" aria-label="เลือกหมวดเพื่อเริ่มคุย">{categories.map(category=><button className="action-secondary" key={category} disabled={disabled||!current} onClick={()=>onCategory(category)}>{categoryLabels[category]}</button>)}</div>:<><p className="chat-card-caution">งบอ้างอิง{card.category?`สำหรับประกัน${categoryLabels[card.category]}`:""} · ตรวจรอบเบี้ยของแต่ละแผน</p><form className="chat-budget-form" onSubmit={event=>{event.preventDefault();const amount=Number(budget);if(!budget.trim()||!Number.isFinite(amount)||amount<0||amount>100000000||Math.abs(amount*100-Math.round(amount*100))>1e-6){setError("กรอกงบ 0–100,000,000 บาท ทศนิยมไม่เกิน 2 ตำแหน่ง");return;}setError("");onBudget(amount,card.category);}}><label>งบประมาณ (บาท)<input className="field" inputMode="decimal" value={budget} onChange={e=>setBudget(e.target.value)} disabled={disabled||!current} placeholder="ระบุงบที่สะดวก" maxLength={14} aria-invalid={!!error}/></label><button className="action-primary" disabled={disabled||!current||!budget.trim()}>ใช้งบนี้</button></form></>}{!current&&<p className="chat-card-caution">ตอบคำถามล่าสุดด้านล่าง หรือพิมพ์เปลี่ยนความต้องการได้</p>}{feedback}</section>;
 const plans=card.planIds.map(getPlan).filter(plan=>plan!==undefined);if(plans.length!==card.planIds.length)return <p className="chat-card-caution">ข้อมูลแผนนี้เปลี่ยนแล้ว กรุณาถามผู้ช่วยอีกครั้ง</p>;
 if(card.type==="handoff")return <section className="chat-result-card"><p className="chat-card-eyebrow">ขั้นตอนถัดไป · เลือกได้</p><h3>ให้ผู้เชี่ยวชาญช่วยดูต่อ</h3><p>{card.reason}</p><ul className="chat-handoff-plans">{plans.map(p=><li key={p.id}>{p.name}</li>)}</ul><button className="action-primary" disabled={disabled||!current} onClick={()=>act("handoff",card.planIds)}>ดูสรุปก่อนส่ง</button><p className="chat-card-caution">คุณตรวจ แก้ และยืนยัน consent ก่อนส่งคำขอเดโม</p>{feedback}</section>;
 if(card.type==="comparison"){
  let comparison;try{comparison=buildComparison(card.category,card.planIds);}catch{return <p className="chat-card-error">ชุดนี้เปรียบเทียบร่วมกันไม่ได้ กรุณาเลือกแผนใหม่</p>;}
  const fields=fieldsFor(plans[0],card.fieldKeys),rows=comparison.rows.filter(row=>fields.some(f=>f.key===row.key));
  return <section className="chat-result-card chat-comparison-card"><p className="chat-card-eyebrow">เทียบประกัน{categoryLabels[card.category]} · {plans.length} แผน</p><h3>เห็นความต่างในที่เดียว</h3><div className="chat-table-scroll" role="region" aria-label="ตารางเปรียบเทียบในแชต" tabIndex={0}><table><thead><tr><th scope="col">สิ่งที่เทียบ</th>{plans.map(p=><th scope="col" key={p.id}><small>{p.insurer}</small>{p.name}</th>)}</tr></thead><tbody><tr><th scope="row">เบี้ยประกัน<TermHelp fieldKey="premiumTHB"/></th>{plans.map(p=><td key={p.id}><PlanPrice price={p.price} className="chat-price"/></td>)}</tr>{rows.map(row=><tr key={row.key}><th scope="row">{row.label}<TermHelp fieldKey={row.key}/><small>{row.comparisonStatus==="not_comparable"?"ฐานต่างกัน":row.comparisonStatus==="insufficient"?"ข้อมูลยังไม่พอ":row.comparisonStatus==="same"?"เหมือนกัน":"ต่างกัน"}</small></th>{row.cells.map((cell,i)=><td key={plans[i].id}><Fact cell={cell} plan={plans[i]}/></td>)}</tr>)}<tr><th scope="row">เลือกดูต่อ</th>{plans.map(p=><td key={p.id}><button className="action-secondary" disabled={disabled} onClick={()=>act("interest",[p.id])}>สนใจแผนนี้<span className="sr-only"> {p.name}</span></button></td>)}</tr></tbody></table></div><a className="text-link" href={comparison.url}>เปิดตารางเต็มทุกหัวข้อ ›</a>{feedback}</section>;
 }
 return <section className="chat-result-card chat-plans-card" aria-label="รายละเอียดแผนในแชต">{plans.map(plan=><article key={plan.id}><header><p className="chat-card-eyebrow">{plan.insurer} · ประกัน{categoryLabels[plan.category]}</p><h3>{plan.name}</h3><PlanPrice price={plan.price} className="chat-price"/></header><dl>{fieldsFor(plan,card.fieldKeys).map(field=><div key={field.key}><dt>{field.label}<TermHelp fieldKey={field.key}/></dt><dd><Fact cell={plan.coverageCells[field.key]} plan={plan}/></dd></div>)}</dl><div className="chat-plan-actions"><label><input type="checkbox" checked={selection.includes(plan.id)} disabled={disabled} onChange={()=>act("select",[plan.id])}/>เลือกเพื่อเทียบ</label><button className="action-primary" disabled={disabled} onClick={()=>act("interest",[plan.id])}>สนใจแผนนี้<span className="sr-only"> {plan.name}</span></button><a className="text-link" href={`/plans/${plan.id}`}>รายละเอียดทั้งหมด ›</a></div></article>)}{selection.length>=2&&<button className="action-secondary chat-compare-selected" disabled={disabled} onClick={()=>act("compare",selection)}>ให้ผู้ช่วยเทียบ {selection.length} แผนที่เลือก</button>}{feedback}</section>;
}
