"use client";

import { createContext, useContext, useEffect, useMemo, useRef, useState } from "react";
import { initialDemoState, readDemoStorage, writeDemoStorage, clearDemoStorage, type DemoState } from "@/lib/demo-state";
import type { CustomerProfile, CustomerSummary, Lead } from "@/lib/types";
import { arePlansCompatible } from "@/lib/compare";
import { getPlan } from "@/lib/catalog";
import type { DemoSignals } from "@/lib/demo-state";

const DemoContext = createContext<{ state: DemoState; setProfile: (profile: CustomerProfile) => void; setSelection: (ids: string[]) => void; setInterestedPlans: (ids: string[]) => void; recordComparison: (ids: string[]) => void; appendMessages: (messages: DemoState["messages"]) => void; saveSummary: (summary: CustomerSummary) => void; addLead: (lead: Lead) => void; updateLead: (lead: Lead) => void; recordSignal: (signal: keyof DemoSignals) => void; markOfferSeen: () => void; reset: () => boolean; storageWarning: boolean; ready: boolean }>({ state: initialDemoState(), setProfile: () => undefined, setSelection: () => undefined, setInterestedPlans: () => undefined, recordComparison: () => undefined, appendMessages: () => undefined, saveSummary: () => undefined, addLead: () => undefined, updateLead: () => undefined, recordSignal: () => undefined, markOfferSeen: () => undefined, reset: () => false, storageWarning: false, ready: false });

export function DemoProvider({ children }: { children: React.ReactNode }) {
  const [state, setState] = useState<DemoState>(initialDemoState);
  const [storageWarning, setStorageWarning] = useState(false);
  const hydrated = useRef(false), canPersist = useRef(true);
  const [resetNotice,setResetNotice]=useState(false);
  const [ready, setReady] = useState(false);
  useEffect(() => { const timer=window.setTimeout(() => {
    try { const restored=readDemoStorage(window.localStorage);setState(restored.state);setStorageWarning(restored.warning); } catch {setStorageWarning(true);canPersist.current=false;}
    const url=new URL(window.location.href);if(url.searchParams.get("reset")==="1"){setResetNotice(true);url.searchParams.delete("reset");window.history.replaceState(window.history.state,"",url);}
    hydrated.current=true;setReady(true);
  },0);return()=>clearTimeout(timer); },[]);
  useEffect(() => { if(!hydrated.current||!canPersist.current)return;let saved=false;try{saved=writeDemoStorage(window.localStorage,state);}catch{}if(!saved){canPersist.current=false;const timer=window.setTimeout(()=>setStorageWarning(true),0);return()=>clearTimeout(timer);} },[state]);
  const value = useMemo(() => ({ state, storageWarning, ready, setProfile: (profile: CustomerProfile) => setState((s) => ({ ...s, profile, interestedPlanIds: s.interestedPlanIds.filter(id=>getPlan(id)?.category===profile.preferredCategory), signals: { ...s.signals, budgetSet: profile.budgetTHB !== null } })), setSelection: (ids: string[]) => setState(s=>{const plans=ids.map(getPlan);if(ids.length>3||new Set(ids).size!==ids.length||plans.some(p=>!p)||!arePlansCompatible(plans.filter(p=>p!==undefined)))return s;return {...s,profile:{...s.profile,preferredCategory:plans[0]?.category??s.profile.preferredCategory},selection:[...ids]};}), setInterestedPlans: (ids: string[]) => setState(s => { const plans=ids.map(getPlan); if(ids.length>3||new Set(ids).size!==ids.length||plans.some(p=>!p)||!arePlansCompatible(plans.filter(p=>p!==undefined)))return s; return {...s, interestedPlanIds:[...ids], profile:{...s.profile,preferredCategory:plans[0]?.category??s.profile.preferredCategory}, signals:{...s.signals,interested:ids.length>0}}; }), recordComparison: (ids: string[]) => setState(s => ({...s,comparedPlanIds:[...ids],selection:[...ids],interestedPlanIds:s.interestedPlanIds.filter(id=>getPlan(id)?.category===getPlan(ids[0])?.category),profile:{...s.profile,preferredCategory:getPlan(ids[0])?.category??s.profile.preferredCategory},signals:{...s.signals,compareCompleted:true}})), appendMessages: (messages: DemoState["messages"]) => setState((s) => ({ ...s, messages: [...s.messages, ...messages].slice(-12) })), saveSummary: (summary: CustomerSummary) => setState((s) => ({ ...s, summary })), addLead: (lead: Lead) => setState((s) => s.leads.some((item) => ["new", "contacting", "follow_up"].includes(item.status) && item.customerId === lead.customerId && item.summary.category === lead.summary.category) ? s : { ...s, leads: [...s.leads, lead], signals: { ...s.signals, interested: true } }), updateLead: (lead: Lead) => setState((s) => ({ ...s, leads: s.leads.map((item) => item.id === lead.id ? lead : item) })), recordSignal: (signal: keyof DemoSignals) => setState((s) => ({ ...s, signals: { ...s.signals, [signal]: true } })), markOfferSeen: () => setState((s) => ({ ...s, offerSeen: true })), reset: () => { let cleared=false;try{cleared=clearDemoStorage(window.localStorage);}catch{}setStorageWarning(!cleared);canPersist.current=cleared;setState(initialDemoState());return cleared; } }), [state, storageWarning, ready]);
  return <DemoContext.Provider value={value}>{ready ? <>{resetNotice&&<div className="flex items-center justify-between gap-3 bg-[#eef6ff] px-5 text-sm" role="status"><p>รีเซ็ตข้อมูลเดโมแล้ว</p><button className="min-h-11 min-w-11" aria-label="ปิดข้อความรีเซ็ต" onClick={()=>setResetNotice(false)}>ปิด</button></div>}{storageWarning&&<p role="status" className="bg-amber-50 px-5 py-3 text-sm text-amber-900">บันทึกข้อมูลใน browser ไม่ได้ ข้อมูลรอบนี้อาจหายเมื่อโหลดหน้าใหม่</p>}{children}</> : <p className="p-8 text-sm text-[#6e6e73]" role="status">กำลังโหลดข้อมูลเดโม…</p>}</DemoContext.Provider>;
}
export function useDemo() { return useContext(DemoContext); }
