import type { Category, CoverageCell, Field, Plan, SourceEvidence } from "./types.ts";

const fields = (...items: [string, string][]): Field[] => items.map(([key, label]) => ({ key, label, unit: null }));
export const additionalCategoryFields = {
  pet: fields(["petType", "สัตว์ที่รับประกัน"], ["treatmentScope", "การรักษาที่มีให้เลือก"], ["petLiability", "ความรับผิดต่อบุคคลอื่น"], ["benefitLimit", "วงเงินและตัวเลือกแผน"], ["waitingPeriod", "ระยะรอคอย"], ["petEligibility", "อายุและคุณสมบัติสัตว์เลี้ยง"]),
  "critical-illness": fields(["coveredConditions", "โรคและระยะที่มีความคุ้มครอง"], ["benefitType", "รูปแบบผลประโยชน์"], ["benefitLimit", "ทุนหรือวงเงินที่เลือก"], ["waitingPeriod", "ระยะรอคอย"], ["basePolicy", "การพ่วงสัญญาชีวิตหลัก"], ["eligibilityConditions", "เงื่อนไขการสมัคร"]),
  cyber: fields(["coveredActivity", "ผู้ใช้และความเสี่ยงที่คุ้มครอง"], ["responseCosts", "ค่าใช้จ่ายจัดการเหตุ"], ["businessInterruption", "ธุรกิจหยุดชะงัก"], ["thirdPartyLiability", "ความรับผิดจากข้อมูล"], ["benefitLimit", "วงเงินที่เลือก"], ["deductible", "ค่าเสียหายส่วนแรก"]),
  business: fields(["businessType", "ประเภทความเสี่ยงธุรกิจ"], ["coveredActivity", "งานหรือทรัพย์สินที่คุ้มครอง"], ["benefitLimit", "วงเงินหรือทุนประกัน"], ["thirdPartyLiability", "ความรับผิดบุคคลภายนอก"], ["territory", "พื้นที่และระยะเวลา"], ["deductible", "ค่าเสียหายส่วนแรก"]),
  event: fields(["eventType", "ประเภทงานที่ต้องพิจารณา"], ["cancellationScope", "การยกเลิกหรือเลื่อนงาน"], ["lossOfProfit", "กำไรที่ลดลง"], ["weddingEligibility", "การรับประกันงานแต่งงาน"], ["benefitLimit", "วงเงินและค่าใช้จ่ายที่แจ้ง"], ["deductible", "ค่าเสียหายส่วนแรก"]),
  sports: fields(["sportType", "กีฬาที่คุ้มครอง"], ["accidentScope", "อุบัติเหตุผู้เล่น"], ["equipmentScope", "อุปกรณ์กีฬา"], ["thirdPartyLiability", "ความรับผิดจากการเล่น"], ["territory", "พื้นที่การเล่น"], ["benefitLimit", "วงเงินและตัวเลือกแผน"], ["golfDeathBenefit", "เสียชีวิตจากอุบัติเหตุกอล์ฟ"], ["golfMedicalPerAccident", "ค่ารักษาจากอุบัติเหตุกอล์ฟ"], ["golfLiabilityPerOccurrence", "ความรับผิดบุคคลอื่นต่อเหตุ"], ["golfEquipmentPerOccurrence", "อุปกรณ์กอล์ฟต่อเหตุ"], ["golfEquipmentAggregate", "อุปกรณ์กอล์ฟรวมตลอดกรมธรรม์"]),
} satisfies Partial<Record<Category, Field[]>>;

type ProductRecord = {
  id: string; category: Category; group?: string; name: string; insurer: string; url: string;
  facts: Record<string, string>; note?: string; locator?: string;
  fieldConditions?: Record<string, string[]>;
  period?: Plan["premiumPeriod"];
  publishedPrice?: Plan["price"];
  priceEvidence?: SourceEvidence;
};
const bkiBusiness = "https://www.bangkokinsurance.com/th/product/business";
const bkiHome = "https://www.bangkokinsurance.com/product/residential";
const msig = "https://www.msig-thai.com/th/business-insurance/";

// One entry per distinct product, not one entry per advertised tier, age or sales channel.
// These are product overviews awaiting a selected plan and quote; no maxima become personal limits.
export const catalogExpansionRecords: ProductRecord[] = [
  {"id": "event-02", "category": "event", "group": "cancellation", "name": "Chubb ประกันคุ้มครองอีเวนต์", "insurer": "ชับบ์ (Chubb)", "url": "https://www.chubb.com/th-th/business/event-insurance.html", "locator": "ลักษณะเด่นของผลิตภัณฑ์ / อีเวนต์ใดบ้างที่เราประกันภัยคุ้มครอง / โซลูชันของชับบ์", "facts": {"eventType": "งานแต่งงาน งานปาร์ตี้ คอนเสิร์ต การประชุม นิทรรศการ และงานกีฬา ตามการพิจารณารับประกัน", "cancellationScope": "มีความคุ้มครองการยกเลิก ทิ้งงาน หยุดชะงัก เลื่อน หรือย้ายสถานที่จากเหตุที่เข้าเงื่อนไข", "weddingEligibility": "เว็บไซต์ระบุงานแต่งงานในประเภทอีเวนต์ที่รับพิจารณาประกันภัย ต้องยืนยันรายละเอียดงานและความคุ้มครองที่เสนอ"}, "note": "ต้องระบุประเภทงาน วัน สถานที่ รายได้และค่าใช้จ่ายเพื่อขอใบเสนอราคา; ไม่รับรองว่าการเปลี่ยนใจแต่งงานหรือการยกเลิกทุกสาเหตุคุ้มครอง"},
  { id: "pet-01", category: "pet", name: "เมืองไทย Pet Chill", insurer: "เมืองไทยประกันภัย", url: "https://www.muangthaiinsurance.com/th/product/miscellaneous-insurance/pet-chill-insurance", facts: { petType: "สุนัขและแมว", treatmentScope: "มีแผนอุบัติเหตุ และแผนที่เพิ่มการเจ็บป่วยตามตารางตัวเลือก" }, note: "แผน 1 ไม่คุ้มครองการเจ็บป่วย; วัคซีนมีเฉพาะแผน 4–6 ต้องเลือกแผนก่อนยืนยันวงเงิน", locator: "ตารางความคุ้มครองแผน 1–6" },
  { id: "pet-02", category: "pet", name: "Falcon Paw Sure", insurer: "ฟอลคอนประกันภัย", url: "https://falconinsurance.co.th/miscellaneous/paw-sure", facts: { petType: "สุนัขและแมว", treatmentScope: "อุบัติเหตุและการเจ็บป่วยตามแผน", petLiability: "มีความรับผิดต่อบุคคลภายนอกตามแผน", waitingPeriod: "การเจ็บป่วยรอ 60 วันในการเริ่มคุ้มครองครั้งแรก", petEligibility: "อายุ 3 เดือน–7 ปี; ใบรับรองตรวจสุขภาพไม่เกิน 60 วัน" }, note: "วงเงินโฆษณาสูงสุดไม่ใช่วงเงินที่ได้ทุกแผน" },
  { id: "pet-03", category: "pet", name: "Falcon Pet Protect Sure", insurer: "ฟอลคอนประกันภัย", url: "https://falconinsurance.co.th/miscellaneous/pet-protect-sure", facts: { petType: "สุนัขและแมว", treatmentScope: "มีตัวเลือกอุบัติเหตุ เจ็บป่วย รวมการรักษาเห็บ หมัด และโรคผิวหนัง", petLiability: "มีความคุ้มครองชีวิตและทรัพย์สินบุคคลอื่นตามแผน", waitingPeriod: "การเจ็บป่วยรอ 60 วันในการเริ่มคุ้มครองครั้งแรก" }, note: "ตัวเลือกแผนและวงเงินต้องตรวจตารางก่อนขอราคา" },
  { id: "critical-illness-01", category: "critical-illness", group: "cancer", name: "AXA SmartCare Cancer", insurer: "AXA ประกันภัย", url: "https://www.axa.co.th/th/personal/health-insurance/cancer", facts: { coveredConditions: "ประกันเฉพาะโรคมะเร็งตามคำนิยามกรมธรรม์", benefitType: "ผลประโยชน์แบบเงินก้อนเมื่อตรวจพบมะเร็งเข้าเงื่อนไข" } },
  { id: "critical-illness-02", category: "critical-illness", group: "cancer", name: "MSIG Cancer Fix", insurer: "MSIG ประกันภัย", url: "https://www.msig-thai.com/th/personal-insurance/cancer-fix", facts: { coveredConditions: "มะเร็งตามคำนิยามของแผน", benefitType: "เงินก้อน พร้อมผลประโยชน์การรักษามะเร็งตามตารางแผน" }, note: "เงินก้อนและค่ารักษาไม่ใช่วงเงินเดียวกัน ต้องตรวจแผนที่เลือก" },
  { id: "critical-illness-03", category: "critical-illness", group: "cancer", name: "กรุงเทพประกันภัย โรคมะเร็ง", insurer: "กรุงเทพประกันภัย", url: "https://www.bangkokinsurance.com/th/product/health/cancer/faq-cancer", facts: { coveredConditions: "การวินิจฉัยมะเร็งตามกรมธรรม์", benefitType: "จ่ายผลประโยชน์ตามทุนที่ซื้อ แล้วความคุ้มครองสิ้นสุดตามเงื่อนไข" }, note: "ต้องตอบคำถามสุขภาพและยืนยันคุณสมบัติก่อนรับประกัน" },
  { id: "critical-illness-04", category: "critical-illness", group: "cancer", name: "รู้ใจ ประกันมะเร็ง", insurer: "รู้ใจประกันภัย", url: "https://www.roojai.com/cancer/", facts: { coveredConditions: "มะเร็งทุกชนิดทุกระยะตามคำนิยามและข้อยกเว้น", benefitType: "เงินก้อนเมื่อได้รับการวินิจฉัยที่เข้าเงื่อนไข" }, note: "ไม่รวมโรคที่เป็นมาก่อนและเหตุในระยะรอคอย; ไม่แปลงเบี้ยโฆษณารายวันเป็นเบี้ยรายปี" },
  { id: "critical-illness-05", category: "critical-illness", group: "multi-disease", name: "รู้ใจ ประกันโรคร้ายแรง", insurer: "รู้ใจประกันภัย", url: "https://www.roojai.com/critical-illness/", facts: { coveredConditions: "เลือกความคุ้มครองกลุ่มมะเร็ง ระบบประสาท หัวใจและหลอดเลือด หรืออวัยวะล้มเหลวตามแผน", benefitType: "ผลประโยชน์โรคร้ายแรงตามกลุ่มที่เลือก" } },
  { id: "critical-illness-06", category: "critical-illness", group: "multi-disease", name: "FWD Big 3", insurer: "เอฟดับบลิวดี ประกันชีวิต", url: "https://www.fwd.co.th/th/critical-illness-insurance/big-3/", facts: { coveredConditions: "3 กลุ่มโรค: มะเร็ง หัวใจและหลอดเลือด สมองและระบบประสาท", benefitType: "เงินก้อนตามทุนที่เลือก เมื่อพบโรคที่เข้าเงื่อนไข" }, note: "เป็นความคุ้มครองเฉพาะ 3 กลุ่ม ไม่ใช่โรคร้ายแรงทุกโรค" },
  { id: "critical-illness-07", category: "critical-illness", group: "multi-disease", name: "AIA CI Care UDR", insurer: "เอไอเอ", url: "https://www.aia.co.th/th/our-products/health/aia-ci-care-udr", facts: { coveredConditions: "โรคร้ายแรงระดับต้นถึงปานกลาง และระดับรุนแรงตามคำนิยาม", benefitType: "ผลประโยชน์ตามสัดส่วนของทุนและระดับโรค", basePolicy: "สัญญาเพิ่มเติม UDR ต้องตรวจสัญญาชีวิตหลักและค่าใช้จ่ายรวม" }, note: "ไม่ใช่ประกันเดี่ยวที่ซื้อเฉพาะเบี้ยสัญญาเพิ่มเติมได้" },
  { id: "critical-illness-08", category: "critical-illness", group: "multi-disease", name: "เมืองไทย D Care โรคร้าย เจอ จ่าย", insurer: "เมืองไทยประกันชีวิต", url: "https://online.muangthai.co.th/th/mtlclick/detail/dcare", facts: { coveredConditions: "มี 6 กลุ่มโรคให้เลือกตามเงื่อนไขโครงการ", benefitType: "เงินก้อนตามกลุ่มโรค ระยะ และทุนที่เลือก", basePolicy: "สัญญาเพิ่มเติม D Care ต้องตรวจแผนหลักและราคารวม" }, note: "กลุ่มยอดฮิตมีเงื่อนไขห้ามซื้อบางกลุ่มเพิ่ม ไม่ถือว่าครบทั้ง 6 กลุ่มอัตโนมัติ" },
  { id: "cyber-01", category: "cyber", name: "คุ้มภัยโตเกียวมารีน TM Cyber 365", insurer: "คุ้มภัยโตเกียวมารีนประกันภัย", url: "https://www.tokiomarine.com/th/en/non-life/products/commercial/special-product/cyber-insurance.html", facts: { coveredActivity: "ผลิตภัณฑ์ประกันความเสี่ยงไซเบอร์สำหรับธุรกิจ TM Cyber 365" }, note: "ต้องยืนยันขอบเขตเหตุ ค่าใช้จ่ายตอบสนอง และวงเงินในใบเสนอราคา" },
  { id: "cyber-02", category: "cyber", name: "Chubb Cyber Enterprise Risk Management", insurer: "ชับบ์สามัคคีประกันภัย", url: "https://www.chubb.com/th-th/business/cyber-insurance.html", facts: { coveredActivity: "ความเสี่ยงไซเบอร์ขององค์กรและข้อมูลลูกค้าหรือพนักงาน", thirdPartyLiability: "มีความคุ้มครองความรับผิดทางไซเบอร์ตามกรมธรรม์ ERM" } },
  { id: "cyber-03", category: "cyber", name: "AIG CyberEdge", insurer: "เอไอจี ประกันภัย", url: "https://www.aig.co.th/en/home/risk-solutions/business/financial-lines/cyber", facts: { coveredActivity: "ความเสี่ยงข้อมูลรั่วไหล การแฮ็ก ไวรัส และความผิดพลาดด้านความปลอดภัย", businessInterruption: "มีความคุ้มครองธุรกิจหยุดชะงักจากเหตุไซเบอร์ตามแผน" }, note: "ความคุ้มครององค์กร ไม่ใช่รับรองชดใช้การโอนเงินจากมิจฉาชีพทุกกรณี" },
  { id: "event-01", category: "event", group: "cancellation", name: "กรุงเทพประกันภัย สำหรับผู้จัดงาน (Event Cancellation)", insurer: "กรุงเทพประกันภัย", url: bkiBusiness, locator: "หัวข้อ ประกันภัยสำหรับผู้จัดงาน", facts: { eventType: "ผู้จัดงานอีเวนต์ การประชุมและสัมมนา", cancellationScope: "ค่าใช้จ่ายเสียไปจากหยุดชะงัก ยกเลิก เลื่อน หรือเปลี่ยนสถานที่ ตามเงื่อนไข", lossOfProfit: "สามารถขยายถึงกำไรที่ลดลงจากการหยุดชะงักของงาน" }, note: "งานแต่งงาน / มงคลสมรส: ต้องสอบถามว่าบริษัทรับงานนั้นและเหตุใดบ้าง ไม่ยืนยันว่าการเปลี่ยนใจแต่งงานคุ้มครอง" },
  { id: "sports-01", priceEvidence: {"id": "sports-01:metadata:audit-20260912", "url": "https://www.msig-thai.com/th/personal-insurance/golfers-insurance", "publisher": "MSIG ประกันภัย", "title": "MSIG ประกันภัยผู้เล่นกอล์ฟ", "locator": "แนะนำผลิตภัณฑ์ / เบี้ยเริ่มต้น; ตารางเบี้ยประกันภัยรายปีรวม", "checkedAt": "2026-09-12", "publishedAt": null, "effectiveAt": null}, publishedPrice: {"kind": "starting", "amountTHB": 913.78, "period": "year", "scenario": "อัตราในตารางผลิตภัณฑ์ผู้เล่นกอล์ฟ; หน้าเว็บเรียกราคาเริ่มต้น ต้องตรวจคุณสมบัติก่อนซื้อ", "includes": "รวมอากรแสตมป์และภาษี", "sourceIds": ["sports-01:metadata:audit-20260912"]}, category: "sports", group: "golf", name: "MSIG ประกันภัยผู้เล่นกอล์ฟ", insurer: "MSIG ประกันภัย", url: "https://www.msig-thai.com/th/personal-insurance/golfers-insurance", facts: { sportType: "กอล์ฟ", accidentScope: "อุบัติเหตุผู้เล่นกอล์ฟตามเงื่อนไข", equipmentScope: "อุปกรณ์กอล์ฟสูญหายหรือเสียหายตามเงื่อนไข", thirdPartyLiability: "ความรับผิดต่อบุคคลอื่นจากการเล่นกอล์ฟ", territory: "สนามกอล์ฟในประเทศไทยตามเงื่อนไข" } },
  { id: "sports-02", category: "sports", group: "golf", name: "Chubb ประกันภัยผู้เล่นกอล์ฟ", insurer: "ชับบ์สามัคคีประกันภัย", url: "https://www.chubb.com/th-th/personal/golfers-insurance.html", facts: { sportType: "กอล์ฟ", accidentScope: "เสียชีวิต สูญเสียอวัยวะ หรือทุพพลภาพจากการเล่นหรือซ้อมกอล์ฟ", equipmentScope: "อุปกรณ์กอล์ฟตามเงื่อนไข", thirdPartyLiability: "ความรับผิดต่อบุคคลภายนอกตามกฎหมาย", territory: "สนามกอล์ฟหรือสนามฝึกซ้อมในประเทศไทย" } },
  { id: "sports-03", category: "sports", group: "golf", name: "คุ้มภัยโตเกียวมารีน Golfers Insurance", insurer: "คุ้มภัยโตเกียวมารีนประกันภัย", url: "https://www.tokiomarine.com/th/en/non-life/products/retail/travel-and-sports/golfers-insurance.html", facts: { sportType: "ประกันสำหรับผู้เล่นกอล์ฟ" }, note: "ต้องขอตารางผลประโยชน์และพื้นที่คุ้มครองของแผนที่เสนอ" },
  { id: "property-08", category: "property", name: "MSIG Baan Easy บ้านอีซี่", insurer: "MSIG ประกันภัย", url: "https://www.msig-thai.com/th/personal-insurance/baan-easy", facts: { occupancy: "บ้านอยู่อาศัย", includedPerils: "ทรัพย์สินภายในบ้านจากอัคคีภัย น้ำ ภัยไฟฟ้า และโจรกรรมตามแผน", valuation: "First Loss สำหรับทรัพย์สินภายใน ตามทุนที่เลือก" }, note: "คุ้มครองทรัพย์สินภายในตามแผน ไม่ใช่สรุปว่าทุนรวมอาคาร" },
  { id: "property-09", category: "property", name: "MSIG Condo Easy คอนโดอีซี่", insurer: "MSIG ประกันภัย", url: "https://www.msig-thai.com/th/personal-insurance/condo-easy", facts: { occupancy: "ห้องชุดเพื่ออยู่อาศัย", includedPerils: "ทรัพย์สินภายในห้องจากอัคคีภัย น้ำ ภัยไฟฟ้า และโจรกรรมตามแผน", valuation: "First Loss สำหรับทรัพย์สินภายในห้องชุด ตามทุนที่เลือก" } },
  { id: "property-10", category: "property", name: "MSIG My Home Safe", insurer: "MSIG ประกันภัย", url: "https://www.msig-thai.com/en/personal-insurance/my-home-safe", facts: { occupancy: "บ้านและคอนโดเพื่ออยู่อาศัย", includedPerils: "มีความคุ้มครองตัวอาคารและของภายใน รวมภัยธรรมชาติตามแผน", bundledLiability: "ความรับผิดต่อบุคคลภายนอกตามวงเงินที่เลือก" }, note: "ทุนสูงสุดที่โฆษณาไม่ใช่ทุนของผู้ซื้อทุกคน; น้ำท่วมมีเพดานเฉพาะ" },
  { id: "property-11", category: "property", name: "เมืองไทย อยู่ดีมีสุข", insurer: "เมืองไทยประกันภัย", url: "https://www.muangthaiinsurance.com/th/product/property-insurance", facts: { occupancy: "บ้านอยู่อาศัย", includedPerils: "อาคารและทรัพย์สินจากไฟไหม้และภัยตามตารางความคุ้มครอง", fireCoverage: "ไฟไหม้ ฟ้าผ่า และภัยระเบิดตามเงื่อนไข" }, note: "น้ำรั่วไม่ใช่น้ำท่วม; ต้องตรวจวงเงินภัยธรรมชาติแยกตามตาราง" },
  { id: "property-12", category: "property", name: "วิริยะ บ้านเปี่ยมสุข", insurer: "วิริยะประกันภัย", url: "https://www.viriyah.co.th/products/residental-property-insurance/pieamsuk-home-insurance/", facts: { occupancy: "อาคารอยู่อาศัยและทรัพย์สินภายใน", includedPerils: "แพ็กบ้าน 6 หมวดความคุ้มครองตามแผนที่เลือก", bundledLiability: "ความรับผิดต่อบุคคลภายนอกในฐานะเจ้าบ้านตามเงื่อนไข" }, note: "มี 9 แผนให้สอบถาม ไม่ใช้วงเงินจากแผนอื่นปนกับแผนที่จะซื้อ" },
  { id: "property-13", category: "property", name: "ทิพย บ้านทิพยยิ้มได้พลัส", insurer: "ทิพยประกันภัย", url: "https://ft.tipinsure.com/Fire/fire_product_choose", facts: { includedPerils: "ไฟไหม้ ฟ้าผ่า ภัยธรรมชาติ และภัยยานพาหนะตามแผน", occupancy: "บ้านอยู่อาศัยตามลักษณะสิ่งปลูกสร้างที่รับประกัน" }, note: "ระบุทุน อาคาร ที่ตั้ง และแผนก่อนยืนยันเบี้ยหรือวงเงินรายภัย" },
  { id: "property-14", category: "property", name: "กรุงเทพประกันภัย รักษ์บ้าน", insurer: "กรุงเทพประกันภัย", url: "https://www.bangkokinsurance.com/th/product/residential/rakbaan", facts: { occupancy: "บ้าน ทาวน์เฮาส์ ห้องชุดและคอนโด", includedPerils: "สิ่งปลูกสร้างและทรัพย์สินภายในตามแผนรักษ์บ้าน" } },
  { id: "property-15", category: "property", name: "กรุงเทพประกันภัย ทรัพย์สินภายในคอนโด", insurer: "กรุงเทพประกันภัย", url: bkiHome, locator: "หัวข้อ ประกันภัยทรัพย์สินภายในคอนโด", facts: { occupancy: "ห้องชุดพักอาศัย", includedPerils: "ทรัพย์สินภายในจากไฟไหม้ ฟ้าผ่า พายุ น้ำรั่ว แผ่นดินไหวและโจรกรรมตามแผน" } },
  { id: "property-16", category: "property", name: "กรุงเทพประกันภัย อัคคีภัยที่อยู่อาศัย 599", insurer: "กรุงเทพประกันภัย", url: bkiHome, locator: "หัวข้อ ประกันอัคคีภัยสำหรับที่อยู่อาศัย 599", facts: { occupancy: "ที่อยู่อาศัยตามเกณฑ์ไมโครอินชัวรันส์", includedPerils: "สิ่งปลูกสร้างและทรัพย์สินภายในจากอัคคีภัย ภัยธรรมชาติและโจรกรรมตามเงื่อนไข" }, note: "หน้าเว็บระบุ 599 บาท/ปี ต้องยืนยันคุณสมบัติและแผนในใบเสนอราคา" },
  { id: "property-17", category: "property", name: "กรุงเทพประกันภัย Home Cover Plus", insurer: "กรุงเทพประกันภัย", url: bkiHome, locator: "หัวข้อ ประกันภัยพร้อมสรรพสำหรับเจ้าบ้าน Home Cover Plus", facts: { occupancy: "บ้าน ทาวน์เฮาส์ ห้องชุดและคอนโด", includedPerils: "อาคารและของภายใน รวมที่พักชั่วคราวหรือสูญเสียค่าเช่าตามเงื่อนไข" } },
  { id: "business-01", category: "business", group: "construction", name: "MSIG FIT OUT LITE งานตกแต่งภายใน", insurer: "MSIG ประกันภัย", url: msig + "contractors%E2%80%99-all-risks-insurance", facts: { businessType: "ความเสี่ยงงานตามสัญญา / งานตกแต่ง", coveredActivity: "เจ้าของงาน ผู้ว่าจ้างและผู้รับเหมา; งานตกแต่งและทรัพย์สินเดิมตามสัญญา", thirdPartyLiability: "มีความรับผิดต่อบุคคลภายนอกตามโครงการ" } },
  { id: "business-02", category: "business", group: "installation", name: "MSIG Erection All Risks", insurer: "MSIG ประกันภัย", url: msig + "erection-all-risks-insurance", facts: { businessType: "การติดตั้งเครื่องจักร", coveredActivity: "ระหว่างติดตั้ง ทดสอบ และเริ่มใช้งานเครื่องจักร", thirdPartyLiability: "ความรับผิดต่อบุคคลอื่นตามเงื่อนไขโครงการ" } },
  { id: "business-03", category: "business", group: "machinery", name: "MSIG Machinery All Risks", insurer: "MSIG ประกันภัย", url: msig + "machinery-all-risks-insurance", facts: { businessType: "ความเสี่ยงเครื่องจักร", coveredActivity: "ความสูญเสียหรือเสียหายของเครื่องจักรจากภัยที่ไม่อยู่ในข้อยกเว้น" } },
  { id: "business-04", period: "year", category: "business", group: "cargo", name: "MSIG Inland Cargo", insurer: "MSIG ประกันภัย", url: msig + "inland-cargo", facts: { businessType: "สินค้าขนส่งภายในประเทศ", coveredActivity: "สินค้าระหว่างขนส่งที่ผู้เอาประกันมีส่วนได้เสีย", territory: "การขนส่งภายในประเทศไทย" } },
  { id: "business-05", category: "business", group: "commercial-property", name: "Chubb Industrial All Risks", insurer: "ชับบ์สามัคคีประกันภัย", url: "https://www.chubb.com/th-th/business/industrial-all-risks-insurance.html", facts: { businessType: "ทรัพย์สินกิจการและอุตสาหกรรม", coveredActivity: "ความสูญเสียหรือเสียหายทางกายภาพต่อทรัพย์สินตามตารางกรมธรรม์" } },
  { id: "business-06", category: "business", group: "sme", name: "Chubb SME Value for Servicing Business", insurer: "ชับบ์สามัคคีประกันภัย", url: "https://www.chubb.com/th-en/business/sme-value-for-servicing-business.html", facts: { businessType: "แพ็กประกัน SME ธุรกิจบริการ", coveredActivity: "ธุรกิจบริการที่ผ่านเงื่อนไขรับประกันของ SME Value" }, note: "อาจต้องสำรวจสถานที่และยืนยันลักษณะกิจการก่อนเสนอราคา" },
  { id: "business-07", category: "business", group: "trade-credit", name: "กรุงเทพประกันภัย สินเชื่อทางการค้า", insurer: "กรุงเทพประกันภัย", url: bkiBusiness, locator: "หัวข้อ ประกันภัยสินเชื่อทางการค้า", facts: { businessType: "ความเสี่ยงสินเชื่อการค้า", coveredActivity: "หนี้การค้าที่ไม่ชำระจากเหตุที่กรมธรรม์กำหนด" } },
  { id: "business-08", category: "business", group: "workers-compensation", name: "กรุงเทพประกันภัย เงินทดแทนแรงงาน", insurer: "กรุงเทพประกันภัย", url: bkiBusiness, locator: "หัวข้อ ประกันภัยเงินทดแทนแรงงาน", facts: { businessType: "ความรับผิดของนายจ้าง", coveredActivity: "ลูกจ้างบาดเจ็บหรือป่วยจากงานตามเงื่อนไข" } },
  { id: "business-09", category: "business", group: "fidelity", name: "กรุงเทพประกันภัย ความซื่อสัตย์ของลูกจ้าง", insurer: "กรุงเทพประกันภัย", url: bkiBusiness, locator: "หัวข้อ ประกันภัยความซื่อสัตย์ของลูกจ้าง", facts: { businessType: "การทุจริตของลูกจ้าง", coveredActivity: "ความเสียหายจากฉ้อโกง ยักยอก หรือทุจริตตามกรมธรรม์" } },
  { id: "business-10", category: "business", group: "jewellers", name: "กรุงเทพประกันภัย ร้านทอง", insurer: "กรุงเทพประกันภัย", url: bkiBusiness, locator: "หัวข้อ ประกันภัยร้านทอง", facts: { businessType: "ร้านทอง", coveredActivity: "ทองและทรัพย์สินร้านจากเหตุที่ระบุในกรมธรรม์" } },
  { id: "business-11", category: "business", group: "jewellers", name: "กรุงเทพประกันภัย เบ็ดเสร็จคุ้มครองผู้ค้าอัญมณี", insurer: "กรุงเทพประกันภัย", url: bkiBusiness, locator: "หัวข้อ ประกันภัยเบ็ดเสร็จคุ้มครองผู้ค้าอัญมณี", facts: { businessType: "ผู้ค้าอัญมณี", coveredActivity: "อัญมณีในความดูแลจากอุบัติเหตุหรือโจรกรรมตามเงื่อนไข" } },
  { id: "business-12", category: "business", group: "commercial-property", name: "กรุงเทพประกันภัย การเสี่ยงภัยทุกชนิด", insurer: "กรุงเทพประกันภัย", url: bkiBusiness, locator: "หัวข้อ ประกันภัยการเสี่ยงภัยทุกชนิด", facts: { businessType: "ความเสี่ยงทรัพย์สิน", coveredActivity: "ทรัพย์สินจากอุบัติเหตุที่ไม่ระบุยกเว้นในกรมธรรม์" } },
  { id: "business-13", category: "business", group: "sme", name: "กรุงเทพประกันภัย ร้านค้าอุ่นใจ", insurer: "กรุงเทพประกันภัย", url: "https://www.bangkokinsurance.com/th/product/residential/shop", facts: { businessType: "แพ็กประกันร้านค้า", coveredActivity: "ความเสี่ยงสำหรับเจ้าของร้านค้าตามแพ็กเกจที่เลือก" } },
  { id: "business-14", category: "business", group: "commercial-property", name: "กรุงเทพประกันภัย อัคคีภัยสถานประกอบการ", insurer: "กรุงเทพประกันภัย", url: "https://www.bangkokinsurance.com/th/product/residential/fire", facts: { businessType: "อัคคีภัยกิจการ", coveredActivity: "อาคาร อุปกรณ์ เครื่องมือและสินค้าภายในสถานประกอบการตามเงื่อนไข" } },
];

export function buildCatalogExpansion(categoryFields: Record<Category, readonly Field[]>): Plan[] {
  return catalogExpansionRecords.map(record => {
    const checkedAt = "2026-09-12";
    const source = (key: string, locator: string): SourceEvidence => ({ id: `${record.id}:${key}`, url: record.url, publisher: record.insurer, title: record.name, locator, checkedAt, publishedAt: null, effectiveAt: null });
    const sources = [source("identity", record.locator ?? "ชื่อผลิตภัณฑ์"), source("price", "ยังไม่ได้เลือกตัวเลือกและผู้เอาประกันเพื่อขอราคาจริง")];
    if (record.priceEvidence) sources.push(record.priceEvidence);
    const coverageCells: Record<string, CoverageCell> = Object.fromEntries(categoryFields[record.category].map(field => {
      const value = record.facts[field.key];
      if (!value) return [field.key, { status: "unknown", value: null, unit: null, basis: null, inclusion: "unknown", conditions: [], sourceIds: [] } satisfies CoverageCell];
      const evidence = source(field.key, record.locator ?? "ข้อมูลผลิตภัณฑ์ / จุดเด่นและเงื่อนไข"); sources.push(evidence);
      return [field.key, { status: "known", value, unit: null, basis: field.key, inclusion: "unknown", conditions: record.fieldConditions?.[field.key] ?? [], sourceIds: [evidence.id] } satisfies CoverageCell];
    }));
    const note = record.note ?? "ต้องเลือกทุนและตรวจเงื่อนไขเฉพาะผู้เอาประกันก่อนยืนยันราคา";
    return { id: record.id, category: record.category, ...(record.group ? { comparisonGroup: `${record.category}:${record.group}` } : {}), productId: record.id, tierLabel: null, edition: null, name: record.name, insurer: record.insurer,
      price: record.publishedPrice ?? { kind: "quote_only", amountTHB: null, period: record.period ?? (record.category === "event" || ["construction", "installation", "cargo"].includes(record.group ?? "") ? "single" : "year"), scenario: "ข้อมูลผลิตภัณฑ์ ยังไม่เลือกแผนย่อยหรือทุน ต้องขอใบเสนอราคา", includes: null, sourceIds: [`${record.id}:price`] },
      coverageCells, sources, premiumTHB: record.publishedPrice?.amountTHB ?? null, premiumPeriod: record.period ?? (record.category === "event" || ["construction", "installation", "cargo"].includes(record.group ?? "") ? "single" : "year"), premiumNote: record.publishedPrice ? "เบี้ยเริ่มต้น รวมอากรและภาษี" : "ขอใบเสนอราคาเฉพาะแผนที่เลือก", image: "/images/plan-placeholder.svg", highlights: [Object.values(record.facts)[0], Object.values(record.facts)[1] ?? note, ...(record.note ? [record.note] : [])],
      eligibility: "ต้องตรวจผู้เอาประกัน วัตถุหรือกิจกรรมที่ประกัน และเงื่อนไขกับบริษัทก่อนสมัคร", exclusions: [note, "ข้อมูลที่ไม่ทราบไม่ได้หมายความว่าไม่คุ้มครอง; โปรดตรวจกรมธรรม์ฉบับเสนอขาย"], coverage: Object.fromEntries(Object.entries(coverageCells).map(([key, cell]) => [key, cell.value])), source: { kind: "official", label: record.name, updatedAt: checkedAt, url: record.url },
    };
  });
}
