import type { Category, CoverageCell, CoverageValue, Field, Plan, PlanSort, PremiumPeriod, Price, SourceEvidence } from "./types.ts";
import { planImages } from "./plan-images.ts";

export const categoryFields: Record<Category, readonly Field[]> = {
  health: [
    { key: "annualLimit", label: "วงเงินต่อปี", unit: "บาท/ปี" },
    { key: "perDiseaseLimit", label: "วงเงินต่อโรค", unit: "บาท" },
    { key: "perAdmissionLimit", label: "วงเงินต่อการเข้าพักรักษา", unit: "บาท/ครั้ง" },
    { key: "roomPerDay", label: "ค่าห้องต่อวัน", unit: "บาท/วัน" },
    { key: "opdPerYear", label: "ผู้ป่วยนอกต่อปี", unit: "บาท/ปี" },
    { key: "opdPerVisit", label: "OPD ต่อครั้ง", unit: "บาท" },
    { key: "roomBasis", label: "เงื่อนไขค่าห้อง", unit: null },
    { key: "deductible", label: "ความรับผิดส่วนแรก", unit: "บาท" },
    { key: "waitingDays", label: "ระยะรอคอย", unit: "วัน" },
    { key: "icuPerDay", label: "ค่าห้อง ICU ต่อวัน", unit: "บาท" },
    { key: "icuMaxDays", label: "จำนวนวัน ICU สูงสุด", unit: "วัน" },
    { key: "roomMaxDays", label: "จำนวนวันค่าห้องสูงสุด", unit: "วัน" },
    { key: "opdVisitsPerDay", label: "OPD สูงสุดต่อวัน", unit: "ครั้ง" },
    { key: "copay", label: "เงื่อนไขร่วมจ่าย Copay", unit: null },
    { key: "minEntryAge", label: "อายุเริ่มสมัคร", unit: null },
    { key: "maxEntryAge", label: "อายุสูงสุดที่สมัคร", unit: "ปี" },
    { key: "renewalAge", label: "ต่ออายุได้ถึง", unit: "ปี" },
    { key: "eligibilityConditions", label: "เงื่อนไขผู้สมัคร", unit: null },
  ],
  motor: [
    { key: "collisionLimit", label: "รถชน", unit: "บาท" },
    { key: "theftLimit", label: "รถสูญหาย", unit: "บาท" },
    { key: "fireLimit", label: "รถไฟไหม้", unit: "บาท" },
    { key: "floodLimit", label: "น้ำท่วม/ภัยธรรมชาติ", unit: "บาท" },
    { key: "thirdPartyBodilyPerPerson", label: "บาดเจ็บบุคคลภายนอกต่อคน", unit: "บาท" },
    { key: "thirdPartyBodilyPerEvent", label: "บาดเจ็บบุคคลภายนอกต่อเหตุ", unit: "บาท" },
    { key: "class", label: "ประเภทชั้น", unit: null },
    { key: "ownDamageLimit", label: "คุ้มครองรถยนต์", unit: "บาท" },
    { key: "thirdPartyProperty", label: "ทรัพย์สินบุคคลภายนอก", unit: "บาท" },
    { key: "deductible", label: "ความรับผิดส่วนแรก", unit: "บาท" },
    { key: "voluntaryMedicalPerPerson", label: "ค่ารักษาผู้ขับขี่/ผู้โดยสาร ภาคสมัครใจ", unit: "บาท/คน" },
    { key: "medicalPerPerson", label: "ค่ารักษาต่อคนตาม พ.ร.บ.", unit: "บาท/คน" },
    { key: "repairType", label: "รูปแบบการซ่อม", unit: null },
  ],
  life: [
    { key: "lifeType", label: "รูปแบบประกันชีวิต", unit: null },
    { key: "deathFormula", label: "ผลประโยชน์เสียชีวิต", unit: null },
    { key: "maturityFormula", label: "ผลประโยชน์ครบสัญญา", unit: null },
    { key: "guaranteedCashback", label: "เงินคืนระหว่างสัญญา", unit: null },
    { key: "nonGuaranteedBenefit", label: "ผลประโยชน์ที่ไม่รับประกัน", unit: null },
    { key: "paymentFrequency", label: "รอบชำระเบี้ย", unit: null },
    { key: "sumAssured", label: "ทุนประกันชีวิต", unit: "บาท" },
    { key: "coverageUntilAge", label: "คุ้มครองถึงอายุ", unit: "ปี" },
    { key: "coverageYears", label: "ระยะคุ้มครอง", unit: "ปี" },
    { key: "paymentYears", label: "ระยะเวลาชำระเบี้ย", unit: "ปี" },
    { key: "minEntryAge", label: "อายุเริ่มต้น", unit: "ปี" },
    { key: "maxEntryAge", label: "อายุสูงสุด", unit: "ปี" },
  ],
  accident: [
    { key: "hospitalAdmissionBenefit", label: "เงินก้อนเมื่อนอนโรงพยาบาลเข้าเงื่อนไข", unit: "บาท/ครั้ง" },
    { key: "motorcycleBenefit", label: "อุบัติเหตุรถจักรยานยนต์", unit: "บาท" },
    { key: "homicideBenefit", label: "ถูกฆาตกรรมหรือทำร้าย", unit: "บาท" },
    { key: "publicAccidentBenefit", label: "อุบัติเหตุสาธารณะ", unit: "บาท" },
    { key: "dailyAllowance", label: "เงินชดเชยรายวัน", unit: "บาท" },
    { key: "dailyMaxDays", label: "ชดเชยสูงสุดต่อครั้ง", unit: "วัน" },
    { key: "occupationClass", label: "กลุ่มอาชีพ", unit: null },
    { key: "deathBenefit", label: "เสียชีวิตจากอุบัติเหตุ", unit: "บาท" },
    { key: "medicalPerAccident", label: "ค่ารักษาต่ออุบัติเหตุ", unit: "บาท" },
    { key: "disabilityBenefit", label: "ทุพพลภาพ", unit: "บาท" },
    { key: "minEntryAge", label: "อายุเริ่มต้น", unit: "ปี" },
    { key: "maxEntryAge", label: "อายุสูงสุด", unit: "ปี" },
  ],
  travel: [
    { key: "policyDuration", label: "ระยะกรมธรรม์", unit: null },
    { key: "evacuationLimit", label: "เคลื่อนย้ายผู้ป่วยฉุกเฉิน", unit: "บาท" },
    { key: "repatriationLimit", label: "ส่งศพ/อัฐิกลับ", unit: "บาท" },
    { key: "interruptionLimit", label: "ลดจำนวนวันเดินทาง", unit: "บาท" },
    { key: "delayHours", label: "ช่วงเวลาล่าช้าต่อการจ่าย", unit: "ชั่วโมง" },
    { key: "delayPayment", label: "จ่ายต่อช่วงเวลาล่าช้า", unit: "บาท" },
    { key: "delayLimit", label: "ล่าช้าจ่ายสูงสุด", unit: "บาท" },
    { key: "delayTrigger", label: "สาเหตุล่าช้าที่เข้าเงื่อนไข", unit: null },
    { key: "medicalLimit", label: "ค่ารักษาพยาบาล", unit: "บาท" },
    { key: "cancellationLimit", label: "ยกเลิกการเดินทาง", unit: "บาท" },
    { key: "baggageLimit", label: "สัมภาระ", unit: "บาท" },
    { key: "maxTripDays", label: "เดินทางสูงสุด", unit: "วัน" },
    { key: "region", label: "พื้นที่คุ้มครอง", unit: null },
  ],
  property: [
    { key: "combinedPropertyLimit", label: "ทุนรวมอาคารและทรัพย์สินภายใน", unit: "บาท" },
    { key: "floodLimit", label: "วงเงินน้ำท่วม", unit: "บาท" },
    { key: "fireCoverage", label: "อัคคีภัย", unit: null },
    { key: "burglaryCoverage", label: "โจรกรรมทรัพย์สิน", unit: null },
    { key: "bundledLiability", label: "ความรับผิดในแพ็กบ้าน", unit: null },
    { key: "occupancy", label: "การใช้งานที่อยู่อาศัย", unit: null },
    { key: "construction", label: "โครงสร้างอาคาร", unit: null },
    { key: "valuation", label: "เกณฑ์มูลค่าทรัพย์สิน", unit: null },
    { key: "locationRestrictions", label: "พื้นที่ไม่รับประกัน", unit: null },
    { key: "buildingLimit", label: "ตัวอาคาร", unit: "บาท" },
    { key: "contentsLimit", label: "ทรัพย์สินภายในบ้าน", unit: "บาท" },
    { key: "sharedNaturalPerilsLimit", label: "วงเงินรวมภัยธรรมชาติ", unit: "บาท" },
    { key: "deductible", label: "ความรับผิดส่วนแรก", unit: "บาท" },
    { key: "includedPerils", label: "ภัยในวงเงินรวม", unit: null },
  ],
  liability: [
    { key: "perOccurrenceLimit", label: "ต่อเหตุการณ์", unit: "บาท" },
    { key: "aggregateLimit", label: "รวมต่อปี", unit: "บาท/ปี" },
    { key: "deductible", label: "ความรับผิดส่วนแรก", unit: "บาท" },
    { key: "territory", label: "พื้นที่คุ้มครอง", unit: null },
    { key: "coveredActivity", label: "กิจกรรมที่คุ้มครอง", unit: null },
  ],
};

// Field evidence is canonical. Compatibility properties below are derived, never separately seeded.
type CellInput = Omit<CoverageCell, "sourceIds"> & { locator: string; url?: string };
type PriceInput = Omit<Price, "sourceIds"> & { locator: string; url?: string };
type Seed = { id: string; category: Category; productId: string; name: string; insurer?: string; eligibility?: string; eligibilitySource?: {url:string;locator:string}; exclusions?: string[]; image?: string; tierLabel?: string; subtype?: Plan["subtype"]; url: string; price: PriceInput; cells: Record<string, CellInput>; highlights: string[]; extraSources?: {url:string;locator:string}[]; edition?: string };
const checkedAt = "2026-09-12";
const axa = "https://www.axa.co.th/th/personal/";
const mtl = "https://online.muangthai.co.th/th/detail/";
const known = (value: Exclude<CoverageValue,null>, unit: string | null, basis: string, locator: string, conditions: string[] = [], inclusion: CoverageCell["inclusion"] = "included"): CellInput => ({status:"known",value,unit,basis,inclusion,conditions,locator});
const missing = (conditions: string[] = [], inclusion: CoverageCell["inclusion"] = "unknown", locator = "ไม่มีค่าของตัวเลือกที่ยืนยันได้ในข้อมูลผลิตภัณฑ์"): CellInput => ({status:"unknown",value:null,unit:null,basis:null,inclusion,conditions,locator});
const absent = (status: "not_covered" | "not_applicable", locator: string, conditions: string[] = []): CellInput => ({status,value:null,unit:null,basis:null,inclusion:"included",conditions,locator});
const conflict = (locator: string, conditions: string[]): CellInput => ({status:"conflicting",value:null,unit:"ปี",basis:"entry_age",inclusion:"unknown",conditions,locator});
const price = (kind: Price["kind"], amountTHB: number | null, period: PremiumPeriod, scenario: string | null, locator: string, includes: string | null = null, url?: string): PriceInput => ({kind,amountTHB,period,scenario,includes,locator,url});
const quote = (scenario: string | null = null, period: PremiumPeriod = "year"): PriceInput => price("quote_only",null,period,scenario,"การขอใบเสนอราคา / ไม่มีราคาเฉพาะตัวเลือกที่ยืนยันได้");
const healthValueUrl = `${axa}health-insurance/value-plan`;
const healthEssentialUrl = `${axa}health-insurance/comprehensive-plan`;
const healthMtlUrl = "https://online.muangthai.co.th/th/Health-IPD-OPD/category/health";
const protectionUrl = "https://www.muangthai.co.th/filestorage/brochures/20250630-04-0174%20%E0%B9%82%E0%B8%9A%E0%B8%A3%E0%B8%8A%E0%B8%B1%E0%B8%A7%E0%B8%A3%E0%B9%8C%20%E0%B8%AA%E0%B8%A1%E0%B8%B2%E0%B8%A3%E0%B9%8C%E0%B8%97%E0%B9%82%E0%B8%9E%E0%B8%A3%E0%B9%80%E0%B8%97%E0%B8%84%E0%B8%8A%E0%B8%B1%E0%B9%88%E0%B8%99%2099-20.pdf";
const motorNewsUrl = "https://www.axa.co.th/th/blog/news_updated-motor-insurance-2025";
const seeds: Seed[] = [
  {id:"health-01",category:"health",productId:"axa-smartcare-value",name:"AXA SmartCare Value",tierLabel:"แผน 1",url:healthValueUrl,
    price:price("starting",6700,"year","ราคาเริ่มต้นของผลิตภัณฑ์; อายุและตัวเลือกของราคาเริ่มต้นไม่ระบุ ไม่ใช่ราคาเสนอเฉพาะแผน 1","จุดเด่น: เบี้ยเริ่มต้น 6,700 บาทต่อปี"),
    cells:{annualLimit:known(2500000,"บาท","per_year","ตาราง แผน 1 / ผลประโยชน์สูงสุดต่อปี"),perAdmissionLimit:known(500000,"บาท","per_admission","ตาราง แผน 1 / วงเงินต่อการเข้าพักรักษา และเงื่อนไขการรับประกันข้อ 6",["การบาดเจ็บหรือการป่วยเดียวกัน รวมการผ่าตัดใหญ่แบบไม่พักรักษา (Day Surgery) ภายใน 90 วันนับจากออกโรงพยาบาลครั้งสุดท้าย นับเป็นการรักษาครั้งเดียวกัน ไม่ได้วงเงินใหม่ทุกการเข้าโรงพยาบาล"]),roomPerDay:known(2500,"บาท","per_day","ตาราง แผน 1 / 1.1 ห้องเดี่ยวมาตรฐาน"),waitingDays:known(30,"วัน","waiting_period","FAQ / ระยะรอคอย",["โรคที่ระบุบางรายการรอ 120 วัน; อุบัติเหตุได้รับยกเว้น"]),opdPerYear:missing(["มี OPD ต่อเนื่องจาก IPD และอุบัติเหตุตามเงื่อนไข ไม่ใช่วงเงิน OPD ทั่วไปรายปี"],"unknown","ตาราง / ผลประโยชน์กรณีไม่ต้องพักรักษา")},
    highlights:["แผน 1 วงเงิน 2.5 ล้านบาทต่อปี และ 500,000 บาทต่อการเข้าพักรักษา","ตอบคำถามสุขภาพ; โรคที่เป็นมาก่อนและระยะรอคอยเป็นไปตามเงื่อนไข"]},
  {id:"health-02",category:"health",productId:"axa-smartcare-essential",name:"AXA SmartCare Essential",tierLabel:"แผน 4",url:healthEssentialUrl,
    price:price("starting",15680,"year","ราคาเริ่มต้นของทั้งผลิตภัณฑ์ ไม่ยืนยันว่าเป็นราคาแผน 4 หรือรวม OPD","บัตรผลิตภัณฑ์ SmartCare Essential / ราคาเริ่มต้น",null,`${axa}health-insurance`),
    cells:{perDiseaseLimit:known(10000000,"บาท","per_disease","ตาราง แผน 4 / วงเงินต่อโรค และเงื่อนไขการรับประกันข้อ 6",["การรักษาจากโรคเดียวกันหรือภาวะแทรกซ้อน ไม่ว่ากี่ครั้งภายใน 90 วันนับจากออกโรงพยาบาลครั้งสุดท้าย นับเป็นการเข้าพักรักษาครั้งเดียวกัน"]),roomPerDay:known(12000,"บาท","per_day","ตาราง แผน 4 / ค่าห้องผู้ป่วยธรรมดา"),opdPerYear:known(50000,"บาท","per_year","จุดเด่น / ตัวเลือก OPD",["เลือก OPD รายปี 50,000 บาท หรือรายครั้ง 3,000 บาท; ยังไม่ได้เลือกและไม่ถือว่ารวมในเบี้ยเริ่มต้น"],"optional"),waitingDays:known(30,"วัน","waiting_period","เงื่อนไขการรับประกันภัย ข้อ 3–4 / ระยะรอคอย",["โรคที่ระบุบางรายการรอ 120 วัน; อุบัติเหตุได้รับยกเว้น"])} ,highlights:["แผน 4 วงเงินสูงสุด 10 ล้านบาทต่อโรค","OPD เป็นตัวเลือกเพิ่มเติม ต้องตรวจเบี้ยและตัวเลือกก่อนซื้อ"]},
  ...(["S","M","L"] as const).map((tier,i):Seed=>({id:`health-0${i+3}`,category:"health",productId:"mtl-health-sukjai-ipd-opd",name:`Health สุขใจ IPD+OPD (แพ็ก ${tier})`,tierLabel:`แพ็ก ${tier}`,url:`https://online.muangthai.co.th/th/Health-IPD-OPD/detail/ipd-opd-sukjai-${tier.toLowerCase()}`,
    price:price("example",[25339.5,27696.5,34301.5][i],"year",`ชายอายุ 35 ปี แพ็ก ${tier}`,`บัตรแพ็ก ${tier} / ตัวอย่างชายอายุ 35 ปี / ชำระต่อปี`,null,healthMtlUrl),
    cells:{perAdmissionLimit:known([700000,1000000,5000000][i],"บาท","per_admission",`แพ็ก ${tier} / วงเงิน IPD และหมายเหตุ 10`,["โรคหรือการบาดเจ็บเดิม รวมภาวะแทรกซ้อนที่เกี่ยวข้องภายใน 90 วัน ใช้วงเงินเดิม; เกิน 90 วันนับจากออกโรงพยาบาลครั้งสุดท้ายจึงเริ่มวงเงินใหม่"]),opdPerYear:known([20000,20000,30000][i],"บาท","per_year",`แพ็ก ${tier} / วงเงิน OPD และหมายเหตุ 4`,["พบแพทย์ได้สูงสุด 2 ครั้งต่อวัน; ไม่จำกัดวงเงินต่อครั้งแต่รวมไม่เกินวงเงินรายปี"]),waitingDays:known(30,"วัน","waiting_period","ไม่คุ้มครองกรณีไหนบ้าง / ระยะรอคอย 30, 120 และ 180 วัน",["การเจ็บป่วยทั่วไปมีระยะรอคอย 30 วัน","120 วันสำหรับเนื้องอก/ถุงน้ำ/มะเร็ง ริดสีดวงทวาร ไส้เลื่อน ต้อเนื้อ/ต้อกระจก ผ่าตัดทอนซิล/อดีนอยด์ นิ่ว เส้นเลือดขอดที่ขา และเยื่อบุโพรงมดลูกเจริญผิดที่","เฉพาะ OPD: รอ 180 วันสำหรับโรคไทรอยด์ ลมบ้าหมู เบาหวาน ภูมิแพ้ ความดันโลหิตสูง หัวใจ และโรคเกี่ยวกับกระเพาะอาหาร"])},highlights:[`IPD ${["700,000","1,000,000","5,000,000"][i]} บาทต่อการเข้าพักรักษา โดยนับโรคเดิมตามเงื่อนไข 90 วัน`,`OPD ${i===2?"30,000":"20,000"} บาทต่อปี; ราคาเป็นตัวอย่างชาย 35 ปี`]})),
  ...(["type1","electric-vehicle-ev","type2-plus","type3-plus"] as const).map((path,i):Seed=>({id:`motor-0${i+1}`,category:"motor",productId:`axa-smartdrive-${path}`,name:["AXA SmartDrive ชั้น 1","AXA SmartDrive ชั้น 1 EV/PHEV","AXA SmartDrive ชั้น 2+","AXA SmartDrive ชั้น 3+"][i],subtype:"voluntary",url:`${axa}car-insurance/${path}`,
    price:i<2?quote("ราคาตามรถ ผู้ขับ ทุนประกันและตัวเลือกซ่อม"):price("starting",i===2?5800:5400,"year","ราคาเปิดตัว 30 มิถุนายน 2568; ต้องขอราคาปัจจุบันตามรถและตัวเลือก","ข่าว 04 กรกฎาคม 2568 / ราคาเริ่มต้นชั้น 2+ และ 3+",null,motorNewsUrl),
    cells:{class:known(["ชั้น 1","ชั้น 1 EV/PHEV","ชั้น 2+","ชั้น 3+"][i],null,"motor_class","ชื่อผลิตภัณฑ์"),ownDamageLimit:missing(["กำหนดตามทุนรถที่เลือก"],"included","ตาราง / ความเสียหายต่อตัวรถ ตามทุนประกัน"),thirdPartyProperty:i===1?missing(["รถเก๋ง 5 ล้านบาท; รถกระบะและรถตู้ 2.5 ล้านบาท; ยังไม่ได้ระบุรถ"],"included","ตาราง / ความเสียหายต่อทรัพย์สินต่อครั้ง"):known(i===0?5000000:1000000,"บาท","per_occurrence","ตาราง / ความเสียหายต่อทรัพย์สินต่อครั้ง"),deductible:i===1?known(0,"บาท","per_claim","ตาราง EV/PHEV / ค่าเสียหายส่วนแรก และประกาศนโยบาย EV / เกณฑ์ตั้งแต่ 1 มิถุนายน 2567",["ส่วนแรกทั่วไป 0 บาทตามตาราง; มีข้อยกเว้นผู้ขับขี่ที่ไม่ระบุชื่อ","สำหรับ EV รถนั่งส่วนบุคคลไม่เกิน 7 ที่นั่งที่ชำระหรือต่ออายุตั้งแต่ 1 มิถุนายน 2567 ต้องระบุผู้ขับขี่ 1–5 คน; อุบัติเหตุที่ผู้ขับขี่ไม่อยู่ในรายชื่อมี excess 6,000 บาทตามประกาศ"]):missing([i===0?"เลือกไม่มีส่วนแรก หรือ 3,000 / 5,000 บาท":"เลือกไม่มีส่วนแรก หรือ 2,000 บาท"],"unknown","ตาราง/จุดเด่น / ตัวเลือกค่าเสียหายส่วนแรก"),repairType:missing([i===0?"เลือกซ่อมห้างรถอายุไม่เกิน 5 ปี หรืออู่ในเครือไม่เกิน 15 ปี":"ตัวเลือกซ่อมขึ้นกับรถและแผนที่เสนอ"],"unknown","จุดเด่น / ตัวเลือกซ่อม"),medicalPerPerson:absent("not_applicable","ผลิตภัณฑ์ภาคสมัครใจ; ช่องนี้เป็นค่ารักษาตาม พ.ร.บ.")},highlights:[i===3?"รถชนรถ; สูญหายและไฟไหม้ไม่คุ้มครอง":i===2?"รถชนรถ สูญหาย ไฟไหม้; ภัยธรรมชาติเป็นตัวเลือกเพิ่ม":"คุ้มครองความเสียหายรถและความรับผิดตามกรมธรรม์","วงเงินรถและค่าเสียหายส่วนแรกต้องดูตัวเลือกในใบเสนอราคา"]})),
  {id:"motor-05",category:"motor",productId:"axa-compulsory-motor",name:"AXA พ.ร.บ. รถยนต์",subtype:"compulsory",url:`${axa}car-insurance/compulsory`,price:{...quote("ราคาไม่ยืนยัน: หัวข้อ 645.21 บาทขัดกับตารางออนไลน์ 581.01 บาทสำหรับรถส่วนบุคคลไม่เกิน 7 ที่นั่ง; โปรโมชั่นที่เชื่อมโยงสิ้นสุด 15 ม.ค. 2569 ต้องขอราคาปัจจุบัน"),locator:"หัวข้อราคา / ตารางเบี้ยรถไม่เกิน 7 ที่นั่ง"},extraSources:[{url:"https://www.axa.co.th/th/promotion/axacar-promotion",locator:"เงื่อนไขโปรโมชั่น ข้อ 1–4 / สิ้นสุด 15 มกราคม 2569"}],cells:{class:known("พ.ร.บ.",null,"motor_class","ชื่อผลิตภัณฑ์"),medicalPerPerson:known(80000,"บาท","per_person","ตารางความคุ้มครอง พ.ร.บ. / ค่ารักษาพยาบาลสูงสุด",["ค่ารักษาเบื้องต้น 30,000 บาทโดยไม่รอพิสูจน์ผิด; สูงสุด 80,000 บาทตามเงื่อนไขความรับผิด"]),ownDamageLimit:absent("not_covered","ข้อมูลผลิตภัณฑ์ / คุ้มครองผู้ประสบภัยทางร่างกาย ไม่ใช่รถตนเอง"),thirdPartyProperty:absent("not_covered","ข้อมูลผลิตภัณฑ์ / คุ้มครองผู้ประสบภัยทางร่างกาย ไม่ใช่ทรัพย์สิน"),repairType:absent("not_applicable","ความคุ้มครอง พ.ร.บ. ไม่ใช่บริการซ่อมรถ"),deductible:absent("not_applicable","ความคุ้มครอง พ.ร.บ. ไม่ใช้ตัวเลือกส่วนแรกของประกันภาคสมัครใจ")},highlights:["ค่ารักษาเบื้องต้น 30,000 บาท; สูงสุด 80,000 บาทตามเงื่อนไข","เป็นประกันภาคบังคับ คุ้มครองร่างกาย ไม่ใช่ค่าซ่อมรถ"]},
  {id:"life-01",category:"life",productId:"mtl-smart-protection-99-20",name:"เมืองไทย สมาร์ท โพรเทคชั่น 99/20",url:protectionUrl,edition:"MTL_2-02-04-0174_21/07/2568",price:price("example",22170,"year","หญิงอายุ 35 ปี สุขภาพแข็งแรง ทุน 1,000,000 บาท","PDF หน้า 2 / ตัวอย่างผลประโยชน์และเบี้ย"),cells:{sumAssured:known(1000000,"บาท","initial_sum_assured","PDF หน้า 2 / ตัวอย่างหญิง 35 ปี",["ทุนของตัวอย่างเบี้ย ไม่ใช่ทุนคงที่สำหรับผู้ซื้อทุกคน"]),coverageUntilAge:known(99,"ปี","until_age","PDF หน้า 2 / ระยะเวลาเอาประกันภัย"),coverageYears:absent("not_applicable","PDF หน้า 2 / คุ้มครองถึงอายุ 99 ไม่ใช่ระยะคงที่"),paymentYears:known(20,"ปี","payment_term","PDF หน้า 2 / ระยะชำระเบี้ย"),minEntryAge:known(30,"วัน","entry_age","PDF หน้า 2 / อายุรับประกัน"),maxEntryAge:known(70,"ปี","entry_age","PDF หน้า 2 / อายุรับประกัน")},highlights:["คุ้มครองถึงอายุ 99 ปี ชำระเบี้ย 20 ปี","ตัวอย่างหญิง 35 ปี ทุน 1 ล้านบาท เบี้ย 22,170 บาทต่อปี"]},
  {id:"life-02",category:"life",productId:"mtl-happy-return-99-7",name:"เมืองไทย แฮปปี้ รีเทิร์น 99/7",url:`${mtl}99-7`,price:quote("ต้องคำนวณตามอายุและทุน; ช่องทางออนไลน์ใช้ชื่อ Easy Protection 99/7"),cells:{coverageUntilAge:known(99,"ปี","until_age","ข้อมูลประกัน / คุ้มครองถึงอายุ"),coverageYears:absent("not_applicable","คุ้มครองถึงอายุ 99"),paymentYears:known(7,"ปี","payment_term","การชำระเบี้ย / ระยะชำระ"),minEntryAge:known(21,"ปี","entry_age","เงื่อนไข / อายุสมัครช่องทางออนไลน์",["ช่วงอายุของช่องทางออนไลน์ Easy Protection"]),maxEntryAge:known(70,"ปี","entry_age","เงื่อนไข / อายุสมัครช่องทางออนไลน์",["ช่วงอายุของช่องทางออนไลน์ Easy Protection"])},highlights:["คุ้มครองถึงอายุ 99 ปี ชำระเบี้ย 7 ปี","คืน 1% ของทุนตั้งแต่สิ้นปีกรมธรรม์ที่ 1 ถึงอายุ 98 ตามเงื่อนไข ไม่ใช่อัตราผลตอบแทนต่อเบี้ย"]},
  {id:"life-03",category:"life",productId:"mtl-smart-linked-pro-10-1",name:"เมืองไทย สมาร์ท ลิงค์ โปร 10/1 (Global)",url:"https://www.muangthai.co.th/en/savings-insurance/muangthai-smart-linked-pro-10-1-global//",price:quote("ราคาตามอายุและทุนประกัน","single"),cells:{coverageYears:known(10,"ปี","coverage_term","Plan overview / Coverage period"),coverageUntilAge:absent("not_applicable","Coverage period 10 years"),paymentYears:known(1,"ครั้ง","single_payment","Single premium payment"),minEntryAge:known(30,"วัน","entry_age","Plan overview / entry age"),maxEntryAge:known(80,"ปี","entry_age","Plan overview / entry age")},highlights:["ชำระเบี้ยครั้งเดียว คุ้มครอง 10 ปี","เงินปันผลเมื่อครบกำหนดขึ้นกับดัชนีและไม่รับประกัน; เอกสารไทยมีผลเหนือคำแปล"]},
  {id:"life-04",category:"life",productId:"mtl-smart-index-15-3",name:"เมืองไทย สมาร์ท อินเด็กซ์ 15/3 (Global)",url:"https://www.muangthai.co.th/en/savings-insurance/muangthai-smart-index-15-3-global-index-linked",price:price("example",19940,"year","ชายอายุ 35 ปี แผนออนไลน์ 1 ทุน 20,000 บาท; ช่องทางออนไลน์รับอายุ 20–70 ปี","ตารางแผน 1 / ตัวอย่างชาย 35 ปี / ชำระเบี้ยต่อปี",null,"https://online.muangthai.co.th/th/detail/global-index-15-3/plan-table"),cells:{sumAssured:known(20000,"บาท","initial_sum_assured","Starting premium / sum assured",["ทุนในตัวอย่างราคาเริ่มต้น"]),coverageYears:known(15,"ปี","coverage_term","Plan overview / Coverage period"),coverageUntilAge:absent("not_applicable","Coverage period 15 years"),paymentYears:known(3,"ปี","payment_term","Highlights / 3 years premium payment"),minEntryAge:known(30,"วัน","entry_age","Plan overview / entry age"),maxEntryAge:known(80,"ปี","entry_age","Plan overview / entry age")},highlights:["ชำระเบี้ย 3 ปี คุ้มครอง 15 ปี","เงินคืน 3% ของทุนทุก 2 ปีตามเงื่อนไข ไม่ใช่ดอกเบี้ยต่อปี"]},
  // life-05 was a category label, not a product identity; never reuse this ID.
  ...(["pa-small-size","pa-go","pa-cashback","pa-all-in-one"] as const).map((path,i):Seed=>({id:`accident-0${i+1}`,category:"accident",productId:`mtl-${path}`,name:["PA จิ๋วแต่แจ๋ว","PA Go","PA Cash Back ไม่เคลมมีคืน","PA All In One แผน S"][i],tierLabel:i<2?"แผน 1":"แผน S",url:`${mtl}${path}/plan-table`,price:price("example",[250,2199,3700,3855][i],"year",`ชายอายุ 35 ปี ${i<2?"แผน 1":"แผน S"}`,"ตารางแผน / ตัวอย่างชายอายุ 35 ปี / เบี้ยต่อปี"),cells:{deathBenefit:known([100000,500000,400000,300000][i],"บาท","per_accident","ตาราง แผน 1/S / เสียชีวิตจากอุบัติเหตุที่ไม่ใช่รถจักรยานยนต์",[`รถจักรยานยนต์ ${[50000,250000,200000,150000][i].toLocaleString("th-TH")} บาท; อุบัติเหตุสาธารณะมีเงื่อนไขและวงเงินแยก`]),disabilityBenefit:known([100000,500000,400000,300000][i],"บาท","per_accident","ตาราง แผน 1/S / ทุพพลภาพสิ้นเชิงถาวร",["เฉพาะกรณีไม่ใช่รถจักรยานยนต์; การสูญเสียอวัยวะจ่ายตามอัตราส่วนกรมธรรม์"]),medicalPerAccident:i===0?absent("not_covered","ตาราง แผน 1 / ค่ารักษาพยาบาลเครื่องหมายขีด; มีเฉพาะแผน 4/5"):known([0,50000,25000,45000][i],"บาท","per_accident","ตาราง แผน 1/S / ค่ารักษาพยาบาลสูงสุดต่อครั้ง"),...(i===0?{minEntryAge:known(20,"ปี","entry_age","ตาราง / อายุรับประกันแผน 1–3"),maxEntryAge:known(75,"ปี","entry_age","ตาราง / อายุรับประกันแผน 1–3")}:{} )},extraSources:i===2?[{url:`${mtl}${path}/plan-table`,locator:"เชิงอรรถ (1) / ผลประโยชน์ไม่เคลมทุก 3 ปี"}]:[],highlights:["วงเงินผูกกับแผนและตัวอย่างราคาเดียวกัน",i===2?"ต่ออายุครบ 3 ปีติดต่อกันและไม่เคยได้รับผลประโยชน์ในรอบนั้น จึงคืนเท่ากับเบี้ยรายปีของปีสุดท้ายในแต่ละรอบ 3 ปี":"ความคุ้มครองมอเตอร์ไซค์และอุบัติเหตุสาธารณะต่างจากอุบัติเหตุทั่วไป"]})),
  {id:"accident-05",category:"accident",productId:"axa-pa-save-dee",name:"AXA ประกันอุบัติเหตุ PA Save Dee",tierLabel:"แผน 1 ตามตาราง; อายุรับประกันรอยืนยัน",url:`${axa}accident-insurance/affordable-plan`,price:price("fixed",365,"year","ราคาในตารางทั้งสองแผน; ช่วงอายุรับประกันมีข้อมูลขัดกัน","ตาราง / เบี้ยรายปีรวมอากร","รวมอากร"),cells:{deathBenefit:known(300000,"บาท","per_accident","ตาราง แผน 1 / อ.บ.2",["แผน 2 วงเงิน 150,000 บาท; การถูกฆาตกรรมแผน 1 วงเงิน 150,000 บาท"]),disabilityBenefit:known(300000,"บาท","per_accident","ตาราง แผน 1 / อ.บ.2",["สูญเสียอวัยวะจ่ายตามอัตราส่วน; ไม่ใช่วงเงินทุกกรณี"]),minEntryAge:known(1,"ปี","entry_age","ตารางและเงื่อนไข / อายุเริ่มต้น"),maxEntryAge:conflict("ตารางแผน 1 อายุ 1–65 / แผน 2 อายุ 66–70 เทียบเงื่อนไขข้อ 1 อายุ 1–17",["ข้อมูลช่วงอายุขัดกัน ต้องยืนยันกับบริษัทก่อนสมัคร"])},highlights:["เบี้ยรายปีรวมอากร 365 บาทตามตาราง","ช่วงอายุหน้าเดียวกันขัดกัน จึงไม่รับรองอายุรับประกันสูงสุด"]},
  ...(["trip","year"] as const).map((period,i):Seed=>({id:`travel-0${i+1}`,category:"travel",productId:"axa-smart-traveller-choice",name:`AXA Smart Traveller’s Choice ${i?"รายปี":"รายเที่ยว"}`,subtype:"outbound",url:`${axa}travel-insurance/outbound`,price:price("starting",i?1564:135,period,"ยังไม่ระบุประเทศ วันเดินทาง อายุหรือ Basic/Advance/Max; ไม่ผูกราคาเริ่มต้นกับวงเงินสูงสุด","FAQ / ราคาเริ่มต้นรายเที่ยวและรายปี",null,`${axa}travel-insurance`),cells:{medicalLimit:missing(["ผลิตภัณฑ์มีวงเงินสูงสุด 5 ล้านบาท แต่ยังไม่เลือก Basic/Advance/Max"],"included","จุดเด่น / วงเงินสูงสุดของผลิตภัณฑ์"),baggageLimit:missing(["เป็นความคุ้มครองเสริม; 10,000 บาทในตารางเป็นต่อชิ้น/คู่ ไม่ใช่วงเงินรวม"],"optional","ตารางเปรียบเทียบ / สัมภาระต่อชิ้นหรือคู่"),cancellationLimit:missing(["ต้องเลือกแพ็กเสริมและแผนเพื่อทราบวงเงิน"],"optional","ข้อมูลทั่วไป / ความคุ้มครองเสริมการเดินทาง"),maxTripDays:i?missing(["รายปีจำกัด 90 หรือ 180 วันต่อเที่ยวตามแผนที่เลือก; ยังไม่ระบุแผน"],"included","FAQ / คุ้มครองสูงสุดกี่วันและการขยายระยะเวลา"):known(180,"วัน","per_trip","FAQ / แบบรายเที่ยว"),region:known("เดินทางออกจากประเทศไทย",null,"territory","ประเภทผลิตภัณฑ์ / Outbound",["ประเทศปลายทางและประเทศยกเว้นต้องตรวจตามกรมธรรม์"])},highlights:["เลือก Basic / Advance / Max และแพ็กเสริมก่อนระบุวงเงิน","วงเงินสูงสุดของผลิตภัณฑ์ไม่ใช่วงเงินของทุกราคาเริ่มต้น"]})),
  {id:"travel-03",category:"travel",productId:"axa-smart-thailand-traveller",name:"AXA Smart Thailand Traveller ในประเทศ",tierLabel:"แผน 3",subtype:"domestic",url:`${axa}travel-insurance/domestic`,price:quote("แผน 3; ราคาเริ่มต้นทั้งผลิตภัณฑ์ 46 บาทยังไม่ผูกกับแผน 3 หรือจำนวนวัน","trip"),cells:{medicalLimit:known(100000,"บาท","per_trip","ตาราง แผน 3 / การรักษาพยาบาลเนื่องจากการบาดเจ็บ",["อุบัติเหตุระหว่างการเดินทาง ไม่ใช่ค่ารักษาการเจ็บป่วยทั่วไป"]),cancellationLimit:known(20000,"บาท","per_trip","ตาราง แผน 3 / ยกเลิกก่อนเริ่มเดินทาง"),baggageLimit:known(20000,"บาท","per_trip","ตาราง แผน 3 / สูญหายหรือเสียหายสัมภาระ",["สูงสุด 10,000 บาทต่อชิ้น/คู่/ชุดเมื่อมีใบเสร็จ; ไม่มีใบเสร็จจำกัดตามเงื่อนไข"]),maxTripDays:known(31,"วัน","per_trip","เงื่อนไขข้อ 2"),region:known("ประเทศไทย",null,"territory","เงื่อนไขข้อ 4",["ยกเว้นปัตตานี ยะลา และนราธิวาส"])},highlights:["แผน 3 ค่ารักษาอุบัติเหตุสูงสุด 100,000 บาท","คุ้มครองไม่เกิน 31 วันต่อเที่ยว; ต้องขอราคาแผน 3"]},
  {id:"travel-04",category:"travel",productId:"axa-sawasdee-thailand",name:"AXA Inbound Travel Insurance",subtype:"inbound",url:`${axa}travel-insurance/inbound`,price:price("starting",999,"trip","ราคาเริ่มต้นของผลิตภัณฑ์; ระยะ 7–180 วันและตัวเลือกแผนต้องขอราคา","หัวตาราง / เบี้ยเริ่มต้น 999 บาท"),cells:{medicalLimit:known(750000,"บาท","per_trip","ตาราง แผน 1 และ 2 / รักษาบาดเจ็บและเจ็บป่วย",["คุ้มครองตามความจำเป็นทางการแพทย์"]),baggageLimit:missing(["แผน 1 ไม่คุ้มครอง; แผน 2 วงเงิน 30,000 บาท ยังไม่เลือกแผน"],"unknown","ตาราง / สัมภาระ"),maxTripDays:known(180,"วัน","per_trip","ข้อมูลทั่วไป / เลือกระยะประกันได้ถึง 180 วัน"),region:known("ประเทศไทย",null,"territory","เงื่อนไข / บุคคลต่างชาติที่อยู่นอกไทยขณะซื้อ",["สำหรับผู้ไม่ถือสัญชาติไทยและต้องอยู่นอกประเทศไทยขณะซื้อ"] )},highlights:["ค่ารักษาบาดเจ็บและเจ็บป่วย 750,000 บาททั้งแผน 1/2","เป็นรายเที่ยว ผู้เอาประกันต้องอยู่นอกประเทศไทยขณะซื้อ"]},
  {id:"travel-05",category:"travel",productId:"axa-smart-traveller-choice",name:"AXA Smart Traveller’s Choice สำหรับเชงเก้น",subtype:"outbound",url:`${axa}travel-insurance/outbound`,price:price("starting",165,"trip","สถานการณ์ยื่นวีซ่าเชงเก้น ไม่ใช่ผลิตภัณฑ์หรือแผนใหม่; ยังไม่ระบุวันและตัวเลือก","ตารางเปรียบเทียบ / ราคาเริ่มต้นสำหรับ Schengen"),cells:{medicalLimit:missing(["ทุกแผนรองรับการยื่นวีซ่าตามเงื่อนไข; ยังไม่เลือก Basic/Advance/Max"],"included","จุดเด่น / ใช้ยื่นวีซ่าเชงเก้นได้ทุกแผน"),baggageLimit:missing(["แพ็กเสริม; ต้องเลือกแผนก่อนทราบวงเงินรวม"],"optional"),cancellationLimit:missing(["แพ็กเสริมการเดินทาง"],"optional"),maxTripDays:known(180,"วัน","per_trip","FAQ / แบบรายเที่ยว"),region:known("เชงเก้น",null,"territory","ตารางเปรียบเทียบ / ราคาเพื่อยื่นวีซ่าเชงเก้น")},highlights:["สถานการณ์เชงเก้นของ Smart Traveller’s Choice ไม่ใช่ผลิตภัณฑ์แยก","เลือกแผนและวันเดินทางก่อนเทียบราคาและวงเงิน"]},
  {id:"property-01",category:"property",productId:"axa-sabuydee-my-home",name:"AXA Sabuydee My Home บ้านและคอนโด",url:`${axa}home-insurance/home-plan`,price:quote("ราคาเริ่มต้นหน้าไทย 1,176 บาท แต่หน้าอังกฤษบ้าน 1,100 / คอนโด 1,200 บาท ข้อมูลขัดกัน ต้องขอใบเสนอราคา"),extraSources:[{url:"https://www.axa.co.th/en/personal/home-insurance/home-plan",locator:"Product information / starting house and condo premiums"}],cells:{buildingLimit:missing(["เลือกทุนอาคารสูงสุด 30 ล้านบาท; มี average clause เมื่อทุนต่ำกว่ามูลค่า"],"optional","ตาราง / 1.1 สิ่งปลูกสร้าง"),contentsLimit:missing(["5–20% ของทุนอาคาร ขั้นต่ำ 200,000 สูงสุด 2 ล้านบาท; first loss; ต้องเลือกทุน"],"optional","ตาราง / 1.2 ทรัพย์สิน"),sharedNaturalPerilsLimit:known(20000,"บาท","shared_cap","ตาราง / 2 กลุ่มภัยธรรมชาติ",["ลมพายุ น้ำท่วม แผ่นดินไหว ลูกเห็บใช้วงเงินเดียวกันรวมทุกภัย"]),includedPerils:known("ลมพายุ น้ำท่วม แผ่นดินไหว ลูกเห็บ",null,"shared_cap","ตาราง / 2.1–2.4 กลุ่มภัยธรรมชาติ"),deductible:known(0,"บาท","per_claim","จุดเด่นและ FAQ / ไม่มีความรับผิดส่วนแรก")},highlights:["เลือกทุนอาคารและทรัพย์สินตามใบเสนอราคา","ภัยธรรมชาติใช้วงเงินร่วม 20,000 บาท; ความรับผิดส่วนบุคคลเป็นส่วนของแพ็ก ไม่ขายเป็นห้าแผนแยก"]},
];

// Core fields absent from the first catalog draft; each source applies to this exact identity.
const life10Wording="https://cdn-ols.muangthai.co.th/bo/product-information/MTL-Smart-Pro-Link-Insurance-10_1-18052023-010350.pdf";
const life15Table="https://online.muangthai.co.th/th/detail/global-index-15-3/plan-table";
const coreCells:Record<string,Record<string,CellInput>>={
  "life-01":{
    lifeType:known("ตลอดชีพ คุ้มครองถึงอายุ 99 ปี",null,"product_type","PDF หน้า 2 / ผลประโยชน์และระยะคุ้มครอง"),
    deathFormula:known("จำนวนสูงสุดระหว่าง 100% ของทุนเริ่มสัญญา มูลค่าเวนคืน และเบี้ยสะสมที่ชำระแล้ว",null,"death_formula","PDF หน้า 2 / หมายเหตุ (3)",["ใช้เมื่อเสียชีวิตระหว่างสัญญาที่มีผล; ไม่ใช่ 101% ของเบี้ย"]),
    maturityFormula:known("100% ของจำนวนเงินเอาประกันภัย ณ วันเริ่มสัญญา",null,"maturity_formula","PDF หน้า 2 / เงินครบสัญญาและหมายเหตุ (2)",["มีชีวิตอยู่ครบอายุ 99 ปี"]),
    guaranteedCashback:absent("not_applicable","PDF หน้า 2 / แผนภาพผลประโยชน์มีชีวิตและครบสัญญา",["แบบนี้แสดงผลประโยชน์ครบสัญญา ไม่ใช่เงินคืนรายปี"]),
    nonGuaranteedBenefit:missing(["ไม่พบผลประโยชน์ไม่รับประกันที่ระบุในเอกสารที่ตรวจ"]),
    paymentFrequency:known("รายปีในตัวอย่างเบี้ย",null,"payment_frequency","PDF หน้า 2 / ตัวอย่างหญิง 35 ปี",["ไม่ยืนยันรอบอื่นจากตัวอย่างนี้"]),
  },
  "life-02":{
    lifeType:known("ตลอดชีพพร้อมเงินคืน คุ้มครองถึงอายุ 99 ปี",null,"product_type","ข้อมูลประกัน / ชื่อแบบและระยะคุ้มครอง"),
    deathFormula:{...known("จำนวนสูงสุดระหว่าง 100% ของทุนเริ่มสัญญา มูลค่าเวนคืน และ 101% ของเบี้ยที่ชำระแล้ว",null,"death_formula","ตารางแผน / เชิงอรรถ (3)",["ปีกรมธรรม์ที่ 1 จนถึงครบอายุ 99 ปี ขณะกรมธรรม์มีผล"]),url:`${mtl}99-7/plan-table`},
    maturityFormula:{...known("จำนวนสูงสุดระหว่าง 100% ของทุนเริ่มสัญญา กับ 101% ของเบี้ยที่ชำระแล้ว",null,"maturity_formula","ตารางแผน / เชิงอรรถ (2)",["มีชีวิตอยู่ครบกำหนดสัญญา"]),url:`${mtl}99-7/plan-table`},
    guaranteedCashback:{...known("1% ของทุนเริ่มสัญญา ณ สิ้นปีกรมธรรม์ทุกปี ตั้งแต่ปีที่ 1 จนถึงอายุ 98 ปี",null,"initial_sum_assured_percent","ตารางแผน / มีชีวิตระหว่างสัญญาและเชิงอรรถ (1)",["จ่ายเมื่อมีชีวิตอยู่; ไม่ใช่อัตราผลตอบแทนต่อเบี้ย"]),url:`${mtl}99-7/plan-table`},
    nonGuaranteedBenefit:missing(["ยังไม่พบผลประโยชน์ไม่รับประกันที่ระบุ"]),
    paymentFrequency:{...known("รายปีตามตารางแผน",null,"payment_frequency","ตารางแผน / ชำระเบี้ยต่อปี",["ตารางนี้ไม่ยืนยันราคาในรอบชำระอื่น"]),url:`${mtl}99-7/plan-table`},
  },
  "life-03":{
    lifeType:known("สะสมทรัพย์แบบมีส่วนร่วมในเงินปันผลตามดัชนี",null,"product_type","ชื่อผลิตภัณฑ์ / Index-Linked"),
    deathFormula:{...known("จำนวนสูงสุดระหว่าง 105% ของทุนเริ่มสัญญา กับมูลค่าเวนคืนขณะนั้น",null,"death_formula","PDF หน้า 1 / ข้อ 1 ตารางปีกรมธรรม์ 1–10",["กรมธรรม์ต้องมีผลบังคับ"]),url:life10Wording},
    maturityFormula:{...known("101% ของทุนเริ่มสัญญา",null,"maturity_formula","PDF หน้า 1 / ข้อ 2(2)",["มีชีวิตอยู่ครบปีที่ 10; เงินปันผลถ้ามีแสดงแยก"]),url:life10Wording},
    guaranteedCashback:{...known("1% ของทุนเริ่มสัญญา ณ สิ้นปีกรมธรรม์ที่ 1–9",null,"initial_sum_assured_percent","PDF หน้า 1 / ข้อ 2(1)",["จ่ายเมื่อมีชีวิตอยู่; ไม่ใช่ผลตอบแทนต่อปีจากเงินลงทุน"]),url:life10Wording},
    nonGuaranteedBenefit:{...known("อาจมีเงินปันผลตามดัชนีเมื่อครบปีที่ 10 ไม่รับประกันจำนวน",null,"non_guaranteed_dividend","PDF หน้า 1 / ข้อ 2(2)",["ต้องมีชีวิตอยู่ครบสัญญา; ไม่คำนวณหรือรับรองเงินปันผลล่วงหน้า"]),url:life10Wording},
    paymentFrequency:{...known("ชำระครั้งเดียว",null,"payment_frequency","PDF หน้า 1 / ระยะเวลาชำระเบี้ย"),url:life10Wording},
  },
  "life-04":{
    lifeType:known("สะสมทรัพย์แบบมีส่วนร่วมในเงินปันผลตามดัชนี",null,"product_type","ชื่อผลิตภัณฑ์ / Index-Linked"),
    deathFormula:{...known("ปีที่ 1: 100% ปีที่ 2: 200% ปีที่ 3–15: 300% ของทุนเริ่มสัญญา; เทียบกับมูลค่าเวนคืนและ 101% ของเบี้ยที่ชำระแล้ว จ่ายจำนวนสูงสุด",null,"death_formula","ตารางแผน / ปีกรมธรรม์ที่ 1–15 และเชิงอรรถ (4)"),url:life15Table},
    maturityFormula:{...known("จำนวนสูงสุดระหว่าง 310% ของทุนเริ่มสัญญา กับ 101% ของเบี้ยที่ชำระแล้ว",null,"maturity_formula","ตารางแผน / เชิงอรรถ (3)",["มีชีวิตอยู่ครบปีที่ 15; ไม่รวมเงินปันผลที่ไม่รับประกัน"]),url:life15Table},
    guaranteedCashback:{...known("3% ของทุนเริ่มสัญญา ณ สิ้นปีกรมธรรม์ที่ 2, 4, 6, 8, 10, 12 และ 14",null,"initial_sum_assured_percent","ตารางแผน / มีชีวิตอยู่และเชิงอรรถ (1)",["ไม่ใช่ดอกเบี้ย 3% ต่อปีหรือเปอร์เซ็นต์ของเบี้ย"]),url:life15Table},
    nonGuaranteedBenefit:{...known("อาจมีเงินปันผลตามดัชนีเมื่อครบปีที่ 15 ไม่รับประกันจำนวน",null,"non_guaranteed_dividend","ตารางแผน / เชิงอรรถ (2),(5)",["จ่ายเฉพาะมีชีวิตอยู่ครบสัญญา"]),url:life15Table},
    paymentFrequency:{...known("รายปี",null,"payment_frequency","ตารางแผน / ชำระเบี้ยต่อปี"),url:life15Table},
  },
  "property-01":{
    fireCoverage:known("ไฟไหม้ ฟ้าผ่า ระเบิด ยานพาหนะ/สัตว์พาหนะเฉี่ยวชน อากาศยาน และภัยจากน้ำที่ไม่ใช่น้ำท่วม",null,"selected_property_sum","ตารางข้อ 1 / อัคคีภัย",["วงเงินขึ้นกับทุนอาคารและทรัพย์สินที่เลือก; น้ำท่วมอยู่ในกลุ่มภัยธรรมชาติที่ใช้วงเงินร่วม"]),
    burglaryCoverage:missing(["ยังไม่มีหลักฐานยืนยันความคุ้มครองโจรกรรมเฉพาะแพ็กนี้; ไม่ถือว่าไม่คุ้มครองจากการไม่ปรากฏในตารางย่อ"],"unknown","ตารางสรุปความคุ้มครอง / ต้องตรวจ wording เพิ่มเติม"),
    bundledLiability:known("10% ของจำนวนเงินเอาประกันภัยทั้งหมด ขั้นต่ำ 500,000 บาท",null,"total_sum_assured_percent","ตาราง / ข้อ 4 ความรับผิดต่อบุคคลภายนอก",["เป็นส่วนของแพ็กบ้าน ไม่ใช่ราคา/ผลิตภัณฑ์ความรับผิดแยกขาย; ทุนยังไม่เลือก จึงไม่สรุปเป็นวงเงินเฉพาะบุคคล"]),
    occupancy:known("เจ้าของอยู่อาศัยเอง ผู้เช่า หรือเจ้าของปล่อยเช่าระยะยาวเพื่ออยู่อาศัย",null,"residential_occupancy","ข้อมูลผลิตภัณฑ์และเงื่อนไขข้อ 2",["ไม่รับการเช่ารายวันหรือรายสัปดาห์; ไม่ใช้แทนประกันอาคารพาณิชย์"]),
    construction:known("ใบเสนอราคาออนไลน์รับอาคารคอนกรีตและเหล็ก ผนังคอนกรีตหรืออิฐมากกว่า 80%",null,"construction","เงื่อนไขข้อ 1"),
    valuation:known("มูลค่าทดแทนใหม่; อาคารอาจเฉลี่ยค่าสินไหมเมื่อทุนต่ำกว่ามูลค่า ส่วนทรัพย์สินภายในใช้ First Loss",null,"replacement_cost","เงื่อนไขข้อ 3–4 และ FAQ ประกันต่ำกว่ามูลค่า",["First Loss ไม่ใช่วงเงินไม่จำกัด ยังจำกัดตามทุนที่เลือก"]),
    locationRestrictions:known("ไม่รับยะลา นราธิวาส ปัตตานี และจะนะ นาทวี เทพา สะบ้าย้อยในสงขลา",null,"excluded_locations","เงื่อนไขข้อ 5",["ต้นทางสะกดอำเภอเทพ แต่หมายถึงพื้นที่ตามกรมธรรม์; ต้องยืนยันที่ตั้งก่อนเสนอราคา"]),
  },
};

for (const seed of seeds) {
  if (seed.category === "health") {
    const value=seed.id==="health-01", essential=seed.id==="health-02", axaHealth=value||essential;
    coreCells[seed.id]={
      opdPerVisit:essential?known(3000,"บาท","per_visit","ตาราง / ตัวเลือก OPD ต่อครั้ง",["เลือกเพิ่ม; ไม่เกิน 1 ครั้งต่อวันและ 30 ครั้งต่อปี; เป็นทางเลือกแทน OPD รายปี 50,000 บาท ไม่บวกสองแบบเข้าด้วยกัน"],"optional"):missing([axaHealth?"OPD ต่อเนื่องจาก IPD/อุบัติเหตุมีเงื่อนไขเฉพาะ ไม่ใช่วงเงิน OPD ทั่วไป":"ไม่จำกัดวงเงินต่อครั้งแต่รวมไม่เกินวงเงิน OPD รายปี; ไม่ตีความเป็นวงเงินรวมไม่จำกัด"],"included",axaHealth?"ตาราง / OPD ต่อเนื่องและอุบัติเหตุ":"เชิงอรรถ (2) / OPD ต่อครั้งและรายปี"),
      roomBasis:known(axaHealth?"ห้องเดี่ยวมาตรฐานที่ว่างและมีอัตราต่ำสุด ภายใต้ความจำเป็นทางการแพทย์":"ห้องเดี่ยวมาตรฐานตามจริง ภายในวงเงิน IPD ที่เลือก",null,"room_cost_basis",axaHealth?"เงื่อนไข / คำนิยามค่าห้องผู้ป่วยธรรมดา":"หัวข้อค่าห้องเดี่ยวมาตรฐานและหมายเหตุ 3",["ไม่ใช่เงินชดเชยรายวัน"]),
      icuPerDay:axaHealth?known(value?5000:24000,"บาท","per_day",`ตาราง แผน ${value?1:4} / ค่าห้องผู้ป่วยวิกฤต`):missing(["ไม่แปลงห้องตามจริง/วงเงินรวมเป็นวงเงินเงินสดต่อวัน"],"included","หมายเหตุ 3 / ICU"),
      icuMaxDays:axaHealth?missing(["ยังไม่ยืนยันจำนวนวันเฉพาะ ICU"]):known(60,"วัน","per_admission","หมายเหตุ 3 / ICU สูงสุดต่อครั้ง",["นับรวมกับค่าห้อง/อาหาร/พยาบาลไม่เกิน 180 วันต่อครั้ง"]),
      roomMaxDays:axaHealth?missing(["ยังไม่ยืนยันจำนวนวันเฉพาะค่าห้อง"]):known(180,"วัน","per_admission","หมายเหตุ 3 / ค่าห้องรวมสูงสุด"),
      opdVisitsPerDay:essential?known(1,"ครั้ง","per_day","ตาราง / ความคุ้มครองเสริม OPD ต่อครั้ง",["เฉพาะตัวเลือก 3,000 บาทต่อครั้ง สูงสุด 30 ครั้งต่อปี; ไม่เหมารวมตัวเลือก OPD รายปี"],"optional"):value?missing(["OPD นี้ขึ้นกับเหตุและการรักษาต่อเนื่อง ไม่ใช่ OPD ทั่วไป"]):known(2,"ครั้ง","per_day","หมายเหตุ 4 / OPD เหมาจ่าย"),
      copay:missing(["ไม่มีหลักฐานรุ่น/เงื่อนไขร่วมจ่ายเฉพาะรายที่ยืนยันได้; ไม่ถือว่า 0% และไม่ใช้ค่า deductible แทน"],"unknown","เงื่อนไขการรับประกัน / ต้องตรวจกรมธรรม์และการต่ออายุ"),
      minEntryAge:known(value?13:essential?15:20,essential?"วัน":"ปี","entry_age",axaHealth?"เงื่อนไขข้อ 1 / อายุเริ่มสมัคร":"เงื่อนไขการรับประกัน / อายุที่สมัครได้"),
      maxEntryAge:known(value?60:essential?65:70,"ปี","entry_age",axaHealth?"เงื่อนไขข้อ 1 / อายุสูงสุด":"เงื่อนไขการรับประกัน / อายุที่สมัครได้"),
      renewalAge:axaHealth?known(99,"ปี","renewal_age","เงื่อนไขข้อ 2 / อายุที่ต่ออายุได้",["เบี้ยอาจปรับตามอายุ; ไม่รับประกันเบี้ยคงที่"]):missing(["หน้าแผนระบุคุ้มครองถึง 99 ปี แต่สัญญาเพิ่มเติมต่อปีและขึ้นกับกรมธรรม์หลัก/อายุสูงสุดที่บริษัทรับ; ไม่รับรองต่ออายุทุกเงื่อนไขถึง 99"],"unknown","เงื่อนไขคุ้มครองถึงอายุ และหมายเหตุ 8"),
      eligibilityConditions:known(value?"อายุ 13–20 ปีผู้ปกครองซื้อให้บุตรได้โดยไม่ต้องพ่วงผู้ปกครอง; ตอบคำถามสุขภาพ 3 ข้อ":essential?"เด็กต่ำกว่า 18 ปีสมัครพร้อมผู้ปกครอง; พิจารณาอาชีพตามเงื่อนไขบริษัท":"ช่องทางนี้เฉพาะสัญชาติไทย; การแถลงสุขภาพมีผลต่อการพิจารณารับประกัน",null,"underwriting",axaHealth?"เงื่อนไขข้อ 1 และ FAQ/เงื่อนไขอาชีพ":"หมายเหตุ / การแถลงสุขภาพและสัญชาติไทย",["อายุเข้าเกณฑ์ไม่ใช่การรับรองอนุมัติ"]),
    };
  }
  if (seed.category === "accident") {
    const i=Number(seed.id.slice(-2))-1, all=i===3;
    coreCells[seed.id]={
      motorcycleBenefit:i<4?known([50000,250000,200000,150000][i],"บาท","per_accident","ตาราง แผน 1/S / ขับขี่หรือโดยสารรถจักรยานยนต์",["สูงสุดสำหรับกรณีเสียชีวิต/ทุพพลภาพ; การสูญเสียอวัยวะจ่ายตามสัดส่วน"]):missing(["ไม่พบวงเงินรถจักรยานยนต์แยกของแผน 1 ที่ยืนยันได้"]),
      homicideBenefit:known([100000,500000,400000,300000,150000][i],"บาท","per_accident",i===4?"ตาราง แผน 1 / ถูกฆาตกรรมหรือทำร้าย":"ตาราง แผน 1/S / ถูกฆาตกรรมหรือทำร้าย",["วงเงินสูงสุดตามเหตุ ไม่บวกกับวงเงินอุบัติเหตุทั่วไปสำหรับเหตุเดียวกัน"]),
      publicAccidentBenefit:i<4?known([200000,500000,800000,600000][i],"บาท","per_accident","ตาราง แผน 1/S / อุบัติเหตุสาธารณะ",["ไม่ใช่อุบัติเหตุทุกประเภท; นิยามเหตุ/พาหนะต้องตามกรมธรรม์; ไม่บวกซ้ำกับวงเงินทั่วไป"]):missing(["ไม่พบวงเงินอุบัติเหตุสาธารณะแยกที่ยืนยันได้"]),
      dailyAllowance:all?known(500,"บาท","per_day","ตาราง แผน S / IPD จากเจ็บป่วยหรืออุบัติเหตุและเชิงอรรถ (4)",["สูงสุด 365 วันต่อครั้ง; โรค/บาดเจ็บเดิมและภาวะแทรกซ้อนภายใน 90 วันนับวงเงินเดิม","ICU/อุบัติเหตุ/รักษาต่างประเทศ 1,000 บาทต่อวัน สูงสุด 45 วัน เป็นทางเลือกกรณีใดกรณีหนึ่งตามตาราง ไม่บวกกับ 500 บาท","เป็นสัญญาเพิ่มเติม HIP ในแพ็กชีวิตและ PA; ไม่ใช่ค่ารักษาจ่ายตามบิล"]):missing(["ไม่มีอัตราชดเชยรายวันเฉพาะแผนที่ยืนยัน; ไม่ตีความเป็นไม่คุ้มครอง"]),
      dailyMaxDays:all?known(365,"วัน","per_admission","ตาราง / ผลประโยชน์รายวันสูงสุด",["กรณีอัตราพิเศษสูงสุด 45 วัน; เหตุเดิมนับตามเงื่อนไข 90 วัน"]):missing(),
      occupationClass:i===1||i===2?known(i===1?"กลุ่มอาชีพ 1, 2":"กลุ่มอาชีพ 1, 2, 3",null,"occupation_class","หมายเหตุ / กลุ่มอาชีพที่รับประกัน",["อาชีพเสี่ยงที่ระบุในข้อยกเว้นไม่รับ; ต้องตรวจหน้าที่งานจริง"]):missing(["ต้องยืนยันลักษณะงาน ไม่อนุมานรับทุกอาชีพจากข้อความการตลาด"]),
    };
  }
  if (seed.category === "motor") {
    const i=Number(seed.id.slice(-2))-1, compulsory=i===4;
    const vehicleSum=()=>missing([i<2?"ชนแบบมี/ไม่มีคู่กรณี วงเงินตามทุนรถที่เลือก":"รถชนรถตามเงื่อนไข วงเงินตามทุนรถที่เลือก"],"included","ตาราง / ความเสียหายต่อรถยนต์");
    const noOwnVehicle=()=>absent("not_covered","พ.ร.บ. / คุ้มครองผู้ประสบภัยทางร่างกาย ไม่ใช่ความเสียหายต่อตัวรถ");
    coreCells[seed.id]={
      collisionLimit:compulsory?noOwnVehicle():vehicleSum(),
      theftLimit:compulsory?noOwnVehicle():i===3?absent("not_covered","ตาราง ชั้น 3+ / รถสูญหายไม่คุ้มครอง"):missing(["วงเงินตามทุนรถ ยังไม่ระบุรถหรือทุน"],"included","ตาราง / รถสูญหาย"),
      fireLimit:compulsory?noOwnVehicle():i===3?absent("not_covered","ตาราง ชั้น 3+ / ไฟไหม้ไม่คุ้มครอง"):missing(["วงเงินตามทุนรถ ยังไม่ระบุรถหรือทุน"],"included","ตาราง / รถไฟไหม้"),
      floodLimit:compulsory?noOwnVehicle():missing([i<2?"วงเงินตามทุนรถที่เลือก":"แพ็กภัยธรรมชาติเป็นตัวเลือกเพิ่ม วงเงินแพ็ก 100,000 บาท; ยังไม่เลือก ไม่ใช่วงเงินน้ำท่วมแยกที่นำไปบวกทุกภัยได้"],i<2?"included":"optional","ตาราง / ภัยธรรมชาติ"),
      thirdPartyBodilyPerPerson:compulsory?absent("not_applicable","พ.ร.บ. / ช่องนี้เป็นภาคสมัครใจส่วนเกิน พ.ร.บ."):i===0?missing(["ส่วนเกิน พ.ร.บ. รถทั่วไป 500,000 บาท; BMW/Mercedes 1,000,000 บาท; ยังไม่ระบุรถ"],"included","ตาราง / ชีวิตร่างกายอนามัยต่อคน"):known(i===1?1000000:500000,"บาท","per_person","ตาราง / ความรับผิดต่อบุคคลภายนอก ชีวิตร่างกายต่อคน",["เฉพาะส่วนเกิน พ.ร.บ. ไม่ใช่ยอดรวมกับภาคบังคับ"]),
      thirdPartyBodilyPerEvent:compulsory?absent("not_applicable","พ.ร.บ. / ช่องนี้เป็นภาคสมัครใจส่วนเกิน พ.ร.บ."):known(i===0?20000000:10000000,"บาท","per_occurrence","ตาราง / ความรับผิดต่อบุคคลภายนอก ชีวิตร่างกายต่อครั้ง",["เฉพาะส่วนเกิน พ.ร.บ.; ขึ้นกับวงเงินต่อคนด้วย"]),
    };
  }
  if (seed.category === "travel") {
    const domestic=seed.id==="travel-03", inbound=seed.id==="travel-04", annual=seed.id==="travel-02";
    const delayNote=inbound?"ยังไม่เลือกแผน: แผน 1 ไม่คุ้มครอง; แผน 2 จ่าย 1,000 บาททุก 6 ชั่วโมง สูงสุด 20,000 บาทตามเงื่อนไข":"ต้องเลือกแพ็กเสริมการเดินทางและ tier; เกณฑ์ล่าช้า 6 ชั่วโมงติดต่อกันและจ่ายตามช่วง 6 ชั่วโมง วงเงินตามกรมธรรม์";
    coreCells[seed.id]={
      policyDuration:annual?known(1,"ปี","policy_term","FAQ / แบบรายปี",["ไม่ใช่ระยะอยู่ต่างประเทศต่อเนื่อง; แต่ละเที่ยวจำกัด 90 หรือ 180 วันตาม tier"]):missing([`ยังไม่ระบุวันเดินทาง; สูงสุด ${domestic?31:180} วันตามประเภท`],"unknown",domestic?"เงื่อนไขข้อ 2 / ระยะคุ้มครอง":"ข้อมูลทั่วไป/FAQ / ระยะคุ้มครอง"),
      evacuationLimit:domestic?known(1000000,"บาท","per_trip","ตาราง แผน 3 / เคลื่อนย้ายเพื่อรักษาฉุกเฉิน",["เคลื่อนย้ายผู้ป่วย/ส่งกลับเพื่อรักษาภายในประเทศไทย; วงเงินตามตารางและเงื่อนไขทริป"]):missing([inbound?"ตารางย่อไม่ยืนยันผลประโยชน์นี้ ไม่ถือว่าไม่คุ้มครอง":"มีความคุ้มครองพื้นฐาน แต่ยังไม่ระบุ Basic/Advance/Max เพื่อยืนยันวงเงิน"],inbound?"unknown":"included",inbound?"ตารางความคุ้มครอง / ไม่พบวงเงินยืนยัน":"ข้อมูลผลิตภัณฑ์ / เคลื่อนย้ายฉุกเฉิน"),
      repatriationLimit:domestic?known(1000000,"บาท","per_trip","ตาราง แผน 3 / ส่งศพหรืออัฐิกลับภูมิลำเนา",["เป็นการส่งศพ/อัฐิ ไม่ใช่วงเงินเคลื่อนย้ายผู้ป่วยที่นำไปบวกกรณีเดียวกัน"]):missing([inbound?"ไม่มีวงเงินส่งศพ/อัฐิยืนยันในตารางที่ตรวจ":"รวมในความคุ้มครองพื้นฐาน แต่ยังไม่เลือก tier เพื่อยืนยันวงเงิน"],inbound?"unknown":"included",inbound?"ตารางความคุ้มครอง":"ข้อมูลผลิตภัณฑ์ / ส่งศพหรืออัฐิกลับ"),
      interruptionLimit:domestic?known(20000,"บาท","per_trip","ตาราง แผน 3 / ลดจำนวนวันเดินทาง",["เหตุที่เข้าเงื่อนไขต้องตรวจกรมธรรม์"]):missing([inbound?"ตารางที่ตรวจไม่ยืนยันผลประโยชน์นี้":"ต้องเลือกแพ็กเสริมและ tier เพื่อทราบวงเงิน"],inbound?"unknown":"optional","ตาราง/FAQ / การลดจำนวนวันเดินทาง"),
      delayHours:domestic?known(4,"ชั่วโมง","delay_interval","ตาราง แผน 3 / เดินทางล่าช้า",["เหตุล่าช้าต้องเข้าเงื่อนไขกรมธรรม์"]):missing([delayNote],inbound?"unknown":"optional",inbound?"ตาราง / เดินทางล่าช้า แผน 1–2":"FAQ / เดินทางล่าช้า"),
      delayPayment:domestic?known(1000,"บาท","per_delay_interval","ตาราง แผน 3 / เดินทางล่าช้า",["ต่อทุก 4 ชั่วโมงที่เข้าเงื่อนไข; ไม่ใช่ต่อชั่วโมง"]):missing([delayNote],inbound?"unknown":"optional","ตาราง/FAQ / เดินทางล่าช้า"),
      delayLimit:domestic?known(10000,"บาท","per_trip","ตาราง แผน 3 / เดินทางล่าช้าสูงสุด"):missing([delayNote],inbound?"unknown":"optional","ตาราง/FAQ / เดินทางล่าช้า"),
      delayTrigger:domestic?missing(["ตารางบอกอัตราและช่วงเวลา แต่ยังไม่มีหลักฐานสาเหตุที่ครอบคลุมครบ; ไม่ใช้เงื่อนไข outbound แทน"],"unknown","ตาราง แผน 3 / ล่าช้า"):inbound?missing(["แผน 2 มีเงื่อนไขเที่ยวบินภายในไทยหรือออกจากไทย; ต้องตรวจสาเหตุในกรมธรรม์"],"unknown","ตาราง / ล่าช้า แผน 2"):known("สภาพอากาศผิดปกติ พาหนะขัดข้อง การนัดหยุดงาน ความไม่สงบที่ไม่คาดคิด ภัยธรรมชาติ หรือปิดน่านฟ้า/สนามบิน",null,"delay_trigger","FAQ / สาเหตุเดินทางล่าช้า",["ต้องเลือกแพ็กเสริม; ขอบเขตและสาเหตุต้องตรงกรมธรรม์ ไม่ใช่ทุกความล่าช้า"],"optional"),
    };
  }
}

function buildPlan(seed:Seed): Plan {
  const cells={...seed.cells,...coreCells[seed.id]};
  if(seed.id==="property-01")cells.floodLimit={...cells.sharedNaturalPerilsLimit,conditions:[...cells.sharedNaturalPerilsLimit.conditions,"น้ำท่วมใช้เพดานรวมกลุ่มภัยธรรมชาติ ไม่ใช่เพิ่มจากกลุ่มอีก 20,000 บาท"]};
  if(seed.category==="motor"&&seed.subtype==="compulsory")cells.voluntaryMedicalPerPerson=absent("not_applicable","พ.ร.บ. ภาคบังคับ ไม่ใช่ความคุ้มครองเอกสารแนบท้ายภาคสมัครใจ");
  const insurer=seed.insurer??(seed.productId.startsWith("axa-")?"AXA ประกันภัย":"เมืองไทยประกันชีวิต");
  const sources:SourceEvidence[]=[];
  const evidence=(key:string,locator:string,url=seed.url)=>{const id=`${seed.id}:${key}`;sources.push({id,url,publisher:url.includes("bangkokbank.com")?"ธนาคารกรุงเทพ — ช่องทางจำหน่ายกรุงเทพประกันชีวิต":insurer,title:seed.name,locator,publishedAt:url===motorNewsUrl?"2025-07-04":null,effectiveAt:null,checkedAt});return id;};
  const identity=evidence("identity","ชื่อผลิตภัณฑ์และส่วนข้อมูลทั่วไป");
  if(seed.eligibility)evidence("eligibility",seed.eligibilitySource?.locator??"เงื่อนไขการรับประกัน / อายุและคุณสมบัติผู้สมัคร",seed.eligibilitySource?.url??seed.url);
  const extraIds=(seed.extraSources??[]).map((s,i)=>evidence(`extra-${i}`,s.locator,s.url));
  const {locator,url,...priceValues}=seed.price;
  const canonicalPrice:Price={...priceValues,sourceIds:[evidence("price",locator,url),...extraIds]};
  const coverageCells=Object.fromEntries(categoryFields[seed.category].map(field=>{
    const cell=cells[field.key]??missing();const {locator,url,...values}=cell;
    return [field.key,{...values,sourceIds:cell.status==="unknown"&&!cells[field.key]?[]:[evidence(field.key,locator,url)]}];
  })) as Record<string,CoverageCell>;
  return {id:seed.id,category:seed.category,...(seed.subtype?{subtype:seed.subtype}:{}),productId:seed.productId,tierLabel:seed.tierLabel??null,edition:seed.edition??null,name:seed.name,insurer,price:canonicalPrice,coverageCells,sources,
    premiumTHB:canonicalPrice.amountTHB,premiumPeriod:canonicalPrice.period,premiumNote:canonicalPrice.scenario??(canonicalPrice.kind==="quote_only"?"ขอใบเสนอราคา":canonicalPrice.kind==="example"?"เบี้ยตัวอย่าง":canonicalPrice.kind==="starting"?"เบี้ยเริ่มต้น":"เบี้ยตามตาราง"),
    image:planImages[seed.id]?.src??seed.image??"/images/plan-placeholder.svg",
    highlights:seed.highlights,eligibility:seed.eligibility??"ตรวจอายุ อาชีพ และเงื่อนไขรับประกันของแผนและช่องทางที่เลือก",exclusions:seed.exclusions??["โปรดอ่านข้อยกเว้นในเอกสารกรมธรรม์; ช่องที่ไม่ทราบไม่ได้หมายความว่าไม่คุ้มครอง"],
    coverage:Object.fromEntries(Object.entries(coverageCells).map(([key,cell])=>[key,cell.status==="known"?cell.value:null])),source:{kind:"official",label:seed.name,updatedAt:checkedAt,url:sources.find(s=>s.id===identity)!.url}};
}
// Explicit researched records bypass the original product-family augmentation above.
const expandedSeeds:Seed[]=[
 {id:"motor-06",category:"motor",subtype:"voluntary",productId:"bki-firstloss-type1",insurer:"กรุงเทพประกันภัย",name:"กรุงเทพประกันภัย ชั้น 1 เลือกทุนเองได้",tierLabel:"ทุน 100,000 บาท",url:"https://www.bangkokinsurance.com/th/product/motor/voluntary/firstloss",price:quote("ตารางตัวอย่างกลุ่ม C รถอายุ 2–5 ปี ทุน 100,000 บาทแสดง 9,500 บาท รวมภาษีและส่วนลดกล้อง ไม่รวม พ.ร.บ.; ยังไม่ยืนยันรอบเบี้ยและราคาเฉพาะรถ"),
 cells:{class:known("ชั้น 1",null,"motor_class","ชื่อผลิตภัณฑ์"),ownDamageLimit:known(100000,"บาท","selected_vehicle_sum","ตารางเบี้ย / ทุน 100,000 บาท"),collisionLimit:known(100000,"บาท","selected_vehicle_sum","ความเสียหายต่อตัวรถ / ทุนที่เลือก"),theftLimit:known(100000,"บาท","selected_vehicle_sum","รถสูญหาย/ไฟไหม้ ตามทุน"),fireLimit:known(100000,"บาท","selected_vehicle_sum","รถสูญหาย/ไฟไหม้ ตามทุน"),floodLimit:missing(["มีความคุ้มครองน้ำท่วม แต่ยังไม่ยืนยันวงเงินแยก"],"included","จุดเด่น / น้ำท่วม"),thirdPartyBodilyPerPerson:known(1000000,"บาท","per_person_scope_unconfirmed","ตาราง / ความรับผิดต่อบุคคลภายนอก",["หน้านี้ไม่ระบุฐานส่วนเกิน พ.ร.บ. จึงยังเทียบฐานกับวงเงินส่วนเกินไม่ได้"]),thirdPartyBodilyPerEvent:known(20000000,"บาท","per_occurrence_scope_unconfirmed","ตาราง / ความรับผิดต่อบุคคลภายนอก",["ยังไม่ยืนยันฐานส่วนเกิน พ.ร.บ."]),thirdPartyProperty:known(5000000,"บาท","per_occurrence","ตาราง / ทรัพย์สินบุคคลภายนอก"),deductible:known(3000,"บาท","per_claim","ตาราง / ความเสียหายส่วนแรก และหมายเหตุ **",["ยกเว้นเมื่อแจ้งทันทีสำหรับรถชนรถ รถพลิกคว่ำจนขับไม่ได้ หรือน้ำท่วม ตามเงื่อนไข"]),repairType:known("อู่ในสัญญา",null,"repair_network","จุดเด่น / ศูนย์ซ่อมมาตรฐาน"),medicalPerPerson:absent("not_applicable","ช่องนี้เป็นค่ารักษาตาม พ.ร.บ. ไม่ใช่ภาคสมัครใจ")},highlights:["เลือกตัวอย่างทุนรถ 100,000 บาท","ทรัพย์สินคู่กรณี 5 ล้านบาทต่อครั้ง; ส่วนแรก 3,000 บาทมีเงื่อนไขยกเว้น"],eligibility:"รถส่วนบุคคลไม่เกิน 7 ที่นั่งตามรุ่นที่ระบุ ตรวจสภาพก่อนรับ ทุนไม่เกิน 80% มูลค่ารถ",exclusions:["ไม่รับรถรับจ้าง ให้เช่า รถแต่งหรือดัดแปลง","ไม่รวมอุปกรณ์ตกแต่งเพิ่มเติมจากโรงงาน"]},
 {id:"motor-07",category:"motor",subtype:"voluntary",productId:"viriyah-2plus-100k",insurer:"วิริยะประกันภัย",name:"วิริยะ 2+ ทุน 100,000 บาท",tierLabel:"ทุน 100,000 บาท",url:"https://vstore.viriyah.co.th/th/insurance-product-event.php?class_id=8&group_id=1&product_id=4",price:quote("คำนวณตามรถ; ค่า 0 ในแบบฟอร์มก่อนคำนวณไม่ใช่เบี้ย"),cells:{class:known("ชั้น 2+",null,"motor_class","หัวข้อ 2+ ทุน 100,000"),collisionLimit:known(100000,"บาท","selected_vehicle_sum","จุดเด่น / รถชนรถ",["ต้องชนยานพาหนะทางบกตามเงื่อนไข"]),ownDamageLimit:known(100000,"บาท","selected_vehicle_sum","จุดเด่น / ทุนตัวรถ"),theftLimit:known(100000,"บาท","per_occurrence","ตาราง / รถสูญหายไฟไหม้"),fireLimit:known(100000,"บาท","per_occurrence","ตาราง / รถสูญหายไฟไหม้"),thirdPartyBodilyPerPerson:known(500000,"บาท","per_person_scope_unconfirmed","ตาราง / ชีวิตร่างกายรวมผู้โดยสาร",["ยังไม่ยืนยันฐานส่วนเกิน พ.ร.บ. จากหน้านี้"]),thirdPartyBodilyPerEvent:known(10000000,"บาท","per_occurrence_scope_unconfirmed","ตาราง / ชีวิตร่างกายต่อครั้ง",["ยังไม่ยืนยันฐานส่วนเกิน พ.ร.บ."]),thirdPartyProperty:known(1000000,"บาท","per_occurrence","ตาราง / ทรัพย์สินบุคคลภายนอก"),medicalPerPerson:absent("not_applicable","ผลิตภัณฑ์ภาคสมัครใจ ไม่ใช่ค่ารักษาตาม พ.ร.บ.")},highlights:["รถชนรถ สูญหายและไฟไหม้ ทุน 100,000 บาท","ไม่ต้องตรวจสภาพรถตามหน้าผลิตภัณฑ์; ราคาและส่วนแรกต้องตรวจใบเสนอราคา"],eligibility:"เลือกยี่ห้อ รุ่น และปีจดทะเบียนเพื่อยืนยันเงื่อนไข",exclusions:["หน้าเว็บไม่ยืนยันน้ำท่วมหรือส่วนแรก ห้ามถือว่าไม่มีข้อจำกัด"]},
 {id:"travel-06",category:"travel",subtype:"domestic",productId:"msig-trip-easy-plus",insurer:"MSIG ประกันภัย",name:"MSIG Trip Easy Plus ในประเทศ แผน 3",tierLabel:"แผน 3 อายุ 1–75 ปี",url:"https://www.msig-thai.com/th/personal-insurance/trip-easy-plus-domestic",price:price("example",230,"trip","แผน 3 ทริป 1–3 วัน อายุ 1–75 ปี","ตารางเบี้ย / 1–3 วัน แผน 3"),cells:{medicalLimit:known(50000,"บาท","per_trip","ตารางข้อ 2 / แผน 3 อายุ 1–75",["เฉพาะอุบัติเหตุ; อาหารเป็นพิษ/ลำไส้อักเสบเฉียบพลันมีวงเงินแยก 20,000 บาท"]),evacuationLimit:known(100000,"บาท","per_trip","ตารางข้อ 4 / แผน 3"),repatriationLimit:known(100000,"บาท","per_trip","ตารางข้อ 5 / ส่งศพ แผน 3"),cancellationLimit:known(10000,"บาท","per_trip","ตารางข้อ 11 / แผน 3",["ค่าตั๋วเครื่องบินจากยกเลิกหรือเลื่อนเดินทาง"]),interruptionLimit:absent("not_covered","ตารางข้อ 13 / แผน 3 ระบุ 0"),baggageLimit:known(15000,"บาท","per_trip","ตารางข้อ 8 / แผน 3",["ไม่เกิน 3,000 บาทต่อชิ้น; ค่าเสียหายส่วนแรก 1,000 บาท"]),delayHours:known(4,"ชั่วโมง","delay_interval","ตารางข้อ 12 / แผน 3"),delayPayment:known(2000,"บาท","per_delay_interval","ตารางข้อ 12 / แผน 3"),delayLimit:known(12000,"บาท","per_trip","ตารางข้อ 12 / แผน 3"),maxTripDays:known(31,"วัน","per_trip","ตารางเบี้ย / ระยะเวลาสูงสุด"),policyDuration:known(3,"วัน","selected_trip_duration","ตารางเบี้ย / ตัวอย่างช่วง 1–3 วัน",["ตัวอย่างเลือกเดินทาง 3 วัน; เบี้ยช่วง 1–3 วันเท่ากัน"]),region:known("ประเทศไทย",null,"territory","เงื่อนไขข้อ 4")},highlights:["ทริป 1–3 วัน ตัวอย่าง 230 บาท","อุบัติเหตุ 50,000 บาท; เที่ยวบินล่าช้า 2,000 บาททุก 4 ชั่วโมง"],eligibility:"ผู้มีถิ่นฐานไทย อายุ 1–80 ปี; ตัวอย่างนี้ใช้วงเงินกลุ่ม 1–75 ปี",exclusions:["ไม่คุ้มครองทำร้ายตนเอง สุรา สงครามและเหตุที่กรมธรรม์ยกเว้น","อายุ 76–80 ปีค่ารักษาอุบัติเหตุลดเหลือ 25,000 บาท"]},
 {id:"travel-07",category:"travel",subtype:"outbound",productId:"msig-travel-easy-plus",insurer:"MSIG ประกันภัย",name:"MSIG Travel Easy Plus Easy 1",tierLabel:"Easy 1 รายเที่ยว อายุ 15–75 ปี",url:"https://www.msig-thai.com/th/personal-insurance/travel-easy-plus",price:quote("ต้องระบุประเทศและวันเดินทางสำหรับ Easy 1", "trip"),cells:{medicalLimit:known(5000000,"บาท","per_trip","ตาราง / ค่ารักษา Easy 1 อายุ 15–75",["ติดตามรักษาในไทย 250,000 บาทและ telemedicine 5,000 บาทเป็นส่วนหนึ่งของวงเงินนี้"]),evacuationLimit:{...conflict("จุดเด่น 2 ล้านบาท / ตารางข้อ 3.1 Easy 1 ระบุ 3 ล้านบาท",["ต้องยืนยันกับผู้รับประกัน: ตาราง 3 ล้านบาทสำหรับเหตุไม่เป็นมาก่อน; เหตุเป็นมาก่อนมีวงเงินแยก 150,000 บาท"]),unit:"บาท",basis:"per_trip"},repatriationLimit:known(2000000,"บาท","per_trip","ตารางข้อ 4.1 / Easy 1",["เหตุไม่เป็นมาก่อน; เหตุเป็นมาก่อนวงเงิน 100,000 บาทตามข้อ 4.2"]),cancellationLimit:known(500000,"บาท","per_trip","ตารางข้อ 9 / Easy 1"),interruptionLimit:known(500000,"บาท","per_trip","ตารางข้อ 10 / Easy 1"),baggageLimit:known(60000,"บาท","per_trip","ตารางข้อ 14 / Easy 1"),delayHours:known(6,"ชั่วโมง","delay_interval","ตารางข้อ 11 / Easy 1"),delayPayment:known(7000,"บาท","per_delay_interval","ตารางข้อ 11.1–11.2 / Easy 1",["กรณีเที่ยวบินทดแทนจ่ายทุก 6 ชั่วโมง; ยกเลิกโดยไม่มีทดแทนเกิน 6 ชั่วโมงจ่ายต่อเหตุ ไม่บวกสองกรณี"]),delayLimit:known(35000,"บาท","per_trip","ตารางข้อ 11 / Easy 1"),region:known("เดินทางออกจากประเทศไทย",null,"territory","เงื่อนไขข้อ 3 และ 6")},highlights:["ค่ารักษา 5 ล้านบาทสำหรับอายุ 15–75 ปี","ยกเลิก/ลดวันเดินทาง 500,000 บาทตามเหตุที่คุ้มครอง"],eligibility:"รายเที่ยวรับ 6 เดือน–80 ปี; ตัวอย่างใช้กลุ่ม 15–75 ปี เริ่มและจบทริปในไทย ซื้อก่อนออกเดินทางอย่างน้อย 2 ชั่วโมง",exclusions:["ยกเว้นสภาพที่เป็นมาก่อน เว้นข้อยกเว้นเฉพาะการเคลื่อนย้าย/ส่งศพที่ระบุ","ยกเว้นจักรยานยนต์ สกู๊ตเตอร์ไฟฟ้า กีฬา/งานเสี่ยง และประเทศที่ระบุในกรมธรรม์"]},
 {id:"property-06",category:"property",productId:"allianz-basic-home",insurer:"อลิอันซ์ อยุธยา ประกันภัย",name:"Allianz Basic Home แผน 1",tierLabel:"แผน 1 ทุนรวม 500,000 บาท",edition:"Version 211214 / มีผล 1 มกราคม 2565",url:"https://www.allianz.co.th/content/dam/onemarketing/azay/allianz-co-th/document-download/brochures/Basic-Home-Coverage_THA_RV9.9.22.pdf",price:price("starting",1009,"year","แผน 1 ทุนอาคารและทรัพย์สินรวม 500,000 บาท","หน้า Basic Home / แผน 1 และหมายเหตุ","รวมภาษีมูลค่าเพิ่มและอากรแสตมป์","https://www.allianz.co.th/th_TH/property/basic-home.html"),cells:{fireCoverage:known("ไฟไหม้ ฟ้าผ่า ระเบิด น้ำที่ไม่ใช่น้ำท่วม ยานพาหนะ อากาศยาน ลมพายุ แผ่นดินไหว ลูกเห็บ",null,"insured_perils","PDF หน้า 2 ข้อ 1",["วงเงินอาคารและทรัพย์สินรวม 500,000 บาท ไม่ใช่แยกอย่างละ 500,000"]),buildingLimit:known(500000,"บาท","shared_building_contents","PDF หน้า 2 ข้อ 1",["อาคารไม่รวมฐานราก และทรัพย์สินภายในใช้วงเงินร่วมกัน"]),contentsLimit:known(500000,"บาท","shared_building_contents","PDF หน้า 2 ข้อ 1",["ใช้วงเงินเดียวกับอาคาร ห้ามบวกเป็น 1 ล้านบาท"]),burglaryCoverage:known("20,000 บาทต่อครั้งและต่อปี",null,"per_occurrence_and_year","PDF หน้า 2 ข้อ 4",["โจรกรรมมีร่องรอยงัดแงะ ชิงทรัพย์หรือปล้นทรัพย์"]),sharedNaturalPerilsLimit:missing(["น้ำท่วมแยก 20,000 บาท รอ 7 วัน; พายุ/แผ่นดินไหว/ลูกเห็บอยู่ในทุนหลัก ไม่ใช่กลุ่มภัยเดียวกันกับ AXA"],"included","PDF หน้า 2 ข้อ 1–2"),includedPerils:known("พายุ แผ่นดินไหว ลูกเห็บรวมในทุนหลัก; น้ำท่วมแยก 20,000 บาท รอ 7 วัน",null,"peril_groups","PDF หน้า 2 ข้อ 1–2"),construction:known("บ้านคอนกรีต ครึ่งตึกครึ่งไม้ และบ้านไม้",null,"construction","PDF หน้า 2 เงื่อนไข",["ชั้น 2–3 รับเฉพาะบ้านเดี่ยวอยู่อาศัยส่วนตัว ไม่ใช่ให้เช่าหรือทำธุรกิจ"]),occupancy:known("ที่อยู่อาศัยตามชั้นสิ่งปลูกสร้างและเงื่อนไข",null,"occupancy","PDF หน้า 2 เงื่อนไข",["สถานที่หนึ่งซื้อได้หนึ่งกรมธรรม์"]),locationRestrictions:known("ยกเว้นเขตอันตรายที่ระบุ และมีข้อจำกัดทุนบางพื้นที่ภาคใต้",null,"territory_exclusions","PDF หน้า 2 / พื้นที่รับประกัน",["ต้องตรวจพื้นที่จริงตามรายละเอียด PDF ไม่ตีความว่าไม่รับทั้งจังหวัด"] )},highlights:["ทุนอาคารและทรัพย์สินรวม 500,000 บาท","น้ำท่วม 20,000 บาท รอ 7 วัน; โจรกรรม 20,000 บาทตามเงื่อนไข"],eligibility:"ทรัพย์สินมูลค่าตั้งแต่ 500,000 บาท; บ้านไม้/ครึ่งไม้เฉพาะบ้านเดี่ยวส่วนตัว",exclusions:["ไม่รวมทรัพย์สินของผู้อื่นที่รับดูแล โทรศัพท์ คอมพิวเตอร์พกพา เงินสดและเอกสารธุรกิจ","ภัยไฟฟ้า 50,000 บาทต่อครั้งต่อปี ต้องทำให้เกิดไฟไหม้เท่านั้น","PDF รุ่นเก่าที่ยังเชื่อมจากหน้าผลิตภัณฑ์ปัจจุบัน ต้องยืนยันฉบับเสนอขาย"]},
 ...([{id:"liability-06",productId:"tokio-marine-public-liability",insurer:"คุ้มภัยโตเกียวมารีนประกันภัย",name:"คุ้มภัยโตเกียวมารีน Public Liability",url:"https://www.tokiomarine.com/th/th/non-life/products/commercial/liability/public-liability-insurance.html",activity:"ความรับผิดต่อชีวิต ร่างกาย และทรัพย์สินบุคคลภายนอกจากธุรกิจ รวมค่าต่อสู้คดีที่บริษัทอนุญาตเป็นลายลักษณ์อักษร",exclusions:["ไม่รวมความเสียหายทางการเงินล้วนที่ไม่สืบเนื่องจากชีวิต ร่างกายหรือทรัพย์สิน","เขตอำนาจศาลและวงเงินต้องตามตารางกรมธรรม์"]},{id:"liability-07",productId:"msig-public-liability",insurer:"MSIG ประกันภัย",name:"MSIG Public Liability",url:"https://www.msig-thai.com/th/business-insurance/public-liability",activity:"ความรับผิดต่อบุคคลภายนอกจากความประมาทหรือข้อบกพร่องของสถานประกอบการ ครอบคลุมชีวิต ร่างกาย ทรัพย์สินและค่าใช้จ่ายทางกฎหมาย",exclusions:["วงเงินและข้อตกลงต้องกำหนดตามกิจการจริง","ยังไม่ยืนยันว่าค่าต่อสู้คดีอยู่ในหรือนอกวงเงิน"]}]).map((p):Seed=>({id:p.id,category:"liability",productId:p.productId,insurer:p.insurer,name:p.name,url:p.url,price:quote("ประกันสำหรับธุรกิจ ต้องระบุกิจการ สถานที่และวงเงินเพื่อขอใบเสนอราคา"),cells:{coveredActivity:known(p.activity,null,"business_public_liability","หัวข้อความคุ้มครองและค่าใช้จ่ายทางกฎหมาย"),territory:missing(["ขึ้นกับสถานที่และเขตอำนาจศาลที่ระบุในตารางกรมธรรม์"],"unknown","เงื่อนไขสถานที่และเขตอำนาจศาล")},highlights:["ประกันความรับผิดสำหรับธุรกิจ","มีผลิตภัณฑ์จริง; ราคาและวงเงินต้องขอใบเสนอราคา"],eligibility:"ผู้ประกอบกิจการตามเงื่อนไขการรับประกัน ไม่ใช่แผนความรับผิดส่วนบุคคลทั่วไป",exclusions:p.exclusions}))
];
expandedSeeds.push(
 {id:"health-06",category:"health",productId:"aia-health-happy",insurer:"เอไอเอ",name:"AIA Health Happy 5 ล้านบาท",tierLabel:"แผน 5 ล้านบาท",url:"https://www.aia.co.th/th/our-products/health/aia-health-happy",price:quote("สัญญาเพิ่มเติมสุขภาพ ต้องรวมเบี้ยกรมธรรม์ชีวิตหลักในใบเสนอราคา"),cells:{annualLimit:known(5000000,"บาท","per_year","ตาราง / แผน 5 ล้านบาท"),roomPerDay:known(3000,"บาท","per_day","ตาราง / ค่าห้อง แผน 5 ล้านบาท"),opdPerYear:absent("not_covered","ตาราง / OPD แผน 5 ล้านบาท"),icuPerDay:missing(["จ่ายตามจริงที่เข้าเงื่อนไขภายในวงเงินรายปี ไม่ใช่วงเงินไม่จำกัด"],"included","ตาราง / ICU"),minEntryAge:known(11,"ปี","entry_age","เงื่อนไข / อายุรับประกัน"),maxEntryAge:known(75,"ปี","entry_age","เงื่อนไข / อายุรับประกัน"),renewalAge:known(98,"ปี","renewal_age","โบรชัวร์ / ระยะต่ออายุ",["คุ้มครองถึงอายุ 99 หรือสิ้นสุดก่อนหากกรมธรรม์หลักสิ้นสุด"]),waitingDays:known(30,"วัน","waiting_period","โบรชัวร์ / ระยะรอคอย",["โรคที่กำหนดรอ 120 วัน; การเพิ่มผลประโยชน์มีเงื่อนไขเริ่มนับใหม่"]),roomMaxDays:known(365,"วัน","per_year","โบรชัวร์ / ค่าห้อง",["รวมวันห้องปกติและ ICU"]),copay:known("ต่ออายุอาจร่วมจ่าย 30% หรือ 50% ตามเกณฑ์สินไหม",null,"renewal_copayment","โบรชัวร์ / เงื่อนไขต่ออายุ",["≥3 ครั้ง minor illness และอัตราสินไหม≥200% หรือ ≥3 ครั้งโรคทั่วไปที่เข้าเกณฑ์และ≥400%:30%; เข้าเกณฑ์ทั้งสอง:50%; ประเมินรายปี"] )},extraSources:[{url:"https://www.aia.co.th/content/dam/th-wise/images/th/our-products/si_156_aia-healthy-happy/Brochure%20AIA%20Health%20Happy_Final_27Dec2022_website.pdf.coredownload.inline.pdf",locator:"หน้า 3,9–10 / ระยะรอคอยและการต่ออายุ"}],highlights:["วงเงิน 5 ล้านบาทต่อปี ค่าห้อง 3,000 บาทต่อวัน","สัญญาเพิ่มเติม ต้องมีประกันชีวิตหลัก; OPD ทั่วไปไม่รวม"],eligibility:"สมัคร 11–75 ปี ต้องพิจารณาสุขภาพและกรมธรรม์หลัก",exclusions:["ไม่รวมความผิดปกติแต่กำเนิด ศัลยกรรมความงาม ตั้งครรภ์และรักษามีบุตรยาก ตามข้อกำหนด"]},
 {id:"health-07",category:"health",productId:"allianz-beyond-care",insurer:"อลิอันซ์ อยุธยา ประกันภัย",name:"Allianz Beyond Care แผน 1",tierLabel:"แผน 1 ส่วนแรกมาตรฐาน",url:"https://www.allianz.co.th/th_TH/health/lump-sum/beyond-care.html",price:quote("แผน 1 ไม่เลือก OPD เพิ่ม ต้องขอราคาตามอายุ"),cells:{perAdmissionLimit:known(1000000,"บาท","per_admission","ตาราง / แผน 1 และเชิงอรรถ 1",["โรคหรือบาดเจ็บเดิมและภาวะแทรกซ้อน รวม Day Surgery ภายใน 90 วันจากออกโรงพยาบาลครั้งสุดท้ายนับวงเงินเดียว"]),roomPerDay:known(8000,"บาท","per_day","ตาราง / แผน 1 ค่าห้อง"),icuPerDay:known(16000,"บาท","per_day","ตาราง / แผน 1 ICU"),icuMaxDays:known(15,"วัน","per_admission","ตาราง / ICU สูงสุด"),deductible:known(0,"บาท","per_admission","ตารางส่วนแรก / มาตรฐานไม่มีส่วนแรก",["ไม่เลือกส่วนแรก 30,000/50,000/100,000/200,000 บาท"]),opdPerYear:missing(["เป็นความคุ้มครองเสริม ยังไม่เลือก"],"optional","ตาราง OPD เพิ่มเติม"),minEntryAge:known(11,"ปี","entry_age","เงื่อนไขข้อ 1 / แผน 1"),waitingDays:known(30,"วัน","waiting_period","ข้อยกเว้น / ระยะรอคอย",["โรคที่กำหนดรอ 120 วัน"]),renewalAge:missing(["เริ่มก่อน 60 และต่อเนื่องมีเงื่อนไขตลอดชีพ; เริ่มตั้งแต่ 60 ต่อถึง 80 ตามโบรชัวร์"],"unknown","โบรชัวร์ / ต่ออายุ")},highlights:["1 ล้านบาทต่อการรักษา ไม่ใช่ต่อปี","ค่าห้อง 8,000 บาทต่อวัน; ICU 16,000 บาทสูงสุด 15 วัน"],eligibility:"แผน 1 เริ่มสมัคร 11 ปี; อายุสูงสุดและราคาให้ตรวจใบเสนอราคา",exclusions:["ยกเว้นโรคที่เป็นมาก่อนตามเงื่อนไข","ทั่วโลกยกเว้นสหรัฐฯ มีข้อยกเว้นอุบัติเหตุจำกัด; ปลูกถ่ายอวัยวะและฟอกไตเฉพาะไทย"]},
 {id:"life-06",category:"life",productId:"bla-gain1st-esavings-10-5",insurer:"กรุงเทพประกันชีวิต",name:"Gain1st e-Savings 10/5",tierLabel:"ทุน 100,000 บาท",url:"https://www.bangkokbank.com/th-TH/Personal/My-Family-and-Me/Bancassurance/BLA/Gain1st-e-Savings",price:price("example",69000,"year","ชายอายุ 35 ปี ทุน 100,000 บาท ชำระ 5 ปี","ตัวอย่างชาย 35 ปี / ตารางเบี้ย"),cells:{lifeType:known("สะสมทรัพย์ ผ่านช่องทางธนาคารกรุงเทพ",null,"life_type","ชื่อการตลาด / Gain1st Happy"),sumAssured:known(100000,"บาท","initial_sum_assured","ตัวอย่างชาย 35 ปี"),coverageYears:known(10,"ปี","coverage_term","ความคุ้มครองและผลประโยชน์"),paymentYears:known(5,"ปี","payment_term","ระยะชำระเบี้ย"),paymentFrequency:known("รายปี",null,"payment_frequency","ตารางเบี้ยรายปี"),minEntryAge:known(20,"ปี","entry_age","คุณสมบัติ"),maxEntryAge:known(60,"ปี","entry_age","คุณสมบัติ"),deathFormula:known("สูงสุดระหว่าง 100% ของทุน เบี้ยชีวิตสะสม และมูลค่าเวนคืน",null,"death_formula","ความคุ้มครองกรณีเสียชีวิต"),guaranteedCashback:known("5% ของทุน ณ สิ้นปีกรมธรรม์ 1–9",null,"cashback_formula","ผลประโยชน์ระหว่างสัญญา"),maturityFormula:known("345% ของทุนเมื่อครบปีที่ 10",null,"maturity_formula","ผลประโยชน์ครบสัญญา")},highlights:["จ่าย 5 ปี คุ้มครอง 10 ปี","เงินคืนคิดจากทุนประกัน ไม่ใช่อัตราผลตอบแทนจากเบี้ย"],eligibility:"อายุ 20–60 ปี ผ่านช่องทางธนาคารกรุงเทพ; ตรวจสุขภาพตามเกณฑ์",exclusions:["ยังไม่ยืนยันข้อยกเว้นและตารางเวนคืนครบถ้วน ต้องอ่านสัญญาจริง"]},
 {id:"life-07",category:"life",productId:"prudential-prulife-care-term10",insurer:"พรูเด็นเชียล ประกันชีวิต",name:"PRULife Care 10/10",tierLabel:"ชีวิตหลัก 10 ปี ทุน 300,000 บาท",url:"https://www.prudential.co.th/en/products/life",price:quote("ยังไม่มีเบี้ยตรงทุน 300,000 บาทและอายุผู้สมัคร; ไม่แปลงโฆษณาต่อวันเป็นเบี้ยปี"),cells:{lifeType:known("ประกันชีวิตชั่วระยะเวลาไม่มีส่วนร่วมเงินปันผล",null,"life_type","PRULife Care / เงื่อนไขรับประกันข้อ 1"),sumAssured:known(300000,"บาท","initial_sum_assured","เงื่อนไข / ทุนเริ่มต้น 300,000"),coverageYears:known(10,"ปี","coverage_term","เงื่อนไข / ตัวเลือกระยะ 10 ปี"),paymentYears:known(10,"ปี","payment_term","เงื่อนไข / ชำระเท่าระยะสัญญา"),minEntryAge:known(20,"ปี","entry_age","เงื่อนไข / อายุรับประกัน"),maxEntryAge:known(59,"ปี","entry_age","เงื่อนไข / อายุรับประกัน"),deathFormula:known("100% ของทุนกรณีเสียชีวิตหรือเจ็บป่วยระยะสุดท้าย",null,"death_or_terminal_formula","PRULife Care / ผลประโยชน์",["ไม่ใช่จ่ายทุนสองครั้ง; ต้องตรวจนิยามเจ็บป่วยระยะสุดท้าย"] )},highlights:["ชีวิตหลัก ทุน 300,000 บาท คุ้มครอง 10 ปี","ไม่รวมสัญญาเพิ่มเติมมะเร็ง โรคร้ายแรงหรือรายวัน"],eligibility:"สัญชาติไทย อายุ 20–59 ปี ตามเกณฑ์รับประกัน",exclusions:["ฆ่าตัวตายภายใน 1 ปี ผู้รับประโยชน์จงใจฆ่า และการแถลงข้อมูลคลาดเคลื่อนตามสัญญา"]},
 {id:"accident-06",category:"accident",productId:"bki-pa-holiday",insurer:"กรุงเทพประกันภัย",name:"PA Holiday ทุน 300,000 บาท",tierLabel:"ทุน 300,000 บาท",url:"https://www.bangkokinsurance.com/th/product/accident/holiday",price:price("fixed",910,"year","คอลัมน์ทุน 300,000 บาท อายุรับประกัน 1–65 ปี","ตารางเบี้ยรายปี คอลัมน์แรก","รวมอากรแสตมป์"),cells:{deathBenefit:known(300000,"บาท","per_accident","ตาราง / อุบัติเหตุทั่วไป"),disabilityBenefit:known(300000,"บาท","per_accident","ตาราง / ทุพพลภาพและสูญเสียอวัยวะ",["จำนวนสูงสุด; สูญเสียอวัยวะตามเงื่อนไขไม่ใช่เต็มทุนทุกกรณี"]),motorcycleBenefit:known(150000,"บาท","per_accident","ตาราง / จักรยานยนต์"),homicideBenefit:known(150000,"บาท","per_accident","ตาราง / ฆาตกรรมหรือทำร้าย"),medicalPerAccident:known(10000,"บาท","per_accident","ตาราง / ค่ารักษา",["รวมจักรยานยนต์และทำร้าย; ค่าห้อง/ICU อยู่ในวงเงินนี้"]),minEntryAge:known(1,"ปี","entry_age","เงื่อนไขอายุ"),maxEntryAge:known(65,"ปี","entry_age","เงื่อนไขอายุ")},highlights:["วันหยุดประจำปีที่กำหนดอุบัติเหตุสูงสุด 600,000 บาท","ค่ารักษา 10,000 บาทต่ออุบัติเหตุ; เบี้ย 910 บาทต่อปี"],eligibility:"อายุ 1–65 ปี ต่ออายุถึง 65 ปี; อาชีพตามเกณฑ์",exclusions:["วันหยุดชดเชย/พิเศษไม่ใช่วันหยุดที่ได้เพิ่มทุนโดยอัตโนมัติ","ไม่รับอาชีพเสี่ยงที่ระบุ เช่น ส่งอาหาร ก่อสร้าง รักษาความปลอดภัยและผู้ขับขี่","เงินเยียวยา 20,000 บาทต้องนอนโรงพยาบาลอย่างน้อย 14 วัน ไม่ใช่รายวัน"]},
 {id:"accident-07",category:"accident",productId:"bla-accident-care-rider",insurer:"กรุงเทพประกันชีวิต",name:"Accident Care สัญญาเพิ่มเติม 1 ล้านบาท",tierLabel:"ทุน 1 ล้านบาท อาชีพกลุ่ม 1",url:"https://www.bangkoklife.com/th/products/detail/286",price:quote("สัญญาเพิ่มเติมตัวอย่าง 6,429 บาท/ปี อายุแรกเกิด–60 กลุ่มอาชีพ 1 ไม่รวมเบี้ยชีวิตหลัก ต้องขอราคารวม"),cells:{deathBenefit:known(1000000,"บาท","per_accident","ตาราง / ทุน 1 ล้านบาท",["เสียชีวิตภายใน 180 วันจากอุบัติเหตุตามเงื่อนไข"]),medicalPerAccident:known(100000,"บาท","per_accident","ตาราง / ค่ารักษาต่ออุบัติเหตุ"),minEntryAge:missing(["รับตั้งแต่แรกเกิดตามเงื่อนไข; ไม่แปลงเป็นอายุปีเศษ"],"included","เงื่อนไขอายุ / แรกเกิด"),maxEntryAge:known(70,"ปี","entry_age","เงื่อนไขอายุ"),occupationClass:known("กลุ่มอาชีพ 1",null,"occupation_class","ตารางเบี้ย / กลุ่ม 1",["ตัวอย่างนี้ไม่ใช่รับรองทุกลักษณะงาน"] )},highlights:["ค่ารักษาอุบัติเหตุ 100,000 บาท","ต้องมีประกันชีวิตหลัก; ไม่ใช่ PA เดี่ยวราคา 6,429 บาท"],eligibility:"แรกเกิด–70 ปี สัญญาเพิ่มเติมต่อปีขึ้นกับชีวิตหลัก อาจคุ้มครองถึง 99 ตามเกณฑ์",exclusions:["สุราตามเกณฑ์ ทำร้ายตนเอง กีฬาเสี่ยงและอากาศยานที่ไม่ใช่พาณิชย์","สูญเสียอวัยวะหนึ่งข้าง 600,000 บาทไม่ใช่เต็มทุน; ไม่รวมผลประโยชน์เพิ่มหลายเหตุโดยไม่มีหลักฐาน"]}
);
const aiaBrochure="https://www.aia.co.th/content/dam/th-wise/images/th/our-products/si_156_aia-healthy-happy/Brochure%20AIA%20Health%20Happy_Final_27Dec2022_website.pdf.coredownload.inline.pdf";
const pruConditions="https://www.prudential.co.th/content/dam/prudential-aem-lbu/plt/th_TH/product/life/pru-life-care/%E0%B9%80%E0%B8%87%E0%B8%B7%E0%B9%88%E0%B8%AD%E0%B8%99%E0%B9%84%E0%B8%82%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B8%A3%E0%B8%B1%E0%B8%9A%E0%B8%9B%E0%B8%A3%E0%B8%B0%E0%B8%81%E0%B8%B1%E0%B8%99.pdf";
expandedSeeds.push(
 {id:"health-08",category:"health",productId:"fwd-easy-ehealth-500k",insurer:"เอฟดับบลิวดี ประกันชีวิต",name:"FWD Easy E-Health 500,000 บาท",tierLabel:"IPD 500,000 บาท ไม่เลือก OPD เสริม",url:"https://www.fwd.co.th/th/health-insurance/easy-e-health/",price:quote("ต้องเลือกข้อมูลผู้สมัครและรับใบเสนอราคาของแพ็กเกจ; ไม่ใช้ราคาโฆษณารายวันเป็นเบี้ยจริง"),cells:{
 annualLimit:known(500000,"บาท","per_policy_year","หน้า 25 / ผลประโยชน์สูงสุดต่อรอบปี"),roomPerDay:known(1500,"บาท","per_day","หน้า 23 / หมวด 1 ค่าห้อง"),roomBasis:known("ค่าห้อง อาหาร และบริการโรงพยาบาลตามจริงไม่เกิน 1,500 บาทต่อวัน",null,"room_limit","หน้า 23 / หมวด 1"),roomMaxDays:known(365,"วัน","per_policy_year","หน้า 23 / หมวด 1",["ต่อรอบปีกรมธรรม์ ไม่ใช่ต่อการเข้าพักทุกครั้ง"]),icuPerDay:missing(["จ่ายตามจริงในวงเงินรวม ไม่ใช่จำนวนต่อวันคงที่หรือไม่จำกัด"],"included","หน้า 23 / ICU"),icuMaxDays:known(180,"วัน","per_policy_year","หน้า 23 / ICU",["ต่อรอบปีกรมธรรม์"]),deductible:known(0,"บาท","selected_deductible","หน้า 25 / ความรับผิดส่วนแรก ไม่มี"),waitingDays:known(30,"วัน","waiting_period","หน้า 36 / ระยะเวลาที่ไม่คุ้มครอง",["โรคที่ระบุรอ 120 วัน; เริ่มนับตามวันเริ่มคุ้มครอง/การเพิ่มผลประโยชน์ที่เกี่ยวข้อง"]),copay:known("อาจร่วมจ่าย 30% หรือ 50% เมื่อต่ออายุเข้าเกณฑ์",null,"renewal_copay","หน้า 33 / เงื่อนไขร่วมจ่ายเมื่อต่ออายุ",["30% เมื่อ ≥3 ครั้งและอัตราสินไหม ≥200% สำหรับเจ็บป่วยเล็กน้อย หรือ ≥3 ครั้งและ ≥400% สำหรับกลุ่มเจ็บป่วยที่กำหนด; สองเกณฑ์ร่วมกัน 50% ทบทวนปีต่อปี"]),opdPerYear:missing(["OPD เป็นสัญญา/ตัวเลือกเพิ่มเติมที่ยังไม่เลือก"],"optional","หน้าเว็บไซต์ / เลือกความคุ้มครองเพิ่มเติม"),minEntryAge:known(20,"ปี","entry_age","หน้าเว็บไซต์ / รายละเอียดกรมธรรม์"),maxEntryAge:known(60,"ปี","entry_age","หน้าเว็บไซต์ / รายละเอียดกรมธรรม์"),renewalAge:known(79,"ปี","renewal_age","หน้าเว็บไซต์ / รายละเอียดกรมธรรม์",["ต่ออายุตามเงื่อนไข คุ้มครองถึงอายุ 80 ไม่ใช่ต่อได้ถึง 80"])
 },highlights:["IPD 500,000 บาทต่อปี ค่าห้อง 1,500 บาทต่อวัน","แผนไม่มีส่วนแรกตามตาราง; OPD เสริมยังไม่เลือก"],eligibility:"อายุสมัคร 20–60 ปี ต่ออายุถึง 79 ปี คุ้มครองถึง 80 ตามเงื่อนไข",exclusions:["เจ็บป่วยที่เป็นมาก่อนเอาประกันและข้อยกเว้นตามสัญญา","อาการเดิม/ภาวะแทรกซ้อนภายใน 90 วันหลังออกโรงพยาบาลรวมเป็นการพักรักษาครั้งเดียว รวม Day Surgery","คุ้มครองไทย; กรณีฉุกเฉินต่างประเทศต้องเข้าเงื่อนไขการเดินทางไม่เกิน 45 วัน ไม่ใช่ทั่วโลกโดยไม่มีข้อจำกัด"]},
 {id:"health-09",category:"health",productId:"thailife-health-fit-dd-1m",insurer:"ไทยประกันชีวิต",name:"ไทยประกันชีวิต Health Fit DD แผน 1 ล้านบาท",tierLabel:"แผน 1 ล้านบาท ไม่มีส่วนแรก",url:"https://product.thailife.com/media/wysiwyg/TL-brochure/HealthFitDD.pdf",edition:"P0097-1/03/69 ตามโบรชัวร์; ไม่อนุมานวันมีผล",price:quote("เบี้ยสัญญาเพิ่มเติมตัวอย่าง 15,710 บาท/ปี ชาย 35 ปี อาชีพ 1/2 ไม่รวมสัญญาชีวิตหลัก ต้องขอราคารวม"),cells:{
 annualLimit:known(1000000,"บาท","per_policy_year","หน้า 2 / ตารางแผน 1 ล้านบาท"),roomPerDay:known(2000,"บาท","per_day","หน้า 2 / หมวด 1"),roomBasis:known("ค่าห้อง อาหาร และบริการโรงพยาบาลตามจริงไม่เกิน 2,000 บาทต่อวัน",null,"room_limit","หน้า 2 / หมวด 1"),roomMaxDays:known(365,"วัน","per_admission_shared_room_icu","หน้า 2 / หมวด 1",["วันห้องปกติและ ICU รวมกันไม่เกิน 365 ต่อการพักรักษา"]),icuPerDay:missing(["ตามจริงในวงเงินรวม ไม่ใช่วงเงินต่อวันคงที่หรือไม่จำกัด"],"included","หน้า 2 / ICU"),icuMaxDays:known(365,"วัน","per_admission_shared_room_icu","หน้า 2 / หมวด 1 ICU",["ใช้เพดานวันร่วมกับห้องปกติ ไม่ใช่อีก 365 วัน"]),deductible:known(0,"บาท","per_admission","หน้า 2 / ตัวเลือกความรับผิดส่วนแรก ไม่มี",["ไม่ได้เลือกตัวเลือกส่วนแรก 30,000 หรือ 50,000 บาท"]),opdPerYear:missing(["OPD เป็นความคุ้มครองเพิ่ม ไม่รวมในแผนที่เลือก"],"optional","หน้า 2 / เพิ่มความคุ้มครอง OPD"),minEntryAge:missing(["รับตั้งแต่อายุ 15 วัน ไม่แปลงเป็นอายุ 0 ปี"],"included","หน้า 1 / อายุรับประกัน"),maxEntryAge:known(80,"ปี","entry_age","หน้า 1 / อายุรับประกัน"),renewalAge:missing(["คุ้มครองถึง 99 หรือสิ้นสุดสัญญาหลัก; อายุ 98 ในเอกสารเป็นปลายชำระเบี้ย ไม่ใช่เพดานต่ออายุที่ยืนยัน"],"unknown","หน้า 1 / ระยะประกันและชำระเบี้ย")
 },highlights:["วงเงินสุขภาพ 1 ล้านบาทต่อปี ค่าห้อง 2,000 บาทต่อวัน","สัญญาเพิ่มเติมต้องมีประกันชีวิตหลัก; เบี้ยแสดงเป็นราคารวมที่ต้องขอ"],eligibility:"อายุ 15 วัน–80 ปี เป็นสัญญาเพิ่มเติม คุ้มครองถึง 99 ปีหรือสิ้นสุดสัญญาหลักตามเงื่อนไข",exclusions:["ต้องอ่านข้อยกเว้นในสัญญาจริง; โบรชัวร์นี้ยังไม่ยืนยันระยะรอหรือ Copay","คุ้มครองในประเทศไทยตามตาราง; ต้องซื้อสัญญาเพิ่มเติมพร้อมสัญญาหลัก","ไม่ใช้เงื่อนไขอายุหรือระยะรอจากแพ็กเกจธนาคารคนละช่องทาง"]}
);
const eligibilityLocators:Record<string,string>={
 "health-08":"รายละเอียดกรมธรรม์ / อายุรับประกัน 20–60 ปี ต่ออายุถึง79",
 "health-09":"หน้า 1 / อายุรับประกันและระยะคุ้มครองสัญญาเพิ่มเติม",
 "motor-06":"เงื่อนไขการรับประกัน ข้อ 1–6 / รุ่นรถ ทุนไม่เกิน 80% และตรวจสภาพ",
 "motor-07":"เงื่อนไขการรับประกันภัย / รถใช้งานส่วนบุคคลไม่ใช้รับจ้าง",
 "travel-06":"เงื่อนไขการรับประกันภัย / อายุ 1–75 ปี และระยะเวลาไม่เกิน 31 วัน",
 "travel-07":"เงื่อนไขการรับประกันภัย / อายุ 15–75 ปี และการเดินทางออกจากประเทศไทย",
 "property-06":"หน้า 2 / เงื่อนไขการรับประกันภัย ข้อ 1–5 ประเภทสิ่งปลูกสร้างและพื้นที่",
 "liability-06":"Public Liability Insurance / businesses and legal liability to third parties",
 "liability-07":"Public Liability / ความรับผิดของผู้ประกอบธุรกิจต่อบุคคลภายนอก",
 "health-06":"เงื่อนไขการรับประกันภัย / อายุรับประกัน 11–75 ปี และสัญญาเพิ่มเติม",
 "health-07":"เงื่อนไขการรับประกันภัย / อายุ 11 ปีขึ้นไปและเงื่อนไขต่ออายุ",
 "life-06":"เงื่อนไขการรับประกันภัย / อายุ 20–60 ปี และแบบประกันออนไลน์",
 "life-07":"หน้า 1 / เงื่อนไขการรับประกัน ข้อ 1 อายุ 20–59 ปี สัญชาติไทย",
 "accident-06":"เงื่อนไขการรับประกันภัย / อายุ 1–65 ปี ต่ออายุไม่เกิน 65 ปี และอาชีพ",
 "accident-07":"เงื่อนไขการรับประกันภัย / แรกเกิด–70 ปี และระยะเวลาสัญญาเพิ่มเติม"
};
for(const seed of expandedSeeds){
 if(seed.id==="motor-06")seed.cells.voluntaryMedicalPerPerson=known(200000,"บาท","per_insured_driver_passenger","ตาราง / ค่ารักษาพยาบาลสำหรับผู้ขับขี่และผู้โดยสาร");
 if(seed.id==="motor-07"){
  seed.cells.voluntaryMedicalPerPerson=known(50000,"บาท","per_insured_driver_passenger","ตาราง / เอกสารแนบท้าย ค่ารักษาพยาบาล",["ผู้ขับขี่ 1 คน ผู้โดยสาร 5 คน"]);
  seed.price=quote("ตารางแสดง 7,500 บาท แต่ไม่ระบุระยะเบี้ยในหน้าที่ตรวจ ต้องยืนยันรถและใบเสนอราคา");
 }
 if(seed.id==="property-06"){
  seed.cells.combinedPropertyLimit=known(500000,"บาท","shared_building_contents","หน้า 2 / ความคุ้มครองหลัก ข้อ 1 แผน 1",["อาคารไม่รวมฐานรากและทรัพย์สินภายในใช้ทุนเดียวกัน ไม่บวกเป็นหนึ่งล้าน"]);
  for(const field of ["buildingLimit","contentsLimit"])seed.cells[field]=missing(["ไม่แยกทุนเฉพาะส่วน ใช้วงเงินรวมอาคารและทรัพย์สินภายใน 500,000 บาท"],"included","หน้า 2 / ความคุ้มครองหลัก ข้อ 1 แผน 1");
  seed.cells.floodLimit=known(20000,"บาท","policy_limit","หน้า 2 / ความคุ้มครองหลัก ข้อ 2 แผน 1",["ระยะรอคอย 7 วัน; ไม่รวมเป็นก้อนเดียวกับพายุ แผ่นดินไหวและลูกเห็บ"]);
 }
 if(seed.id==="travel-07"){
  seed.cells.maxTripDays=known(180,"วัน","single_trip_max","FAQ / รายเที่ยวกับรายปีต่างกันอย่างไร",["ตัวเลือกนี้รายเที่ยว; ระยะเดินทางจริงยังไม่เลือก"]);
  seed.cells.delayTrigger=known("อากาศไม่เอื้ออำนวย อุปกรณ์เครื่องบินขัดข้อง หรือลูกจ้างสายการบิน/สนามบินหยุดงานหรือประท้วง",null,"delay_trigger","หมายเหตุ / หมวดดูแลการล่าช้าและเที่ยวบิน ข้อ 11.1–11.2",["กรณีจัดเที่ยวบินทดแทนจ่ายทุก 6 ชั่วโมง; ยกเลิกไม่มีทดแทนหลังล่าช้าเกิน 6 ชั่วโมงจ่ายต่อเหตุ ไม่รับสองกรณีพร้อมกัน"]);
 }
 if(seed.id==="health-06"){
  seed.cells.roomBasis=known("ค่าห้อง อาหาร และบริการในโรงพยาบาลตามจริงไม่เกิน 3,000 บาทต่อวัน",null,"room_limit","หน้า 7 / หมวด 1 แผน 5 ล้านบาท",["ห้องปกติและ ICU รวมวันตามเงื่อนไข ไม่ใช่ห้องเดี่ยวราคาใดก็ได้"]);seed.cells.roomBasis.url=aiaBrochure;
  seed.cells.icuMaxDays=known(365,"วัน","per_admission_shared_room_icu","หน้า 3 หมายเหตุ 4–5 และหน้า 7 หมวด 1",["รวมวันห้องปกติและ ICU ไม่เกิน 365 วัน ไม่ใช่แยกคนละ 365"]);seed.cells.icuMaxDays.url=aiaBrochure;
  seed.cells.roomMaxDays.basis="per_admission_shared_room_icu";
  seed.cells.roomMaxDays.locator="หน้า 3 หมายเหตุ 4–5 และหน้า 7 หมวด 1";
  seed.cells.perAdmissionLimit=absent("not_applicable","หน้า 3 / ไม่มีวงเงินแยกต่อครั้ง ใช้วงเงินรายปีและเพดานรายหมวด");seed.cells.perAdmissionLimit.url=aiaBrochure;
  for(const field of ["opdPerVisit","opdVisitsPerDay"])seed.cells[field]=absent("not_covered","ตารางแผน 5 ล้านบาท / OPD ปกติไม่คุ้มครอง ไม่ใช่ OPD ต่อเนื่องหลัง IPD");
 }
 if(seed.id==="health-07")seed.cells.roomBasis=known("ค่าห้อง อาหาร และบริการโรงพยาบาล ไม่เกิน 8,000 บาทต่อวัน",null,"room_limit","ตารางหมวด 1 แผน 1",["อยู่ในวงเงินต่อการพักรักษา 1 ล้านบาทและข้อรวมอาการเดิม 90 วัน"]);
 if(seed.category==="health")seed.cells.eligibilityConditions=known(seed.eligibility!,null,"underwriting",eligibilityLocators[seed.id]);
 if(seed.id==="life-07")seed.cells.nonGuaranteedBenefit=absent("not_covered","หน้า 1 / แบบชั่วระยะเวลาไม่มีเงินปันผล");
 if(seed.id==="life-06"||seed.id==="life-07")seed.cells.coverageUntilAge=absent("not_applicable","ระยะคุ้มครอง 10 ปีตามแผนที่เลือก ไม่ใช่สัญญากำหนดอายุสิ้นสุด");
 if(seed.id==="accident-06")seed.cells.hospitalAdmissionBenefit=known(20000,"บาท","per_accident_lump_sum","ตาราง / เงินเยียวยา แผนทุน 300,000",["นอนโรงพยาบาลอย่างน้อย 14 วันเนื่องจากอุบัติเหตุตามเงื่อนไข; ไม่ใช่เงินต่อวัน"]);
 if(seed.id==="accident-07"){
  seed.cells.homicideBenefit=known(1000000,"บาท","death_per_accident","ตาราง ข้อ 1.1 และหมายเหตุข้อ 1",["หมายเหตุรวมถูกฆาตกรรม/ทำร้ายร่างกาย ภายใต้เงื่อนไขสัญญา"]);
  seed.cells.publicAccidentBenefit=known(2000000,"บาท","public_accident_death_total","ตาราง ข้อ 1.1 + ข้อ 6 และนิยามอุบัติเหตุสาธารณะ",["ทุนเสียชีวิต 1 ล้านบาทบวกเพิ่มหนึ่งเท่าเฉพาะอุบัติเหตุสาธารณะที่ระบุ; ไม่รวมหลายเงื่อนไขเพิ่มทุนซ้อนกัน"]);
 }

 seed.eligibilitySource={url:seed.id==="life-07"?pruConditions:seed.url,locator:eligibilityLocators[seed.id]};
 for(const [field,cell] of Object.entries(seed.cells)){
  if(seed.id==="health-08"&&!["opdPerYear","minEntryAge","maxEntryAge","renewalAge","eligibilityConditions"].includes(field))cell.url="https://www.fwd.co.th/files/v3/assets/blt331c1aa12dcfd37a/blt9c6be205ca1ac70e/67be96c1045f58f038bfaa8c/Easy_E-Health_500_000_THB.pdf";
  if(seed.id==="health-06"&&["renewalAge","waitingDays","roomMaxDays","copay"].includes(field))cell.url=aiaBrochure;
  if(seed.id==="life-07"&&field!=="deathFormula")cell.url=pruConditions;
 }
 if(seed.id==="life-07")seed.extraSources=[{url:pruConditions,locator:"หน้า 1 / เงื่อนไขการรับประกัน ข้อ 1,3–8"}];
}
export const catalog:Plan[]=[...seeds,...expandedSeeds].map(buildPlan);
export type SearchOptions={category?:Category;q?:string;maxPremium?:number;sort?:PlanSort};
export function searchPlans({category="health",q="",maxPremium,sort="price-asc"}:SearchOptions={}):Plan[]{
  const query=q.trim().toLocaleLowerCase("th-TH");const budget=Number.isFinite(maxPremium)&&(maxPremium??-1)>=0?maxPremium:undefined;
  const plans=catalog.filter(p=>p.category===category&&(budget===undefined||(p.price.amountTHB!==null&&p.price.amountTHB<=budget))&&(!query||[p.name,p.insurer,...p.highlights].some(t=>t.toLocaleLowerCase("th-TH").includes(query))));
  return plans.sort((a,b)=>{if(sort==="name")return a.name.localeCompare(b.name,"th")||a.id.localeCompare(b.id);const x=a.price.amountTHB,y=b.price.amountTHB;if(x===null)return y===null?a.id.localeCompare(b.id):1;if(y===null)return -1;return (sort==="price-desc"?y-x:x-y)||a.id.localeCompare(b.id);});
}
export function getPlan(id:string):Plan|undefined{return catalog.find(plan=>plan.id===id);}







