// Plain-language context, not a substitute for the selected policy's wording.
const healthSource = "https://www.aia.co.th/th/our-products/health/aia-health-happy";
const healthWording = "https://www.fwd.co.th/files/v3/assets/blt331c1aa12dcfd37a/blt9c6be205ca1ac70e/67be96c1045f58f038bfaa8c/Easy_E-Health_500_000_THB.pdf";
const motorSource = "https://www.bangkokinsurance.com/th/product/motor/voluntary/firstloss";
const lifeSource = "https://www.bangkokbank.com/th-TH/Personal/My-Family-and-Me/Bancassurance/BLA/Gain1st-e-Savings";
const propertySource = "https://www.allianz.co.th/content/dam/onemarketing/azay/allianz-co-th/document-download/brochures/Basic-Home-Coverage_THA_RV9.9.22.pdf";
const travelSource = "https://www.msig-thai.com/th/personal-insurance/travel-easy-plus";

export const insuranceTerms = {
  ipd: {title:"IPD · ผู้ป่วยใน",description:"การรักษาที่รับไว้เป็นผู้ป่วยในของโรงพยาบาล ตามนิยามในสัญญา",caution:"การนอนโรงพยาบาลไม่ได้ทำให้เคลมได้ทุกกรณี ยังต้องเข้าเงื่อนไขความจำเป็นทางการแพทย์และความคุ้มครอง",source:healthWording},
  opd: {title:"OPD · ผู้ป่วยนอก",description:"การพบแพทย์โดยไม่ได้รับไว้เป็นผู้ป่วยใน เช่น ตรวจแล้วกลับบ้าน",caution:"OPD ทั่วไปอาจต้องซื้อเพิ่ม ต่างจากการติดตามผลหลัง IPD หรือรักษาอุบัติเหตุที่บางแผนรวมไว้แล้ว",source:healthWording},
  icu: {title:"ICU · ห้องผู้ป่วยวิกฤต",description:"ห้องสำหรับผู้ป่วยที่ต้องดูแลอย่างใกล้ชิด วงเงินและจำนวนวันอาจต่างจากห้องปกติ",caution:"คำว่าจ่ายตามจริงยังอยู่ภายใต้เพดานและเงื่อนไขของแผน บางแผนใช้จำนวนวันร่วมกับห้องปกติ",source:healthSource},
  copay: {title:"Copay · การร่วมจ่าย",description:"ส่วนค่ารักษาที่ผู้เอาประกันต้องร่วมออกเป็นสัดส่วน เช่น 30% ของค่าใช้จ่ายที่เข้าเกณฑ์",caution:"ต่างจากส่วนแรกที่เป็นจำนวนเงิน เงื่อนไขร่วมจ่ายเมื่อต่ออายุไม่ได้ใช้กับทุกคนหรือทุกการเคลม ต้องดูสัญญาและเกณฑ์ของแผน",source:"https://www.oic.or.th/web-upload/1xff0d34e409a13ef56eea54c52a291126/202412/m_news/217/68875/file_download/0f38082b2174b0fdbb3d26693e395c46.pdf"},
  deductible: {title:"Deductible · ความรับผิดส่วนแรก",description:"จำนวนเงินส่วนแรกที่ผู้เอาประกันรับผิดชอบเองสำหรับความเสียหายที่เข้าเงื่อนไข",caution:"ต้องดูว่าใช้ต่อครั้ง ต่อโรค หรือต่อปี ต่างจาก Copay ที่คิดเป็นสัดส่วน ช่องที่ไม่ทราบไม่ได้แปลว่าส่วนแรกเป็นศูนย์",source:healthWording},
  sum_assured: {title:"ทุนประกัน",description:"จำนวนเงินอ้างอิงที่เลือกไว้ในสัญญา ใช้กำหนดเพดานหรือคำนวณผลประโยชน์",caution:"ไม่ใช่เบี้ยที่ต้องจ่าย และไม่ได้หมายความว่าทุกเหตุจะได้รับเงินเต็มทุน",source:lifeSource},
  per_year: {title:"วงเงินต่อปีกรมธรรม์",description:"เพดานผลประโยชน์รวมในรอบปีของกรมธรรม์ตามที่สัญญากำหนด",caution:"ต่างจากวงเงินต่อครั้งหรือต่อโรค และรอบปีกรมธรรม์ไม่จำเป็นต้องตรงเดือนมกราคมถึงธันวาคม",source:healthWording},
  per_disease: {title:"วงเงินต่อโรค",description:"เพดานที่ใช้กับการเจ็บป่วยหรือโรคตามนิยามของแผน",caution:"อาการเดิมหรือภาวะแทรกซ้อนอาจถูกรวมกัน อย่าเทียบเลขเดียวกับวงเงินต่อปีโดยไม่ดูฐาน",source:"https://www.axa.co.th/th/personal/health-insurance/comprehensive-plan"},
  per_admission: {title:"วงเงินต่อการพักรักษา",description:"เพดานสำหรับการเข้ารักษาหนึ่งครั้งตามนิยามในกรมธรรม์",caution:"กลับมารักษาอาการเดิมภายในช่วงที่กำหนดอาจนับเป็นครั้งเดียว บางแผนรวม Day Surgery ด้วย ไม่ได้เริ่มวงเงินใหม่ทุกครั้งที่เข้าโรงพยาบาล",source:healthWording},
  waiting: {title:"ระยะรอคอย",description:"ช่วงหลังเริ่มความคุ้มครองที่เหตุหรือโรคบางอย่างยังไม่อยู่ในความคุ้มครอง",caution:"จำนวนวันอาจต่างกันตามโรคและการเพิ่มผลประโยชน์ พ้นระยะรอไม่ได้ยกเลิกข้อยกเว้นอื่น",source:healthWording},
  third_party: {title:"บุคคลภายนอก",description:"บุคคลอื่นที่ได้รับความเสียหายและผู้เอาประกันมีความรับผิดตามกฎหมายในขอบเขตที่สัญญารับไว้",caution:"แยกวงเงินบาดเจ็บต่อคน ต่อเหตุ และทรัพย์สิน ความเสียหายของตัวเราไม่ได้อยู่ในวงเงินนี้โดยอัตโนมัติ",source:"https://www.msig-thai.com/th/business-insurance/public-liability"},
  shared_cap: {title:"วงเงินร่วม",description:"หลายรายการใช้เพดานก้อนเดียวกัน เช่น อาคารกับทรัพย์สินภายใน หรือหลายภัยธรรมชาติ",caution:"ห้ามนำวงเงินที่แสดงซ้ำมาบวกกัน ต้องดูว่ารายการใดใช้ก้อนเดียวกันและรายการใดมีวงเงินแยก",source:propertySource},
  quote: {title:"เบี้ยประกันและใบเสนอราคา",description:"เบี้ยคือเงินที่จ่ายเพื่อทำประกัน ราคาอาจเป็นราคาคงที่ ราคาเริ่มต้น ตัวอย่างเฉพาะกรณี หรือรอใบเสนอราคา",caution:"เทียบโดยใช้ระยะเวลาและเงื่อนไขเดียวกัน เบี้ยสัญญาเพิ่มเติมอาจยังไม่รวมสัญญาหลักและราคาเริ่มต้นไม่ใช่ราคาของทุกคน",source:motorSource},
  exclusions: {title:"ข้อยกเว้น",description:"เหตุหรือเงื่อนไขที่สัญญาระบุว่าไม่อยู่ในความคุ้มครอง",caution:"ไม่เหมือนข้อมูลที่ยังไม่ทราบ และไม่เหมือนระยะรอคอย ต้องอ่านของแผนและฉบับที่เลือก",source:healthWording},
  renewal: {title:"การต่ออายุ",description:"การทำให้ความคุ้มครองดำเนินต่อเมื่อครบรอบสัญญา ตามเกณฑ์และอายุที่กำหนด",caution:"อายุรับสมัคร อายุที่ต่อได้ และอายุสิ้นสุดคุ้มครองเป็นคนละค่า ต่อได้ไม่ได้แปลว่าเบี้ยจะเท่าเดิม",source:"https://www.allianz.co.th/th_TH/health/lump-sum/beyond-care.html"},
  entry_age: {title:"อายุและคุณสมบัติผู้สมัคร",description:"เงื่อนไขสำหรับเริ่มทำแผน เช่น อายุ อาชีพ และข้อกำหนดของช่องทางขาย",caution:"อายุอยู่ในช่วงไม่ได้รับรองการอนุมัติ และห้ามนำอายุต่ออายุมาใช้แทนอายุสมัครใหม่",source:healthSource},
  coverage_term: {title:"ระยะคุ้มครอง",description:"ช่วงเวลาที่สัญญาให้ความคุ้มครอง อาจระบุเป็นจำนวนปีหรือถึงอายุที่กำหนด",caution:"คุ้มครองถึงอายุ 99 ไม่ใช่คุ้มครองอีก 99 ปี และระยะชำระเบี้ยอาจสั้นกว่าระยะคุ้มครอง",source:lifeSource},
  payment_term: {title:"ระยะชำระเบี้ย",description:"จำนวนปีที่ต้องชำระเบี้ยตามแผน แยกจากงวดชำระ เช่น รายปีหรือรายเดือน",caution:"ตัวเลข 10/5 อาจหมายถึงคุ้มครอง 10 ปี จ่าย 5 ปี ต้องตรวจความหมายของแบบประกันนั้น",source:lifeSource},
  life_benefit: {title:"ผลประโยชน์ประกันชีวิต",description:"เงินที่คำนวณตามสูตรในสัญญาเมื่อเข้าเงื่อนไข เช่น เสียชีวิตหรืออยู่ครบสัญญา",caution:"สูตรอาจอ้างอิงทุน เบี้ยสะสม หรือมูลค่าเวนคืน อย่านำหลายสูตรมาบวกกันถ้าสัญญาให้เลือกเพียงค่าหนึ่ง",source:lifeSource},
  cashback: {title:"เงินคืนระหว่างสัญญา",description:"ผลประโยชน์ที่จ่ายเมื่ออยู่ครบช่วงเวลาหรือเข้าเงื่อนไขที่ระบุ",caution:"เปอร์เซ็นต์ของทุนประกันไม่ใช่อัตราผลตอบแทนต่อปี ต้องแยกส่วนที่รับประกันกับส่วนที่ไม่รับประกัน",source:lifeSource},
  surrender: {title:"มูลค่าเวนคืน",description:"มูลค่าที่สัญญากำหนดให้ได้รับเมื่อยุติสัญญาก่อนครบกำหนดและเข้าเงื่อนไขเวนคืน",caution:"ไม่จำเป็นต้องเท่ากับเบี้ยที่จ่ายไป และการยุติสัญญาทำให้ความคุ้มครองตามสัญญาสิ้นสุด",source:lifeSource},
  motor_class: {title:"ประเภทประกันรถยนต์",description:"ประเภทชั้นบอกกลุ่มความคุ้มครองของประกันภาคสมัครใจ เช่น ชั้น 1 หรือ 2+",caution:"ประเภทเดียวกันอาจมีทุน ส่วนแรก และเงื่อนไขต่างกัน ส่วน พ.ร.บ. เป็นภาคบังคับอีกประเภทหนึ่ง",source:motorSource},
  repair: {title:"ซ่อมอู่ / ซ่อมศูนย์",description:"ประเภทสถานซ่อมที่แผนกำหนดให้ใช้ เช่น อู่ในเครือหรือศูนย์บริการ",caution:"ไม่ได้แปลว่าเลือกซ่อมที่ใดก็ได้ ต้องตรวจเครือข่ายและข้อกำหนดของกรมธรรม์",source:motorSource},
  compulsory: {title:"พ.ร.บ. · ประกันรถภาคบังคับ",description:"ประกันภาคบังคับสำหรับความเสียหายต่อชีวิต ร่างกาย หรืออนามัยของผู้ประสบภัยจากรถตามเกณฑ์",caution:"ไม่ใช่ประกันซ่อมรถ และต่างจากค่ารักษาผู้ขับขี่/ผู้โดยสารในเอกสารแนบท้ายประกันภาคสมัครใจ",source:"https://www.axa.co.th/th/personal/car-insurance/compulsory"},
  travel_duration: {title:"ระยะเดินทาง / ระยะกรมธรรม์",description:"รายเที่ยวคุ้มครองทริปที่กำหนด ส่วนรายปีอาจครอบคลุมหลายทริปโดยจำกัดวันต่อทริป",caution:"ระยะสูงสุดต่อทริปไม่ใช่จำนวนวันที่เลือกซื้อจริง และต้องแยกในประเทศ ต่างประเทศ และเดินทางเข้าไทย",source:travelSource},
  travel_delay: {title:"การเดินทางล่าช้า",description:"ผลประโยชน์เมื่อการล่าช้าครบเวลาและเกิดจากสาเหตุที่แผนรับไว้",caution:"ไม่ใช่ทุกการล่าช้าจะได้รับเงิน ต้องดูชั่วโมงขั้นต่ำ เงินต่อช่วงเวลา เพดาน และกรณียกเลิกที่อาจนับต่างกัน",source:travelSource},
  lump_sum: {title:"เงินก้อนเมื่อนอนโรงพยาบาล",description:"เงินชดเชยเป็นก้อนเมื่อพักรักษาครบเงื่อนไขจำนวนวันที่กำหนด",caution:"ต่างจากเงินชดเชยรายวัน เช่น เงินก้อนเมื่อครบ 14 วัน ไม่ใช่จำนวนเงินนั้นคูณทุกวัน",source:"https://www.bangkokinsurance.com/th/product/accident/holiday"},
  valuation: {title:"ฐานประเมินมูลค่าทรัพย์สิน",description:"หลักที่สัญญาใช้ประเมินความเสียหายและจำนวนชดใช้ เช่น มูลค่าตามเงื่อนไขของทรัพย์สินนั้น",caution:"ทุนประกันไม่ใช่การรับรองว่าจะชดใช้เต็มทุนทุกเหตุ ต้องตรวจค่าเสื่อมและเงื่อนไขประเมินในกรมธรรม์",source:propertySource},
  pa: {title:"PA · ประกันอุบัติเหตุส่วนบุคคล",description:"ความคุ้มครองผลจากอุบัติเหตุตามรายการและนิยามในสัญญา เช่น ค่ารักษาหรือเสียชีวิต",caution:"ต่างจากประกันสุขภาพที่อาจคุ้มครองการเจ็บป่วยด้วย จักรยานยนต์และเหตุพิเศษอาจมีวงเงินต่างจากอุบัติเหตุทั่วไป",source:"https://www.bangkokinsurance.com/th/product/accident/holiday"},
  disability: {title:"ทุพพลภาพ / สูญเสียอวัยวะ",description:"ผลประโยชน์เมื่อเกิดความสูญเสียตามนิยามและระดับที่สัญญาระบุ",caution:"สูญเสียอวัยวะหนึ่งส่วนไม่จำเป็นต้องได้เงินเต็มทุน และไม่ใช่นิยามเดียวกับทุพพลภาพถาวรสิ้นเชิง",source:"https://www.bangkoklife.com/th/products/detail/286"},
  daily_allowance: {title:"เงินชดเชยรายวัน",description:"เงินตามอัตราต่อวันที่จ่ายเมื่อการพักรักษาเข้าเงื่อนไข ไม่ใช่การเบิกค่ารักษาตามใบเสร็จ",caution:"ตรวจจำนวนวันขั้นต่ำและสูงสุด แตกต่างจากเงินก้อนเมื่อพักรักษาครบจำนวนวัน",source:travelSource},
  cancellation: {title:"ยกเลิก / ลดจำนวนวันเดินทาง",description:"ความคุ้มครองค่าใช้จ่ายเมื่อยกเลิกก่อนเดินทาง หรือจำเป็นต้องจบทริปเร็วกว่ากำหนด ตามสาเหตุที่รับไว้",caution:"เป็นคนละผลประโยชน์และไม่ใช่การยกเลิกด้วยเหตุใดก็ได้ ต้องดูค่าใช้จ่ายที่เรียกคืนจากผู้ให้บริการได้ด้วย",source:travelSource},
  baggage: {title:"สัมภาระและทรัพย์สินระหว่างเดินทาง",description:"ความคุ้มครองกระเป๋าหรือทรัพย์สินจากเหตุที่กำหนด โดยอาจมีเพดานต่อชิ้นและต่อทริป",caution:"กระเป๋าล่าช้าต่างจากสูญหาย ข้อยกเว้นของมีค่าและหลักฐานที่ต้องใช้ขึ้นกับสัญญา",source:travelSource},
  evacuation: {title:"เคลื่อนย้ายฉุกเฉิน / ส่งศพกลับ",description:"ค่าเคลื่อนย้ายเพื่อรักษาพยาบาลฉุกเฉินกับการส่งศพกลับเป็นคนละผลประโยชน์",caution:"มักมีขั้นตอนประสานผู้ให้บริการและเงื่อนไขทางการแพทย์ ไม่ใช่งบเดินทางกลับที่เลือกใช้ได้ทุกเหตุ",source:travelSource},
  territory: {title:"พื้นที่คุ้มครอง",description:"ประเทศหรือสถานที่ที่ความคุ้มครองมีผลตามสัญญา",caution:"ชื่อบริษัทหรือประเทศของเว็บไซต์ไม่ได้บอกพื้นที่คุ้มครอง และบางผลประโยชน์อาจมีข้อจำกัดพื้นที่ต่างกัน",source:"https://www.allianz.co.th/th_TH/health/lump-sum/beyond-care.html"},
  insured_perils: {title:"ภัยที่คุ้มครอง",description:"สาเหตุความเสียหายที่สัญญารับไว้ เช่น ไฟไหม้ รถชน โจรกรรม หรือน้ำท่วม ตามรายการของแต่ละแผน",caution:"อัคคีภัยหมายถึงภัยจากไฟ แต่ไม่ใช่ความเสียหายทุกอย่าง และภัยหลายอย่างอาจใช้วงเงินร่วมกัน ต้องดูข้อยกเว้นและนิยามเหตุ",source:propertySource},
  property_use: {title:"ลักษณะและการใช้ทรัพย์สิน",description:"ประเภทอาคาร วัสดุ และการใช้งาน เช่น อยู่อาศัยเอง ให้เช่า หรือทำธุรกิจ เป็นเงื่อนไขในการรับประกัน",caution:"บ้านในพื้นที่เดียวกันอาจรับประกันต่างกัน ไม่ควรใช้เงื่อนไขบ้านอยู่อาศัยแทนร้านค้าหรืออาคารประเภทอื่น",source:propertySource},
  medical_expense: {title:"ค่ารักษาพยาบาลตามจริง",description:"ชดใช้ค่าใช้จ่ายที่เกิดขึ้นและเข้าเกณฑ์ ไม่เกินวงเงินที่แผนกำหนด",caution:"ต่างจากเงินชดเชยแบบก้อนหรือรายวัน และไม่ได้แปลว่าใบเสร็จทุกรายการอยู่ในความคุ้มครอง",source:travelSource},
} as const;

export type InsuranceTermKey = keyof typeof insuranceTerms;
export const fieldTermKeys: Record<string, InsuranceTermKey> = {
  annualLimit:"per_year",perDiseaseLimit:"per_disease",perAdmissionLimit:"per_admission",
  roomPerDay:"ipd",roomBasis:"ipd",roomMaxDays:"ipd",icuPerDay:"icu",icuMaxDays:"icu",
  opdPerYear:"opd",opdPerVisit:"opd",opdVisitsPerDay:"opd",copay:"copay",deductible:"deductible",waitingDays:"waiting",
  minEntryAge:"entry_age",maxEntryAge:"entry_age",eligibility:"entry_age",eligibilityConditions:"entry_age",occupationClass:"entry_age",renewalAge:"renewal",
  premiumTHB:"quote",price:"quote",sumAssured:"sum_assured",ownDamageLimit:"sum_assured",class:"motor_class",repairType:"repair",
  medicalPerPerson:"compulsory",voluntaryMedicalPerPerson:"compulsory",thirdPartyBodilyPerPerson:"third_party",thirdPartyBodilyPerEvent:"third_party",thirdPartyProperty:"third_party",
  combinedPropertyLimit:"shared_cap",sharedNaturalPerilsLimit:"shared_cap",buildingLimit:"sum_assured",contentsLimit:"sum_assured",valuation:"valuation",bundledLiability:"third_party",
  aggregateLimit:"per_year",perOccurrenceLimit:"third_party",coveredActivity:"third_party",
  lifeType:"life_benefit",deathFormula:"life_benefit",maturityFormula:"life_benefit",guaranteedCashback:"cashback",nonGuaranteedBenefit:"cashback",coverageYears:"coverage_term",coverageUntilAge:"coverage_term",paymentYears:"payment_term",paymentFrequency:"payment_term",
  policyDuration:"travel_duration",tripType:"travel_duration",region:"travel_duration",maxTripDays:"travel_duration",delayRate:"travel_delay",delayLimit:"travel_delay",delayTrigger:"travel_delay",
  hospitalAdmissionBenefit:"lump_sum",exclusions:"exclusions",
  deathBenefit:"pa",medicalPerAccident:"pa",motorcycleBenefit:"pa",homicideBenefit:"pa",publicAccidentBenefit:"pa",disabilityBenefit:"disability",dailyAllowance:"daily_allowance",dailyMaxDays:"daily_allowance",
  cancellationLimit:"cancellation",interruptionLimit:"cancellation",baggageLimit:"baggage",evacuationLimit:"evacuation",repatriationLimit:"evacuation",territory:"territory",locationRestrictions:"territory",
  delayHours:"travel_delay",delayPayment:"travel_delay",medicalLimit:"medical_expense",collisionLimit:"insured_perils",theftLimit:"insured_perils",fireLimit:"insured_perils",floodLimit:"insured_perils",fireCoverage:"insured_perils",burglaryCoverage:"insured_perils",includedPerils:"shared_cap",occupancy:"property_use",construction:"property_use",
};
